import { T, combos, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

const sourceQuestionPath = "Tmua/2016-2023paper/tmua-paper-2-specimen.pdf";
const sourceAnswerPath = "Tmua/2016-2023 answer key/tmua-specimen.pdf";

export const TMUA_SPECIMEN_P2 = defineHistoricPaper({
  id: "tmua-specimen-p2", edition: "Early Specimen", paper: 2,
  answers: "BBCAAFCCEEDACBEAEEBD", sourceQuestionPath, sourceAnswerPath,
  sourcePages: [3,3,4,5,5,6,7,8,8,9,10,10,11,11,12,12,13,14,15,16],
  questions: [
    { prompt: [p(text("The radius of the circle "), math(T`2x^2+2y^2-8x+12y+15=0`), text(" is"))], options: mo(T`\sqrt{\frac52}`,T`\sqrt{\frac{11}2}`,T`\sqrt{\frac{41}2}`,T`\sqrt{37}`,T`\sqrt{67}`) },
    { prompt: [p(text("Find the gradient at "), math("x=2"), text(" of")), d(T`y=\frac{(3x-2)^2}{x\sqrt x}`)], options: mo(T`\frac32\sqrt2`,T`3\sqrt2`,T`4\sqrt2`,T`\frac92\sqrt2`,T`6\sqrt2`) },
    { prompt: [p(text("An attempt to solve "), math(T`\sqrt{x+5}=x+3`), text(" squares both sides, rearranges to "), math(T`x^2+5x+4=0`), text(" and obtains "), math("x=-4,-1"), text(". Which statement is true?"))], options: to("Both are solutions.","Neither is a solution.","One is correct; the incorrect one arises from the first rearrangement.","One is correct; the incorrect one arises from squaring.","One is correct; the incorrect one arises from factorising.") },
    { prompt: [p(text("Cards A–E have fronts and backs A/3, B/4, C/1, D/7 and E/8. Which card is a counterexample to: every card with a vowel on its front has an even number on its back?"))], options: to("Card A","Card B","Card C","Card D","Card E") },
    { prompt: [p(text("Using "), math(T`2^5\approx3^3`), text(", estimate "), math(T`\log_3 2`), text("."))], options: mo(T`\frac35`,T`\frac23`,T`\frac32`,T`\frac53`,T`\frac12`,`2`) },
    { prompt: [p(text("A rectangle's area is 5600 cm² correct to 2 significant figures and its width is 80 cm correct to the nearest centimetre. Which expression gives the greatest possible height?"))], options: mo("70.5","75",T`\frac{5650}{80}`,T`\frac{5650}{80.5}`,T`\frac{5650}{75}`,T`\frac{5650}{79.5}`) },
    { prompt: [p(text("Which sketch represents "), math(T`(x+y)(x^2-xy+y^2)=1`), text("?")), fig("/questions/tmua-specimen-p2/q07.svg","Four candidate implicit-function graphs labelled A to D")], options: to("Graph A","Graph B","Graph C","Graph D") },
    { prompt: [p(text("For positive integer "), math("n"), text(", consider: the sum of four consecutive integers beginning at "), math("n"), text(" is a multiple of 6. Which is true?"))], options: to("True for all n","True exactly for odd n","True exactly for multiples of 3","True exactly for multiples of 6","Never true") },
    { prompt: [p(text("‘Every day next week, Fred will do at least one maths problem.’ If this is false, which statement is certainly true?"))], options: to("Every day he does more than one.","On some day he does more than one.","On no day does he do more than one.","Every day he does none.","On some day he does none.","On no day does he do none.") },
    { prompt: [p(text("Which is the graph of "), math(T`y=\log_x2`), text(" for "), math("x>1"), text("?")), fig("/questions/tmua-specimen-p2/q10.svg","Six candidate graphs labelled A to F")], options: to("Graph A","Graph B","Graph C","Graph D","Graph E","Graph F") },
    { prompt: [p(text("Which number is largest? All angles are in radians."))], options: mo(T`\tan\frac{3\pi}4`,T`\log_{10}100`,T`\sin^{10}\frac\pi2`,T`\log_2 10`,T`(\sqrt2-1)^{10}`) },
    { prompt: [p(text("A polynomial "), math("p(x)"), text(" satisfies "), math("p(1)=2"), text(". Which can be deduced?"))], options: mo(T`p(x)=(x-1)q(x)+2`,T`p(x)=(x+1)q(x)+2`,T`p(x)=(x-1)q(x)-2`,T`p(x)=(x+1)q(x)-2`,T`p(x)=(x-2)q(x)+1`,T`p(x)=(x+2)q(x)+1`,T`p(x)=(x-2)q(x)-1`,T`p(x)=(x+2)q(x)-1`) },
    { prompt: [p(text("Five runners are Fred, George, Hermione, Lavender and Ron. Fred beat George; Hermione beat Lavender; Lavender beat George; Ron beat George. With no ties, how many finishing orders are possible?"))], options: mo("1","6","12","18","24","120") },
    { prompt: [p(text("For a degree-five polynomial "), math(T`y=ax^5+bx^4+cx^3+dx^2+ex+f`), text(" with "), math("a\ne0"), text(", which pattern is impossible?"))], options: to("two local minima and two local maxima","one local minimum and two local maxima","one local minimum and one local maximum","no local minima or maxima") },
    { prompt: [p(text("For real "), math(T`a\ge b`), text(" and real "), math("c"), text(", which statements must hold?")), d(T`\text{I }-b\ge-a\qquad\text{II }a^2+b^2\ge2ab\qquad\text{III }ac\ge bc`)], options: combos },
    { prompt: [p(text("The sequence is defined by")), d(T`a_1=2,\qquad a_{n+1}=a_n+(-1)^n\quad(n\ge1)`), p(text("Find "), math(T`\sum_{n=1}^{100}a_n`), text("."))], options: mo("150","250","-4750","5150",T`4(1-(\frac12)^{100})`,T`4((\frac32)^{100}-1)`) },
    { prompt: [p(text("Let "), math("S"), text(" be a set of positive integers. An integer "), math("n"), text(" is an S-number exactly when every factor "), math("m>1"), text(" of "), math("n"), text(" is a multiple of some number in "), math("S"), text(". Therefore "), math("n"), text(" is not an S-number exactly when"))], options: to("for every factor m, some S-number does not divide m","for every factor m, no S-number divides m","for every factor m, every S-number divides m","for some factor m, some S-number does not divide m","for some factor m, no S-number divides m","for some factor m, every S-number divides m") },
    { prompt: [p(text("Five numbers have mean 0 and range 20. What is the largest possible median?"))], options: mo("0","4",T`4\frac12`,T`6\frac12`,`8`,`20`) },
    { prompt: [p(text("Positive "), math("a,b,c"), text(" are such that "), math(T`x^3+ax^2=bx+c`), text(" has three real roots, one positive and two negative. Describe the roots of "), math(T`x^3+c=ax^2+bx`), text("."))], options: to("three: one positive, two negative","three: two positive, one negative","three, signs depend on a,b,c","exactly one positive","exactly one negative","exactly one, sign depends on a,b,c","one or three, depending on a,b,c") },
    { prompt: [p(text("Five logicians say: P: an odd number of these statements are true. Q: both women's statements are true. R: my first name is Robert and P is true. S: exactly one man's statement is true. T: neither woman's statement is true. How many statements can be simultaneously true?"))], options: to("none","1 only","2 only","3 only","4 only","none or 1 only","1 or 2 only","2 or 3 only") },
  ],
});
