import { T, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2021_P1 = defineHistoricPaper({
  id: "tmua-2021-p1", edition: "2021", paper: 1, answers: "FFGBFDGACBAECBCBABBD",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-1-2021.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2021.pdf",
  questions: [
    { prompt: [p(text("Two equal-radius circles have centres "), math("(-2,1)"), text(" and "), math("(3,-2)"), text(" and intersect twice. Find the line through their intersection points."))], options: mo(T`3x-5y=4`, T`3x+5y=-1`, T`5x-3y=-4`, T`5x-3y=-1`, T`5x-3y=1`, T`5x-3y=4`, T`5x+3y=1`), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("The curve "), math(T`y=x^3-6x+3`), text(" has turning points at "), math(T`x=\alpha,\beta`), text(" with "), math(T`\beta>\alpha`), text(". Find")), d(T`\int_\alpha^\beta(x^3-6x+3)\,\mathrm dx`)], options: mo(T`-8\sqrt2`, "-10", T`-10+6\sqrt2`, "0", T`12-8\sqrt2`, T`6\sqrt2`, "12"), knowledge: "integration" },
    { prompt: [p(text("An arithmetic progression and a convergent geometric progression each have first term "), math(T`\frac12`), text(". The sums of their second and third terms are respectively "), math(T`\frac12`), text(" and "), math(T`\frac18`), text(". Find the geometric progression's sum to infinity."))], options: mo("-2", "-1", T`-\frac12`, T`-\frac13`, T`\frac13`, T`\frac12`, "1", "2"), knowledge: "sequences-and-series" },
    { prompt: [p(text("Find the minimum value of")), d(T`2^{2x}-2^{x+3}+4`)], options: mo("-16", "-12", "-8", "0", "4", "20"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("For positive integers "), math("m,n"), text(",")), d(T`f(mn)=\begin{cases}f(m)f(n),&3\mid mn\\mn,&3\nmid mn\end{cases}`), p(text("Given "), math(T`f(9)+f(16)-f(24)=0`), text(", find "), math("f(3)"), text("."))], options: mo(T`\frac83`, T`2\sqrt2`, "3", T`\frac{16}5`, T`3\sqrt2`, "4") },
    { prompt: [p(text("For")), d(T`f(x)=\frac{\cos x+3}{7+5\cos x-\sin^2x}`), p(text("find the positive difference between its maximum and minimum values."))], options: mo("0", T`\frac13`, T`\frac12`, T`\frac23`, "1", "2"), knowledge: "trigonometry" },
    { prompt: [p(text("The function "), math("f"), text(" satisfies "), math(T`f(0)=0`), text(" and "), math(T`xf(x)>0`), text(" for non-zero "), math("x"), text(". Given")), d(T`\int_{-2}^{2}f(x)\,\mathrm dx=4,\qquad\int_{-2}^{2}|f(x)|\,\mathrm dx=8`), p(text("evaluate")), d(T`\int_{-2}^{0}f(|x|)\,\mathrm dx`)], options: mo("-8", "-6", "-4", "-2", "2", "4", "6", "8"), knowledge: "integration" },
    { prompt: [p(text("Each line "), math(T`y=2x+3`), text(" and "), math(T`y=4x-2`), text(" is tangent to "), math(T`y=x^2+bx+c`), text(". Find "), math(T`b-c`), text("."))], options: mo("-9", "-5.5", "-1", "5", "6", "14"), knowledge: "coordinate-geometry" },
    { prompt: [p(text("Find the area enclosed by")), d(T`|x|+|y|=1`)], options: mo(T`\frac12`, "1", "2", "4", T`\frac{\sqrt2}{2}`, T`\sqrt2`, T`2\sqrt2`), knowledge: "coordinate-geometry" },
    { prompt: [p(text("Use the trapezium rule with three strips to estimate")), d(T`\int_{1/2}^{2}2\log_{10}x\,\mathrm dx`)], options: mo(T`\log_{10}\frac{\sqrt6}{2}`, T`\log_{10}\frac32`, T`\log_{10}\frac94`, T`\log_{10}3`, T`\log_{10}\frac{81}{16}`, T`\log_{10}\frac{\sqrt{23}}2`), knowledge: "integration" },
    { prompt: [p(text("For")), d(T`f(x)=x^{1/7}(x^2-x+1)`), p(text("find the fraction of "), math(T`0<x<1`), text(" on which "), math("f"), text(" is decreasing."))], options: mo(T`\frac2{15}`, T`\frac15`, T`\frac13`, T`\frac12`, T`\frac23`, T`\frac45`, T`\frac{13}{15}`), knowledge: "differentiation" },
    { prompt: [p(text("The minimum of "), math(T`x^4-p^2x^2`), text(" is "), math("-9"), text(", where "), math("p"), text(" is real. Find the minimum of "), math(T`x^2-px+6`), text("."))], options: mo("-3", T`6-\frac{3\sqrt2}{2}`, T`\frac32`, "3", T`\frac92`, T`6+\frac{3\sqrt2}{2}`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("For every integer "), math("n"), text(",")), d(T`\int_n^{n+1}f(x)\,\mathrm dx=n+1`), p(text("evaluate")), d(T`\sum_{r=1}^{8}\int_0^r f(x)\,\mathrm dx`)], options: mo("36", "84", "120", "165", "204", "288"), knowledge: "integration" },
    { prompt: [p(text("Using radians, find the number of distinct solutions to")), d(T`(x+1)(3-x)=2(1-\cos(\pi x))`)], options: mo("2", "3", "4", "5", "6", "7"), knowledge: "trigonometry" },
    { prompt: [fig("/questions/tmua-2021-p1/q15.svg", "Periodic triangular wave f(x), rising from (0,0) to (1,1), falling to (2,0), and repeating."), p(text("The graph consists of alternating line segments of gradient 1 and −1 and continues for all "), math("x"), text(". Define")), d(T`g(x)=\sum_{r=1}^{10}f(2^{r-1}x)`), p(text("Find")), d(T`\int_0^1g(x)\,\mathrm dx`)], options: mo(T`\frac{1023}{1024}`, T`\frac{1023}{512}`, "5", "10", T`\frac{55}2`, "55"), knowledge: "integration", skills: ["diagram-interpretation", "multi-step-planning"] },
    { prompt: [p(text("In the expansion of "), math(T`(a+bx)^n`), text(", the third ascending term is "), math(T`105x^2`), text(", the fourth ascending term is "), math(T`210x^3`), text(", and the fourth descending term is also "), math(T`210x^3`), text(". Find "), math(T`(a/b)^2`), text("."))], options: mo(T`\frac14`, T`\frac49`, T`\frac{25}{36}`, T`\frac56`, "1"), knowledge: "binomial-expansion" },
    { prompt: [p(text("Which sketch represents")), d(T`\sin(x^2+y^2)=\frac12,\qquad x^2+y^2\le8\pi`), fig("/questions/tmua-2021-p1/q17.svg", "Five answer sketches A to E, each showing a different set of concentric circles.")], options: to("Sketch A", "Sketch B", "Sketch C", "Sketch D", "Sketch E"), knowledge: "graphs-of-functions", skills: ["diagram-interpretation", "representation-switching"] },
    { prompt: [p(text("The curve "), math(T`x=y^2-6y+11`), text(" is rotated 90° clockwise about "), math(T`P=(-2,3)`), text(". Find the equation of the image curve."))], options: mo(T`y=-x^2-4x-3`, T`y=-x^2-4x-5`, T`y=-x^2-6x-7`, T`y=-x^2-6x-11`, T`y=x^2-4x+5`, T`y=x^2+4x+3`, T`y=x^2-6x+11`, T`y=x^2+6x+7`), knowledge: "coordinate-geometry" },
    { prompt: [p(text("The equation")), d(T`\sin^2\!\left(4^{\cos\theta}\times60^\circ\right)=\frac34`), p(text("has exactly three solutions on "), math(T`0^\circ\le\theta\le x^\circ`), text(". Find the range of possible "), math("x"), text("."))], options: mo(T`90\le x<120`, T`90\le x<270`, T`120\le x<240`, T`270\le x<300`, T`300\le x<360`, T`450\le x<630`), knowledge: "trigonometry" },
    { prompt: [p(text("Find the length of the curve")), d(T`2\log_{10}(x-y)=\log_{10}(2-2x)+\log_{10}(y+5)`)], options: mo("5", "10", "15", T`3\pi`, T`9\pi`, T`12\pi`), knowledge: "coordinate-geometry" },
  ],
});
