import { T, d, defineHistoricPaper, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2020_P1 = defineHistoricPaper({
  id: "tmua-2020-p1", edition: "2020", paper: 1, answers: "CCBDACADC AEDFECCAAEC".replaceAll(" ", ""),
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-1-2020.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2020.pdf",
  questions: [
    { prompt: [p(text("Differentiate with respect to "), math("x"), text(":")), d(T`\frac{x^3-5x^2}{2x\sqrt{x}}`)], options: mo(T`-\frac{\sqrt{x}}2`, T`\frac{\sqrt{x}}4`, T`\frac{3x-5}{4\sqrt{x}}`, T`\frac{3\sqrt{x}-5}{4\sqrt{x}}`, T`\frac{3\sqrt{x}-10}{3\sqrt{x}}`, T`\frac{3x^2-10x}{3\sqrt{x}}`), knowledge: "differentiation" },
    { prompt: [p(math(T`2x+1`), text(" and "), math(T`x-2`), text(" are factors of "), math(T`2x^3+px^2+q`), text(". Find "), math(T`2p+q`), text("."))], options: mo("-10", T`-\frac{38}5`, "-22", "22", T`\frac{38}5`, "10") },
    { prompt: [p(text("Find the complete solution set of")), d(T`(x+4)(x+3)(1-x)>0,\qquad(x+2)(x-2)<0`)], options: mo(T`1<x<2`, T`-2<x<1`, T`-2<x<2`, T`x<-2\text{ or }x>1`, T`x<-4\text{ or }x>2`, T`x<-4\text{ or }-3<x<1`, T`-4<x<-2\text{ or }x>1`) },
    { prompt: [p(text("Terms 1, 2 and 3 of a geometric progression are terms 1, 4 and 6 respectively of an arithmetic progression. The GP has sum to infinity 12. Find its first term."))], options: mo("1", "2", "3", "4", "5", "6"), knowledge: "sequences-and-series" },
    { prompt: [p(text("The curve "), math(T`y=px^2+6x-q`), text(" has symmetry line "), math(T`x=-\frac14`), text(" and touches the "), math("x"), text("-axis once. Find "), math(T`p+8q`), text("."))], options: mo("6", "18", "21", "25", "38"), knowledge: "graphs-of-functions" },
    { prompt: [p(text("Find the maximum of")), d(T`f(x)=\frac1{5^{2x}-4(5^x)+7}`)], options: mo("1", T`\frac17`, T`\frac14`, T`\frac13`, "3", "4", "7"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Given")), d(T`2^{3x}=8^{y+3},\qquad4^{x+1}=\frac{16^{y+1}}{8^{y+3}}`), p(text("find "), math(T`x+y`), text("."))], options: mo("-23", "-22", "-15", "-14", "-11", "-10"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("For "), math(T`f(x)=(p-x)(x+2)`), text(", find all "), math("p"), text(" for which the maximum of "), math("f"), text(" is less than 4."))], options: mo(T`-2-4\sqrt2<p<-2+4\sqrt2`, T`-2-2\sqrt2<p<-2+2\sqrt2`, T`-2\sqrt5<p<2\sqrt5`, T`-6<p<2`, T`-4<p<0`, T`-2<p<2`), knowledge: "graphs-of-functions" },
    { prompt: [p(math(T`x^2-14x+9=(x-\alpha)(x-\beta)`), text(" with positive "), math(T`\alpha,\beta`), text(". Which expression factorises as "), math(T`(x-\sqrt\alpha)(x-\sqrt\beta)`), text("?"))], options: mo(T`x^2-\sqrt{10}x+3`, T`x^2-\sqrt{14}x+3`, T`x^2-\sqrt{20}x+3`, T`x^2-178x+81`, T`x^2-176x+81`, T`x^2+196x+81`) },
    { prompt: [p(text("Apply to "), math(T`y=4x^2`), text(": translate by "), math(T`\binom3{-5}`), text(", reflect in the "), math("x"), text("-axis, then stretch parallel to the "), math("x"), text("-axis by scale factor 2. Find the resulting equation."))], options: mo(T`y=-x^2+12x-31`, T`y=-x^2+12x-41`, T`y=x^2+12x+31`, T`y=x^2+12x+41`, T`y=-16x^2+48x-31`, T`y=-16x^2+48x-41`, T`y=16x^2-48x+31`, T`y=16x^2-48x+41`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("A quadratic crosses the "), math("x"), text("-axis at "), math("2"), text(" and "), math(T`q>2`), text(". Region R is between the curve and axis from "), math("x=0"), text(" to "), math("x=2"), text("; region S is between them from "), math("x=2"), text(" to "), math("x=q"), text(". Find "), math("q"), text(" when the two areas are equal."))], options: mo(T`\sqrt6`, "3", T`\frac{18}5`, "4", "6", T`\frac{33}5`), knowledge: "integration" },
    { prompt: [p(text("How many real solutions does")), d(T`3\cos x=\sqrt{x}`), p(text("have, with "), math("x"), text(" in radians?"))], options: to("0", "1", "2", "3", "4", "5", "infinitely many"), knowledge: "trigonometry" },
    { prompt: [p(text("Find the coefficient of "), math(T`x^2y^4`), text(" in")), d(T`(1+x+y^2)^7`)], options: mo("6", "10", "21", "35", "105", "210"), knowledge: "binomial-expansion" },
    { prompt: [p(text("The area enclosed by "), math(T`y=mx`), text(" and "), math(T`y=x^3`), text(" is 6. Find "), math("m"), text("."))], options: mo("2", "4", T`\sqrt3`, T`\sqrt6`, T`2\sqrt3`, T`2\sqrt6`), knowledge: "integration" },
    { prompt: [p(text("Find the positive difference between the real values of "), math("x"), text(" satisfying")), d(T`(\log_2x)^4+12\left(\log_2\frac1x\right)^2-26=0`)], options: mo("4", "16", "15", T`\frac{17}4`, T`\frac{255}{16}`, T`\frac{257}{16}`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Circles "), math(T`(x+2)^2+(y-1)^2=3`), text(" and "), math(T`(x-4)^2+(y-1)^2=3`), text(" share a positive-gradient tangent "), math("l"), text(". If its acute angle to the "), math("x"), text("-axis is "), math("\theta"), text(", find "), math(T`\tan\theta`), text("."))], options: mo("1", T`\frac12`, T`\frac{\sqrt2}{2}`, T`\sqrt2`, T`\frac{\sqrt2}{6}`, T`\frac{\sqrt3}{6}`, T`\frac{\sqrt3}{3}`, T`\sqrt3`), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("Find the complete set of "), math("m"), text(" in terms of "), math("c"), text(" such that "), math(T`y=mx+c`), text(" and "), math(T`y=\sqrt{x}`), text(" intersect twice."))], options: mo(T`0<m<\frac1{4c}`, T`0<m<4c^2`, T`m>\frac1{4c}`, T`m<\frac1{4c}`, T`m>4c^2`, T`m<4c^2`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("For "), math(T`0^\circ\le x\le180^\circ`), text(", determine the number and sum of solutions of")), d(T`1-2\cos^2x=|\cos x|`)], options: to("2 solutions; sum 180°", "2 solutions; sum 240°", "3 solutions; sum 180°", "3 solutions; sum 360°", "4 solutions; sum 240°", "4 solutions; sum 360°"), knowledge: "trigonometry" },
    { prompt: [p(text("Find the smallest positive integer "), math("x"), text(" for which "), math(T`x^2-52x-52>0`), text("."))], options: mo("26", "27", "51", "52", "53", "54") },
    { prompt: [p(text("For how many values of "), math("a"), text(" does")), d(T`(x-a)(x^2-x+a)=0`), p(text("have exactly two distinct real solutions in "), math("x"), text("?"))], options: to("0", "1", "2", "3", "4", "more than 4") },
  ],
});
