import { T, combos, d, defineHistoricPaper, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2018_P2 = defineHistoricPaper({
  id: "tmua-2018-p2", edition: "2018", paper: 2, answers: "CBFDACBDFBAFFEGFCCCB",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-2-2018.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2018.pdf",
  questions: [
    { prompt: [p(text("For "), math("x>0"), text(",")), d(T`f(x)=\frac{x^3-4x}{2\sqrt{x}}`), p(text("find "), math(T`f'(4)`), text("."))], options: mo("3", "9", "9.5", "12", "39.5", "88"), knowledge: "differentiation" },
    { prompt: [p(text("Find the constant term in")), d(T`\left(x^6-\frac1{2x}\right)^{12}`)], options: mo("-495", "-220", "-66", "66", "220", "495"), knowledge: "binomial-expansion" },
    { prompt: [p(text("A two-part car journey has average speeds "), math("u,v"), text(". Which examples counter the claim that its overall average is "), math(T`\frac12(u+v)`), text("?")), p(text("I — 100 km at 50 km/h, then 100 km at 40 km/h.")), p(text("II — one hour at 50 km/h, then one hour at 40 km/h.")), p(text("III — 80 km at 50 km/h, then 100 km at 40 km/h."))], options: combos, knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("Non-zero real "), math("c"), text(" makes "), math(T`\cos x=c`), text(" have two solutions on "), math(T`0<x<3\pi/2`), text(". How many solutions does "), math(T`\cos^2(2x)=c^2`), text(" have on the same interval?"))], options: mo("2", "3", "4", "6", "7", "8"), knowledge: "trigonometry" },
    { prompt: [p(text("A quadrilateral has perpendicular diagonals. Which must hold?")), p(text("I — One diagonal is an axis of symmetry.")), p(text("II — The side midpoints form a square."))], options: to("neither", "I only", "II only", "I and II"), knowledge: "coordinate-geometry", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("Which function counters the claim "), math(T`f'(x)>0\ \forall x\Rightarrow f(x)>0\ \forall x`), text("?"))], options: mo(T`x^2+1`, T`x^2-1`, T`x^3+x+1`, T`1-x`, T`2x`), knowledge: "differentiation", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("APs "), math(T`11,14,17,\ldots`), text(" and "), math(T`2,7,12,\ldots`), text(" share some terms. Let "), math("N"), text(" be the 20th common term. Find its remainder mod 7."))], options: mo("0", "1", "2", "3", "4", "5", "6"), knowledge: "sequences-and-series" },
    { prompt: [p(text("A valid mountain-profile code has "), math("n"), text(" U strokes and "), math("n"), text(" D strokes, starts and ends at sea level, and never goes below it. Which transformations always preserve validity?")), p(text("I — reverse the code.")), p(text("II — swap every U and D.")), p(text("III — add U at the start and D at the end."))], options: combos, knowledge: "mathematical-logic", skills: ["condition-checking", "counterexample-construction"] },
    { prompt: [p(text("An attempted solution of")), d(T`4x\sqrt{2x-1}=10x-5`), p(text("factors the right side, squares in step III, then divides by "), math(T`2x-1`), text(" in IV to obtain "), math(T`x=5/8,5/2`), text(". Which diagnosis is correct?"))], options: to("Correct", "Only one root; error II", "Only one root; error III", "Only one root; error IV", "Another root; error II", "Another root; error III", "Another root; error IV"), knowledge: "errors-in-proof", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("For all real "), math("x"), text(" and real "), math("a"), text(" which conditions are necessary and sufficient for symmetry about "), math(T`x=a`), text("?")), d(T`\mathrm I\ f(a-x)=f(a+x)\qquad\mathrm{II}\ f(2a-x)=f(x)\qquad\mathrm{III}\ f(a-x)=f(x)`)], options: to("I yes; II yes; III yes", "I yes; II yes; III no", "I yes; II no; III yes", "I yes; II no; III no", "I no; II yes; III yes", "I no; II yes; III no", "I no; II no; III yes", "all no"), knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "representation-switching"] },
    { prompt: [p(text("For real "), math("m,c"), text(", consider "), math(T`2^x=mx+c`), text(". Which statements are true?")), p(text("I — A negative solution is possible only if "), math("c>1"), text(".")), p(text("II — It has two distinct real solutions if "), math("c>1"), text(".")), p(text("III — It has two distinct positive roots iff "), math("c≤1"), text("."))], options: combos, knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("Negate: for every positive integer "), math("N"), text(" there exists positive "), math("K"), text(" such that "), math(T`N(Km+1)-1`), text(" is non-prime for every positive "), math("m"), text("."))], options: to("∀N ∃K ∃m: prime", "∀N ∃K ∃m: non-prime", "∀N ∃K ∀m: non-prime", "∀N ∀K ∀m: non-prime", "∃N ∀K ∃m: non-prime", "∃N ∀K ∃m: prime", "∃N ∀K ∀m: prime", "∃N ∃K with no m making it prime"), knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("An attempted proof of "), math(T`\tan\theta>0\Rightarrow\sin\theta+\cos\theta>1`), text(" derives "), math(T`(\sin\theta+\cos\theta)^2>1`), text(" in IV and then removes the square in V. Where is the first error?"))], options: to("Correct", "I", "II", "III", "IV", "V"), knowledge: "errors-in-proof", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("In triangle "), math("PQR"), text(", "), math(T`PR=2`), text(", "), math(T`QR=p`), text(" and "), math(T`\angle RPQ=30^\circ`), text(". For which "), math("p"), text(" is "), math("PQ"), text(" uniquely determined?"))], options: mo(T`p=1`, T`p=\sqrt3`, T`1\le p<2`, T`\sqrt3\le p<2`, T`p=1\text{ or }p\ge2`, T`p=\sqrt3\text{ or }p\ge2`, T`p<2`, T`p\ge2`), knowledge: "trigonometry", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("Let "), math(T`f=x^3+3qx^2+2`), text(". If "), math(T`f(x)=0`), text(" has three distinct real roots, which must follow?")), p(text("I — "), math(T`f(x)+1=0`), text(" has three distinct roots.")), p(text("II — "), math(T`f(x+1)=0`), text(" has three distinct roots.")), p(text("III — "), math(T`f(-x)-1=0`), text(" has three distinct roots."))], options: combos, knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("An integer AP has terms "), math(T`x_1,x_2,\ldots`), text(". If the first "), math("n"), text(" terms have integer median, which must hold?")), p(text("I — first "), math("n+2"), text(" terms have integer median.")), p(text("II — first "), math("2n"), text(" terms have integer median.")), p(text("III — "), math(T`x_2,x_4,\ldots,x_{2n}`), text(" have integer median."))], options: combos, knowledge: "sequences-and-series", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A squaresum is a sum of two integer squares. Fermat's theorem says it is a squaresum iff each prime congruent to 3 mod 4 has even exponent. Which statement is false?"))], options: to("Every square is a squaresum.", "A product of squaresums is a squaresum.", "If NM is a squaresum, then N and M are squaresums.", "For non-squaresum N, some product k of awkward primes makes kN a squaresum."), knowledge: "mathematical-proof", skills: ["condition-checking", "counterexample-construction"] },
    { prompt: [p(text("For polynomial "), math("f"), text(", which is necessary for")), d(T`\frac{f(a)+f(b)}2\ge f\left(\frac{a+b}2\right)`), p(text("for every real "), math("a<b"), text("?"))], options: mo(T`f\ge0`, T`f'\ge0`, T`f''\ge0`, T`f\le0`, T`f'\le0`, T`f''\le0`), knowledge: "differentiation", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("For "), math(T`x>y>z>1`), text(", which inequality must hold?"))], options: mo(T`\frac{2^{z+1}}{2^x}>\frac{2^x+2^z}{2^y}`, T`2>\frac{3^x+3^z}{3^y}`, T`\frac{2\cdot5^x}{5^z}>\frac{5^x+5^z}{5^y}`, T`2<\frac{7^x+7^z}{7^y}`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("For real "), math("p"), text(", "), math(T`\sqrt{x+p}+\sqrt{x}=p`), text(" has at least one real "), math("x"), text(" solution. Find all possible "), math("p"), text("."))], options: mo(T`p=0\text{ or }p=1`, T`p=0\text{ or }p\ge1`, T`p\ge-x`, T`p\ge\sqrt{x}`, T`p\ge0`, T`p\ge1`) },
  ],
});
