import { T, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2018_P1 = defineHistoricPaper({
  id: "tmua-2018-p1", edition: "2018", paper: 1, answers: "DCEGDEADBECFCBEFABDE",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-1-2018.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2018.pdf",
  questions: [
    { prompt: [p(text("Evaluate")), d(T`\int_1^4\frac{3-2x}{x\sqrt{x}}\,\mathrm dx`)], options: mo(T`-\frac{13}2`, T`-\frac{85}{16}`, T`-\frac{13}8`, "-1", T`-\frac14`, T`\frac74`, "7"), knowledge: "integration" },
    { prompt: [p(text("An arithmetic progression has first term "), math("a"), text(" and difference "), math("d"), text(". Its first-five sum equals its first-eight sum. Relate "), math("a,d"), text("."))], options: mo(T`a=-\frac{38}3d`, T`a=-7d`, T`a=-6d`, T`a=6d`, T`a=7d`, T`a=\frac{38}3d`), knowledge: "sequences-and-series" },
    { prompt: [p(text("Find the shortest distance between "), math(T`(x+2)^2+(y-3)^2=18`), text(" and "), math(T`(x-7)^2+(y+6)^2=2`), text("."))], options: mo("0", "4", "16", T`2\sqrt2`, T`5\sqrt2`), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("For real "), math("a"), text(", when do")), d(T`3x^2+2xy=4,\qquad x+y=a`), p(text("have two distinct real "), math("x"), text(" solutions?"))], options: to("no a", "−2 < a < 2", "−1 < a < 1", "a = 0", "a < −1 or a > 1", "a < −2 or a > 2", "all real a") },
    { prompt: [p(text("Let "), math(T`f=x^3+ax^2+bx+c`), text(", where "), math(T`a,b,c`), text(" are 1, 2, 3 in some order. Let "), math("R,S"), text(" be remainders on division by "), math(T`x+2,x+3`), text(". Maximise "), math(T`R-S`), text("."))], options: mo("-26", "5", "7", "17", "29") },
    { prompt: [p(text("How many solutions has")), d(T`x\sin2x=\cos2x,\qquad0\le x\le2\pi?`)], options: mo("0", "1", "2", "3", "4"), knowledge: "trigonometry" },
    { prompt: [p(text("Non-zero "), math("k"), text(" makes the "), math(T`x^6`), text(" coefficients in "), math(T`(1+kx^2)^7`), text(" and "), math(T`(k+x)^{10}`), text(" equal. Find "), math("k"), text("."))], options: mo(T`\frac16`, "6", T`\frac{\sqrt6}{6}`, T`\sqrt6`, T`\frac{\sqrt{30}}{30}`, T`\sqrt{30}`), knowledge: "binomial-expansion" },
    { prompt: [p(text("A GP has sum to infinity 6 and the sum of squared terms is 12. Find the sum of cubed terms."))], options: mo("8", "18", "24", T`\frac{216}7`, "72", "216"), knowledge: "sequences-and-series" },
    { prompt: [p(text("Find "), math("c"), text(" such that "), math(T`2x^3-3x^2-12x+c=0`), text(" has three distinct real roots."))], options: mo(T`-20<c<7`, T`-7<c<20`, T`c>7`, T`c>-7`, T`c<20`, T`c<-20`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("If "), math(T`|2-x|\le6`), text(" and "), math(T`|y+2|\le4`), text(", find the greatest "), math(T`|xy|`), text("."))], options: to("16", "24", "32", "40", "48", "no greatest value") },
    { prompt: [p(text("The line "), math(T`y=mx+5`), text(" with "), math("m>0"), text(" is normal to "), math(T`y=10-x^2`), text(" at "), math(T`(p,q)`), text(". Find "), math("p"), text("."))], options: mo(T`\frac{\sqrt2}{6}`, T`-\frac{\sqrt2}{6}`, T`\frac{3\sqrt2}{2}`, T`-\frac{3\sqrt2}{2}`, T`\sqrt5`, T`-\sqrt5`), knowledge: "differentiation" },
    { prompt: [p(text("Let "), math(T`f=x(x-p)(x-q)(r-x)`), text(" with "), math(T`0<p<q<r`), text(" and")), d(T`\int_0^rf(x)\,dx=0,\qquad\int_0^qf(x)\,dx=-2,\qquad\int_p^rf(x)\,dx=-3`), p(text("Find the total area between the curve and axis on "), math(T`[0,r]`), text("."))], options: mo("0", "1", "4", "5", "6", "10"), knowledge: "integration" },
    { prompt: [p(text("The graph shown is "), math(T`y=f'(x)`), text(". Which labelled point corresponds to a local minimum of "), math("f"), text("?")), fig("/questions/tmua-2018-p1/q13.svg", "Derivative curve crossing the x-axis downward at A, reaching a minimum B, crossing upward at C, passing D, peaking E, and touching the axis at F.")], options: to("A", "B", "C", "D", "E", "F"), knowledge: "differentiation", skills: ["diagram-interpretation", "condition-checking"] },
    { prompt: [p(text("The line "), math(T`y=mx+4`), text(" passes through "), math(T`(3,\log_2p)`), text(" and "), math(T`(\log_2p,4)`), text(". Find possible "), math("p"), text("."))], options: to("1 and 4", "1 and 16", "1/4 and 4", "1/4 and 64", "1/64 and 4", "1/64 and 16"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Find the sum of real roots of")), d(T`3^x-(\sqrt3)^{x+4}+20=0`)], options: mo("1", "4", "9", T`\log_3 20`, T`2\log_3 20`, T`4\log_3 20`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("For "), math(T`y=x^2+bx+2`), text(" with "), math("b≥0"), text(", find "), math("b"), text(" minimising the distance from the origin to the stationary point."))], options: mo("0", "1", "2", T`2\sqrt6`, T`\sqrt2`, T`\sqrt6`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("Two data sets have means 15 and 20. Exchanging one datum raises the first mean to 16 and lowers the second to 17. Find the combined mean."))], options: to("16 1/4", "16 1/3", "16 1/2", "16 2/3", "16 3/4"), knowledge: "gcse-supporting-knowledge" },
    { prompt: [p(text("Find the smallest positive "), math("a"), text(" such that "), math(T`x=a`), text(" is a symmetry line of "), math(T`y=\sin(2x-4\pi/3)`), text("."))], options: mo(T`\frac\pi{12}`, T`\frac{5\pi}{12}`, T`\frac{7\pi}{12}`, T`\frac{11\pi}{12}`, T`\frac{19\pi}{12}`), knowledge: "trigonometry" },
    { prompt: [p(text("A triangle has "), math(T`AB=10`), text(", "), math(T`BC=7`), text(" and specified "), math(T`\angle A=\theta`), text(". Of the two possible triangles, the larger has three times the smaller's area. Find "), math(T`\cos\theta`), text("."))], options: mo(T`\frac57`, T`\frac{151}{200}`, T`\frac{2\sqrt2}{5}`, T`\frac{\sqrt{17}}5`, T`\frac{\sqrt{51}}8`, T`\frac{\sqrt{34}}8`), knowledge: "trigonometry" },
    { prompt: [p(text("Evaluate")), d(T`\sum_{k=0}^{90}\sin^2(k^\circ)`)], options: mo("0.5", "1", "1.5", "45", "45.5", "46"), knowledge: "trigonometry" },
  ],
});
