import { T, d, defineHistoricPaper, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2017_P1 = defineHistoricPaper({
  id: "tmua-2017-p1", edition: "2017", paper: 1, answers: "CCABCBBAFEABCFBEDADE",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-1-2017.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2017.pdf",
  questions: [
    { prompt: [p(text("Given")), d(T`\frac{dy}{dx}=3x^2-\frac{2-3x}{x^3},\quad x\ne0,\qquad y(1)=5`), p(text("find "), math("y"), text(" in terms of "), math("x"), text("."))], options: mo(T`y=\frac13x^3+x^{-2}-3x^{-1}+\frac{20}3`, T`y=x^3+\frac12x^{-2}-3x^{-1}+\frac{13}2`, T`y=x^3+x^{-2}-3x^{-1}+6`, T`y=x^3+x^{-2}-x^{-1}+4`, T`y=x^3+2x^{-2}-x^{-1}+3`, T`y=3x^3+x^{-2}-x^{-1}+2`), knowledge: "integration" },
    { prompt: [p(text("For")), d(T`f(x)=\left(\frac2x-\frac1{2x^2}\right)^2,\quad x\ne0`), p(text("find "), math(T`f''(1)`), text("."))], options: mo("-3", "-1", "5", "17", "29", "80"), knowledge: "differentiation" },
    { prompt: [p(text("Line "), math(T`y=6-2x`), text(" and its perpendicular through "), math(T`(-6,0)`), text(" enclose a region with the "), math("x"), text("-axis. Find its area."))], options: mo(T`16\frac25`, "18", T`21\frac32`, T`27\frac15`, T`40\frac12`), knowledge: "coordinate-geometry" },
    { prompt: [p(text("When "), math(T`3x^2+8x-3`), text(" is multiplied by "), math(T`px-1`), text(" and divided by "), math(T`x+1`), text(" the remainder is 24. Find "), math("p"), text("."))], options: mo("-4", "2", "4", "8", T`\frac74`) },
    { prompt: [p(text("Let "), math("S"), text(" satisfy both "), math(T`x^2-8x+12<0`), text(" and "), math(T`2x+1>9`), text(". Which single inequality represents "), math("S"), text("?"))], options: mo(T`(x^2-8x+12)(2x+1)<0`, T`(x^2-8x+12)(2x+1)>0`, T`x^2-10x+24<0`, T`x^2-10x+24>0`, T`x^2-6x+8<0`, T`x^2-6x+8>0`, T`x<2`, T`x>6`) },
    { prompt: [p(text("A tangent to "), math(T`x^2+y^2=144`), text(" passes through "), math(T`(20,0)`), text(" and crosses the positive "), math("y"), text("-axis. Find that intercept."))], options: mo("12", "15", T`\frac{49}3`, "20", T`\frac{64}3`, T`\frac{80}3`), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("An AP begins "), math(T`p,q,p^2`), text(" with "), math("p<0"), text(". A GP begins "), math(T`p,p^2,q`), text(". Find the AP's first-ten sum."))], options: mo(T`\frac{23}8`, T`\frac{95}8`, T`\frac{115}8`, T`\frac{185}8`), knowledge: "sequences-and-series" },
    { prompt: [p(text("For "), math(T`0\le x\le\pi`), text(", solve")), d(T`(1-2\sin x)\cos x\ge0`)], options: mo(T`0\le x\le\frac\pi6\text{ or }\frac\pi2\le x\le\frac{5\pi}6`, T`0\le x\le\frac\pi6\text{ or }\frac{5\pi}6\le x\le\pi`, T`\frac\pi6\le x\le\frac\pi2\text{ or }\frac{5\pi}6\le x\le\pi`, T`\frac\pi6\le x\le\frac{5\pi}6`), knowledge: "trigonometry" },
    { prompt: [p(text("A regular hexagon is inscribed in "), math(T`x^2+y^2-18x-22y+178=0`), text(". Find its area."))], options: mo("6", T`6\sqrt3`, "18", T`18\sqrt3`, "36", T`36\sqrt3`, "48", T`48\sqrt3`), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("For")), d(T`f(x)=p^3-6p^2x+3px^2-x^3`), p(text("the normal gradient at "), math(T`x=-1`), text(" is "), math("M"), text(". Find the greatest possible "), math("M"), text(" as real "), math("p"), text(" varies."))], options: mo(T`-\frac32`, T`-\frac23`, T`-\frac12`, T`\frac14`, T`\frac23`, T`\frac32`), knowledge: "differentiation" },
    { prompt: [p(text("Define")), d(T`x_1=7,\qquad x_{n+1}=\frac{23x_n-53}{5x_n+1}`), p(text("The first three terms are 7, 3, 1. Find "), math(T`x_{100}`), text("."))], options: mo("-5", "0", "1", "3", "7"), knowledge: "sequences-and-series" },
    { prompt: [p(text("A polynomial "), math("f(x)>0"), text(" for every "), math("x"), text(" and "), math(T`\int_2^4f(x)\,dx=A`), text(". Which identity must hold?"))], options: mo(T`\int_0^2[f(x+2)+1]dx=A+1`, T`\int_0^2[f(x+2)+1]dx=A+2`, T`\int_2^4[f(x+2)+1]dx=A+1`, T`\int_2^4[f(x+2)+1]dx=A+2`, T`\int_4^6[f(x+2)+1]dx=A+1`, T`\int_4^6[f(x+2)+1]dx=A+2`), knowledge: "integration" },
    { prompt: [p(text("In "), math(T`(a+bx)^6`), text(" the "), math(T`x^4`), text(" coefficient is eight times the "), math(T`x^2`), text(" coefficient. For positive integer non-zero "), math("a,b"), text(", minimise "), math(T`a+b`), text("."))], options: mo("3", "4", "5", "9", "13", "17"), knowledge: "binomial-expansion" },
    { prompt: [p(text("Solve")), d(T`2^x+3\cdot2^y=3,\qquad2^{2x}-9\cdot2^{2y}=6`), p(text("If "), math(T`x=p,y=q`), text(", find "), math(T`p-q`), text("."))], options: mo(T`\frac5{12}`, T`\frac73`, T`\log_2\frac5{12}`, T`\log_2\frac73`, T`\log_2 9`, T`\log_2 15`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Let "), math(T`f(x)=-2x^2+10`), text(". The trapezium rule estimates area on "), math(T`0\le x\le1`), text(" under (1) "), math(T`f(x)`), text(", (2) "), math(T`f(x+1)`), text(", and (3) the latter reflected in "), math(T`y=6`), text(". Classify each."))], options: to("under, under, under", "under, under, over", "under, over, under", "under, over, over", "over, under, under", "over, under, over", "over, over, under", "over, over, over"), knowledge: "integration" },
    { prompt: [p(text("For "), math(T`f=3x^2+12x+4`), text(" and "), math(T`g=x^3+6x^2+9x-8`), text(", find "), math("x"), text(" where exactly one function is increasing."))], options: mo(T`x\ge-1`, T`x<-1`, T`-3\le x<-2\text{ or }x\ge-1`, T`x<-2\text{ or }x\ge-1`, T`x<-3\text{ or }-2<x<-1`, T`x<-3\text{ or }x\ge-2`, T`-2<x<-1`), knowledge: "differentiation" },
    { prompt: [p(text("For positive integer "), math("n"), text(" define")), d(T`F(n)=\frac1n\int_0^n(n-x)\,dx,\qquad G(n)=\sum_{r=1}^nF(r)`), p(text("Find the smallest "), math("n"), text(" with "), math(T`G(n)>150`), text("."))], options: mo("22", "23", "24", "25", "26"), knowledge: "integration" },
    { prompt: [p(text("Translate "), math(T`y=\log_{10}x`), text(" upward by 2. This equals a stretch of factor "), math("k"), text(" parallel to the "), math("x"), text("-axis. Find "), math("k"), text("."))], options: mo("0.01", T`\log_{10}2`, "0.5", "2", T`\log_2 10`, "100"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("The roots of "), math(T`x^2+bx+c<0`), text(" form "), math(T`p<x<q`), text(" with "), math("c<0"), text(". Find the solution interval of "), math(T`x^2+bcx+c^2<0`), text("."))], options: mo(T`p/c<x<q/c`, T`q/c<x<p/c`, T`pc<x<qc`, T`qc<x<pc`, T`pc^2<x<qc^2`, T`qc^2<x<pc^2`) },
    { prompt: [p(text("Triangle "), math("PQR"), text(" has side lengths "), math(T`QR=a,RP=a+d,PQ=a+2d`), text(" with "), math(T`a,d>0`), text(" and "), math(T`3d>2a`), text(". Find the full possible range of "), math(T`\angle PRQ`), text(" in degrees."))], options: to("0° < angle < 60°", "0° < angle < 120°", "60° < angle < 120°", "60° < angle < 180°", "120° < angle < 180°"), knowledge: "trigonometry" },
  ],
});
