import { T, d, defineHistoricPaper, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2019_P1 = defineHistoricPaper({
  id: "tmua-2019-p1", edition: "2019", paper: 1, answers: "AAECECFEDFHCBBACCBCE",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-1-2019.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2019.pdf",
  questions: [
    { prompt: [p(text("A quadratic "), math("f"), text(" passes through "), math(T`(1,-1)`), text(" and has turning point "), math(T`(-1,3)`), text(". Find "), math("f(x)"), text("."))], options: mo(T`-x^2-2x+2`, T`-x^2+2x+3`, T`x^2-2x`, T`x^2+2x-4`, T`2x^2+4x+1`, T`-2x^2-4x+5`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("Find all real "), math("k"), text(" for which "), math(T`x^2+(k+2)x+1-2k`), text(" is positive for every real "), math("x"), text("."))], options: mo(T`-12<k<0`, T`k<-12\text{ or }k>0`, T`-\sqrt6-3<k<\sqrt6-3`, T`k<-\sqrt6-3\text{ or }k>\sqrt6-3`, T`-2<k<12`, T`k<-2\text{ or }k>12`, T`0<k<4`, T`k<0\text{ or }k>4`) },
    { prompt: [p(text("Find the coefficient of "), math("x"), text(" in")), d(T`\sum_{r=0}^{80}(1+x)^r`)], options: mo("80", "81", "324", "628", "3240", "3321", "6480", "6642"), knowledge: "binomial-expansion" },
    { prompt: [p(text("The sequence is")), d(T`x_1=10,\qquad x_{n+1}=\sqrt{x_n}\ (n\ge1)`), p(text("Find "), math(T`x_{100}`), text(". Exponentiation is right-associative."))], options: mo(T`10^{2^{99}}`, T`10^{2^{100}}`, T`10^{2^{-99}}`, T`10^{2^{-100}}`, T`10^{-2^{99}}`, T`10^{-2^{100}}`, T`10^{-2^{-99}}`, T`10^{-2^{-100}}`), knowledge: "sequences-and-series" },
    { prompt: [p(text("A geometric sequence has sum of first six terms equal to nine times the sum of its first three terms. Its seventh term is 360. Find its first term."))], options: mo(T`\frac{40}{27}`, T`\frac{40}{9}`, T`\frac{40}{3}`, T`\frac{45}{16}`, T`\frac{45}{8}`, T`\frac{45}{4}`), knowledge: "sequences-and-series" },
    { prompt: [p(text("Circles "), math(T`(x+4)^2+(y+1)^2=64`), text(" and "), math(T`(x-8)^2+(y-4)^2=r^2`), text(" with "), math("r>0"), text(" are tangent. Find the difference between the two possible "), math("r"), text(" values."))], options: mo("4", "10", "16", "26", "50"), knowledge: "coordinate-geometry-circles" },
    { prompt: [p(text("For "), math(T`y=(2q-x^2)(2qx+3)`), text(", the gradient at "), math(T`x=-1`), text(" depends on "), math("q"), text(". Find the "), math("q"), text(" that minimises it."))], options: mo("-1", T`-\frac34`, T`-\frac12`, "0", T`\frac12`, T`\frac34`, "1"), knowledge: "differentiation" },
    { prompt: [p(text("For "), math(T`0<f(x)<1`), text(" on "), math(T`[0,1]`), text(", the trapezium rule with "), math("n"), text(" intervals underestimates "), math(T`\int_0^1f(x)\,dx`), text(". For which does it overestimate using the same "), math("n"), text("?"))], options: mo(T`\int_0^1(f(x)+1)\,dx`, T`\int_0^12f(x)\,dx`, T`\int_{-1}^0f(x+1)\,dx`, T`\int_{-1}^0f(-x)\,dx`, T`\int_0^1(1-f(x))\,dx`), knowledge: "integration" },
    { prompt: [p(text("For positive "), math("p"), text(", find the area enclosed by "), math(T`y=p\sqrt{x}`), text(" and "), math(T`x=p\sqrt{y}`), text("."))], options: mo(T`\frac23p^{5/2}-\frac12p^2`, T`\frac43p^{5/2}-p^2`, T`\frac{p^4}{6}`, T`\frac{p^4}{3}`, T`\frac23p^3-\frac12p^4`, T`\frac43p^3-p^4`, T`2p^4`), knowledge: "integration" },
    { prompt: [p(text("Evaluate")), d(T`\int_{-1}^{3}|x|(1-x)\,\mathrm dx`)], options: mo(T`\frac{17}3`, T`-\frac{17}3`, T`\frac{16}3`, T`-\frac{16}3`, T`\frac{11}3`, T`-\frac{11}3`), knowledge: "integration" },
    { prompt: [p(text("Find the sum of real "), math("x"), text(" values satisfying")), d(T`\log_3(xy^2)=1,\qquad(\log_3x)(\log_3y)=-3`)], options: mo(T`\frac13`, "1", "3", T`3\frac19`, T`9\frac1{27}`, T`9\frac13`, "27", T`27\frac19`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Given")), d(T`\frac{\mathrm dV}{\mathrm dt}=\frac{24\pi(t-1)}{1+\sqrt t}\quad(t\ge1),\qquad V(1)=7`), p(text("find "), math(T`V(9)`), text("."))], options: mo(T`208\pi+7`, T`216\pi+7`, T`224\pi+7`, T`416\pi+7`, T`608\pi+7`, T`744\pi+7`), knowledge: "integration" },
    { prompt: [p(text("Find the maximum, for real "), math("x"), text(", of")), d(T`4^{\sin x}-4\cdot2^{\sin x}+\frac{17}{4}`)], options: mo(T`\frac14`, T`\frac52`, T`\frac{13}2`, T`\frac{21}2`, T`\frac{65}4`, T`\text{no maximum}`), knowledge: "trigonometry" },
    { prompt: [p(text("For "), math(T`0^\circ\le x\le360^\circ`), text(", solve simultaneously")), d(T`\sin2x+\sqrt3\cos2x=-1`), d(T`\sqrt3\sin2x-\cos2x=\sqrt3`), p(text("and find the sum of possible "), math("x"), text("."))], options: mo(T`210^\circ`, T`330^\circ`, T`390^\circ`, T`660^\circ`, T`780^\circ`, T`930^\circ`), knowledge: "trigonometry" },
    { prompt: [p(text("Find the non-zero real solution of")), d(T`\frac{2^{9^x}}{8^{3^x}}=\frac14`)], options: mo(T`\log_3 2`, T`2\log_3 2`, "1", "2", T`\log_2 3`, T`2\log_2 3`), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("Given")), d(T`\frac12\int_0^1f(x)\,dx+5\int_1^2f(x)\,dx=14,\qquad\int_0^1f(x+1)\,dx=6`), p(text("find "), math(T`\int_0^2f(x)\,dx`), text("."))], options: mo("-8", "-4", "-2", "2", "4", T`\frac{29}5`, T`\frac{32}5`, "14"), knowledge: "integration" },
    { prompt: [p(text("Find the fraction of "), math(T`0\le\theta\le\pi`), text(" satisfying")), d(T`\left(\sin2\theta-\frac12\right)(\sin\theta-\cos\theta)\ge0`)], options: mo(T`\frac1{12}`, T`\frac16`, T`\frac14`, T`\frac5{12}`, T`\frac7{12}`, T`\frac34`, T`\frac56`, T`\frac{11}{12}`), knowledge: "trigonometry" },
    { prompt: [p(text("Find the shortest distance between "), math(T`y=x^2+4`), text(" and "), math(T`y=2x-2`), text("."))], options: mo("2", T`\sqrt5`, T`\frac{6\sqrt5}{5}`, "3", T`\frac{5\sqrt5}{3}`, "5", "6"), knowledge: "coordinate-geometry" },
    { prompt: [p(text("Find")), d(T`\sum_{k=0}^{90}\sin(10+90k)^\circ`)], options: mo("0", T`\sin10^\circ`, T`\sin100^\circ`, T`\sin190^\circ`, T`\sin280^\circ`, "1"), knowledge: "trigonometry" },
    { prompt: [p(text("Find all "), math("k"), text(" for which "), math(T`y=x^3-12x`), text(" and "), math(T`y=k-(x-2)^2`), text(" intersect at three distinct points, exactly two with positive "), math("x"), text("."))], options: mo(T`-4<k<0`, T`-4<k<4`, T`-4<k<16`, T`-16<k<0`, T`-16<k<4`, T`-16<k<16`), knowledge: "graphs-of-functions" },
  ],
});
