import { T, combos, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2019_P2 = defineHistoricPaper({
  id: "tmua-2019-p2", edition: "2019", paper: 2, answers: "ECADBDBEDAAFDBBFDEEB",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-2-2019.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2019.pdf",
  questions: [
    { prompt: [p(text("Find the coefficient of "), math(T`x^4`), text(" in")), d(T`x^2\left(2x+\frac1x\right)^6`)], options: mo("15", "30", "60", "120", "240"), knowledge: "binomial-expansion" },
    { prompt: [p(math(T`2x+1`), text(" and "), math(T`x-2`), text(" are factors of "), math(T`2x^3+px^2+q`), text(". Find "), math(T`2p+q`), text("."))], options: mo("-10", T`-\frac{38}5`, "-22", "22", T`\frac{38}5`, "10") },
    { prompt: [p(text("For real "), math("a,b,c"), text(" with "), math(T`ab=ac`), text(", which must hold?")), d(T`\mathrm I\ a=0\qquad\mathrm{II}\ b=0\text{ or }c=0\qquad\mathrm{III}\ b=c`)], options: combos, knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("Conjecture: a positive integer consisting of 1, then an odd number of zeros, then 1 is prime. Which examples counter it?")), d(T`\mathrm I\ 101\text{ (prime)}\qquad\mathrm{II}\ 1001=7\cdot11\cdot13\qquad\mathrm{III}\ 10001=73\cdot137`)], options: combos, knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("For positive integers "), math("a,b,n"), text(", let (*) mean "), math(T`n\mid ab`), text(". The condition “"), math(T`n\mid a`), text(" or "), math(T`n\mid b`), text("” is …"))], options: to("necessary but not sufficient", "sufficient but not necessary", "necessary and sufficient", "neither necessary nor sufficient"), knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("A student solves "), math(T`\cos x+\sin x\tan x=2\sin x-1`), text(" on "), math(T`[0,2\pi]`), text(". They factor to "), math(T`(\sin x-\cos x)(\tan x-1)=-1`), text(" in line II, then assert in line III that one factor equals −1. Where is the first error?"))], options: to("Completely correct", "Line I", "Line II", "Line III", "Extra solutions introduced in IV", "Extra solutions introduced in V", "Failure to exclude undefined tangent in VI"), knowledge: "errors-in-proof", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("For which statement does "), math(T`12^2+16^2=20^2`), text(" produce a counterexample?"))], options: to("Every primitive Pythagorean triple has two odd terms and one even term.", "a⁴ + b² = c² has no positive-integer solutions.", "a⁴ + b⁴ = c⁴ has no positive-integer solutions.", "In every Pythagorean triple one term is the arithmetic mean of the other two."), knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("Real "), math(T`a<b<c<0`), text(". Which must hold?")), d(T`\mathrm I\ ac<ab<a^2\qquad\mathrm{II}\ b(c+a)>0\qquad\mathrm{III}\ \frac cb>\frac ab`)], options: combos, skills: ["condition-checking", "counterexample-construction"] },
    { prompt: [p(text("A circular table has 40 chairs. What is the fewest people already seated such that the next person must sit beside someone?"))], options: mo("9", "10", "13", "14", "19", "20"), knowledge: "mathematical-logic" },
    { prompt: [p(text("For quadrilateral "), math("PQRS"), text(" labelled anticlockwise, which is necessary but not sufficient for being a parallelogram?"))], options: to("PQ = SR and PS ∥ QR", "PQ = SR and PQ ∥ SR", "PQ = QR = SR = PS", "PR = QS"), knowledge: "coordinate-geometry", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("An integer arithmetic series has "), math("n"), text(" terms and sum 20. Which must be true?")), d(T`\mathrm I\ \text{first term even}\qquad\mathrm{II}\ n\text{ even}\qquad\mathrm{III}\ \text{common difference even}`)], options: combos, knowledge: "sequences-and-series", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("Most students in a large college study Mathematics. Three distinct students are selected without replacement. Let "), math("R"), text(" be the probability at least one studies Mathematics, "), math("S"), text(" the probability the second does, and "), math("T"), text(" the probability all three do. Order them."))], options: mo(T`R<S<T`, T`R<T<S`, T`S<R<T`, T`S<T<R`, T`T<R<S`, T`T<S<R`), knowledge: "gcse-supporting-knowledge" },
    { prompt: [p(text("A four-strip trapezium estimate of "), math(T`\int_a^b\sin^2x\,dx`), text(" is an overestimate. Which must follow?")), p(text("I — The same method over "), math(T`[-b,-a]`), text(" also overestimates "), math(T`\int_{-b}^{-a}\sin^2x\,dx`), text(".")), p(text("II — It underestimates "), math(T`\int_a^b\cos^2x\,dx`), text("."))], options: to("neither", "I only", "II only", "I and II"), knowledge: "integration", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("For a polynomial "), math("p"), text(" and "), math(T`a<b`), text(", which are necessary for "), math("p"), text(" to be increasing on "), math(T`[a,b]`), text("?")), d(T`\mathrm I\ p(a)\le p(b)\qquad\mathrm{II}\ p'(a)\le p'(b)\qquad\mathrm{III}\ p''(a)\le p''(b)`)], options: combos, knowledge: "differentiation", skills: ["necessary-sufficient-reasoning", "counterexample-construction"] },
    { prompt: [p(text("For "), math(T`a,b,c>1`), text(", logarithms to one base satisfy")), d(T`\log(ab^2c)=7,\qquad\log(a^2bc^2)=11,\qquad\log(a^2b^2c^3)=15`), p(text("What is the base?"))], options: to("a", "b", "c", "determinable but not a, b or c", "insufficient information"), knowledge: "exponentials-and-logarithms" },
    { prompt: [p(text("For "), math(T`p>0`), text(", "), math(T`y=px^2+qx+p`), text(" crosses the "), math("x"), text("-axis twice. Which shaded "), math("(p,q)"), text(" region is complete?")), fig("/questions/tmua-2019-p2/q16.svg", "Eight candidate shaded regions bounded by q equals plus or minus 2p in the right half-plane.")], options: to("Graph A", "Graph B", "Graph C", "Graph D", "Graph E", "Graph F", "Graph G", "Graph H"), knowledge: "graphs-of-functions", skills: ["diagram-interpretation", "condition-checking"] },
    { prompt: [p(text("Four options about a statement are: A iff "), math("x>1"), text("; B if "), math("x>1"), text("; C iff "), math("x>2"), text("; D if "), math("x>2"), text(". Exactly one is correct. Which?"))], options: to("A", "B", "C", "D"), knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("Find all real "), math("a"), text(" such that")), d(T`a|x|+1\le|x-2|`), p(text("holds for every real "), math("x"), text("."))], options: mo(T`a\le\frac32`, T`a\le1`, T`a\le\frac12`, T`a\le0`, T`a\le-\frac12`, T`a\le-1`, T`a\le-\frac32`, T`\text{none}`), skills: ["condition-checking", "counterexample-construction"] },
    { prompt: [p(text("Evaluate")), d(T`\sqrt{8-4\sqrt2+1}+\sqrt{9-12\sqrt2+8}`)], options: mo(T`\sqrt{26-16\sqrt2}`, T`4\sqrt2-4`, "-2", T`4-4\sqrt2`, "2", T`\sqrt{26}-4\sqrt2`, "1") },
    { prompt: [p(text("Reflect "), math(T`y=f(x)`), text(" in the "), math("y"), text("-axis then translate 2 left to obtain "), math("g"), text(". Translate "), math("f"), text(" 2 left then reflect to obtain "), math("h"), text(". Which condition is necessary and sufficient for "), math(T`g=h`), text("?"))], options: mo(T`f(x)=f(x+2)`, T`f(x)=f(x+4)`, T`f(x)=f(x+8)`, T`f(x)=f(-x)`, T`f(x)=f(2-x)`, T`f(x)=f(4-x)`, T`f(x)=f(8-x)`), knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "representation-switching"] },
  ],
});
