import { T, combos, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2020_P2 = defineHistoricPaper({
  id: "tmua-2020-p2", edition: "2020", paper: 2, answers: "EFCGAAHEFFGDDADDEGEC",
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-2-2020.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2020.pdf",
  questions: [
    { prompt: [p(text("Find all "), math("k"), text(" for which "), math(T`y=x-2`), text(" crosses or touches "), math(T`y=x^2+kx+2`), text("."))], options: mo(T`-1\le k\le3`, T`-3\le k\le5`, T`-4\le k\le4`, T`k\le-1\text{ or }k\ge3`, T`k\le-3\text{ or }k\ge5`, T`k\le-4\text{ or }k\ge4`), knowledge: "graphs-of-functions" },
    { prompt: [p(text("Given "), math(T`\tan\theta=2`), text(" and "), math(T`180^\circ<\theta<360^\circ`), text(", find "), math(T`\cos\theta`), text("."))], options: mo(T`\sqrt3`, T`-\sqrt3`, T`\frac{\sqrt3}{2}`, T`-\frac{\sqrt3}{2}`, T`\frac{\sqrt5}{5}`, T`-\frac{\sqrt5}{5}`, T`\frac{2\sqrt5}{5}`, T`-\frac{2\sqrt5}{5}`), knowledge: "trigonometry" },
    { prompt: [p(text("A student claims that for every integer "), math("n"), text(",")), d(T`4\left(\frac{9n+1}{2}-\frac{3n-1}{2}\right)`), p(text("is divisible by 3. Their argument rewrites 4 as "), math(T`2(2)`), text(" in line I, then changes the inner "), math("2"), text(" times the bracket to "), math(T`2(9n+1-3n-1)`), text(" in line II, and concludes "), math(T`12n=3(4n)`), text(". Where is the first error?"))], options: to("The argument is correct.", "Line I", "Line II", "Line III", "Line IV", "Line V", "Line VI"), knowledge: "errors-in-proof", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("Claim: every positive integer "), math("N>6"), text(" is a sum of two non-prime integers greater than 1. Which are counterexamples?")), d(T`\mathrm I\ N=5\qquad\mathrm{II}\ N=7\qquad\mathrm{III}\ N=9`)], options: combos, knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("Which sketch shows")), d(T`y=\frac{2^x}{1+2^x}`), p(text("Dotted lines are asymptotes.")), fig("/questions/tmua-2020-p2/q05.svg", "Six sketches A–F: increasing or decreasing curves, with different horizontal asymptotes.")], options: to("Sketch A", "Sketch B", "Sketch C", "Sketch D", "Sketch E", "Sketch F"), knowledge: "graphs-of-functions", skills: ["diagram-interpretation", "representation-switching"] },
    { prompt: [p(text("Which conditions are necessary to ensure")), d(T`\int_{-5}^{0}f(x)\,\mathrm dx=\int_0^5f(x)\,\mathrm dx?`), p(text("I — "), math(T`f(x)=f(-x)`), text(" on "), math(T`[-5,5]`), text(".")), p(text("II — "), math(T`f(x)=c`), text(" on "), math(T`[-5,5]`), text(".")), p(text("III — "), math(T`f(x)=-f(-x)`), text(" on "), math(T`[-5,5]`), text("."))], options: combos, knowledge: "integration", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("For parallelogram "), math("PQRS"), text(", which conditions are individually sufficient for it to be a square?")), p(text("I — "), math(T`PQ=QR`), text(".")), p(text("II — Diagonals "), math("PR"), text(" and "), math("QS"), text(" meet at right angles.")), p(text("III — "), math(T`\angle PQR=\angle QRS`), text("."))], options: to("I yes; II yes; III yes", "I yes; II yes; III no", "I yes; II no; III yes", "I yes; II no; III no", "I no; II yes; III yes", "I no; II yes; III no", "I no; II no; III yes", "I no; II no; III no"), knowledge: "coordinate-geometry", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A student disproves "), math(T`|a+b|<|a|+|b|`), text(" for all real "), math("a,b"), text(" using "), math(T`a=3,b=4`), text(". Which best describes the proof?"))], options: to("The statement is true and the proof is wrong.", "The statement is false but the counterexample is invalid.", "The student must list every failing pair.", "The student should instead state the non-strict triangle inequality.", "The statement is false and the proof is fully correct."), knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("A calculator works in degrees only. What input correctly evaluates "), math(T`f(4)`), text(" for "), math(T`f(x)=x\sin x`), text(" with "), math("x"), text(" in radians?"))], options: mo(T`(\pi4/180)\sin4`, T`(\pi4/180)\sin(\pi4/180)`, T`4\sin(\pi4/180)`, T`(180\cdot4/\pi)\sin4`, T`(180\cdot4/\pi)\sin(180\cdot4/\pi)`, T`4\sin(180\cdot4/\pi)`), knowledge: "trigonometry" },
    { prompt: [p(text("Real "), math("a,b,c,d"), text(" satisfy")), d(T`0<a+b<c+d,\qquad0<a+c<b+d`), p(text("Which must be true?")), d(T`\mathrm I\ a<d\qquad\mathrm{II}\ b<c\qquad\mathrm{III}\ a+b+c+d>0`)], options: combos, skills: ["condition-checking", "counterexample-construction"] },
    { prompt: [fig("/questions/tmua-2020-p2/q11.svg", "A square spiral beginning at the origin, turning at coordinates (−2,0), (−2,−2), (2,−2), (2,2), (−4,2), (−4,−4), (4,−4), (4,4), and continuing."), p(text("The square spiral continues indefinitely. Which point is not on it?"))], options: mo(T`(99,100)`, T`(99,-100)`, T`(-99,100)`, T`(-99,-100)`, T`(100,99)`, T`(100,-99)`, T`(-100,99)`, T`(-100,-99)`), knowledge: "coordinate-geometry", skills: ["diagram-interpretation", "condition-checking"] },
    { prompt: [p(text("Given "), math(T`a<b`), text(" and "), math(T`f(x)>0`), text(" on "), math(T`(a,b)`), text(", the trapezium rule overestimates "), math(T`\int_a^bf(x)\,\mathrm dx`), text(" …"))], options: mo(T`\text{if }f'>0\text{ and }f''<0`, T`\text{only if }f'>0\text{ and }f''<0`, T`\text{iff }f'>0\text{ and }f''<0`, T`\text{if }f'<0\text{ and }f''>0`, T`\text{only if }f'<0\text{ and }f''>0`, T`\text{iff }f'<0\text{ and }f''>0`), knowledge: "integration", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A function "), math("f"), text(" satisfies")), d(T`\int_0^3(f(x))^2\,\mathrm dx+\int_0^3f(x)\,\mathrm dx=\int_0^1f(x)\,\mathrm dx`), p(text("Which must be true?")), p(text("I — "), math(T`f(x)\le0`), text(" for some "), math(T`1\le x\le3`), text(".")), p(text("II — "), math(T`\int_0^3f(x)\,\mathrm dx\le\int_0^1f(x)\,\mathrm dx`), text("."))], options: to("neither", "I only", "II only", "I and II"), knowledge: "integration", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("An arithmetic sequence has non-zero integer first term "), math("a"), text(" and difference "), math("d"), text(". Property P means that for some positive integer "), math("m"), text(", the sum of the first "), math("m"), text(" terms equals the sum of the first "), math("2m"), text(" terms. Which are true?")), p(text("I — "), math(T`ad<0`), text(" is sufficient for P.")), p(text("II — even "), math("d"), text(" is necessary for P."))], options: to("neither", "I only", "II only", "I and II"), knowledge: "sequences-and-series", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("Which condition is necessary and sufficient for")), d(T`\sum_{k=1}^{n}\sin\left(\frac{k\pi}{3}\right)=\frac{\sqrt3}{2}?`)], options: to("n = 1", "n is a multiple of 3", "n is a multiple of 6", "n is 1 more than a multiple of 3", "n is 1 more than a multiple of 6", "n is 1 or 2 more than a multiple of 6"), knowledge: "trigonometry", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A student uses the FTC to calculate")), d(T`\frac{\mathrm d}{\mathrm dx}\int_x^{2x}t^2\,\mathrm dt`), p(text("I — Split it as "), math(T`\int_0^{2x}t^2\,dt-\int_0^xt^2\,dt`), text(".")), p(text("II — The derivative of the second integral is "), math(T`x^2`), text(".")), p(text("III — The derivative of the first is written as "), math(T`(2x)^2=4x^2`), text(".")), p(text("IV–V — Conclude "), math(T`3x^2`), text(". Where is the first error?"))], options: to("Completely correct", "Line I", "Line II", "Line III", "Line IV", "Line V"), knowledge: "integration", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("Six distinct integers are split into triples. The first has mean 10 and median 8; the second has mean 12 and median 9. Find the smallest possible range of all six."))], options: mo("8", "10", "11", "12", "14", "15") },
    { prompt: [p(text("Let "), math(T`f=ax^3+bx^2+cx+d`), text(" and "), math(T`g=px^3+qx^2+rx+s`), text(". If "), math(T`f(x)-g(x)>0`), text(" for every real "), math("x"), text(", which must hold?")), d(T`\mathrm I\ a>p\qquad\mathrm{II}\ b=q\Rightarrow c=r\qquad\mathrm{III}\ d>s`)], options: combos, knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("Nine people occupy a 3×3 grid. Side-sharing occupants are neighbours. Each is a truth-teller or liar and says, “My neighbours are all liars.” Find the smallest and largest possible numbers of truth-tellers."))], options: to("1 and 4", "2 and 4", "2 and 5", "3 and 4", "3 and 5", "4 and 4", "4 and 5", "5 and 5"), knowledge: "mathematical-logic", skills: ["condition-checking", "multi-step-planning"] },
    { prompt: [p(text("Exactly one statement below about real "), math("x"), text(" and function "), math("f"), text(" is true. Which?"))], options: to("x ≥ 0 only if f(x) < 0", "x < 0 if f(x) ≥ 0", "x ≥ 0 only if f(x) ≥ 0", "f(x) < 0 if x < 0", "f(x) ≥ 0 only if x ≥ 0", "f(x) ≥ 0 iff x < 0"), knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
  ],
});
