import { T, combos, d, defineHistoricPaper, math, mo, p, text, to } from "./historic-paper-helpers.js";

export const TMUA_2017_P2 = defineHistoricPaper({
  id: "tmua-2017-p2", edition: "2017", paper: 2, answers: "AEGBBAEEDDBC BFD CFBEB".replaceAll(" ", ""),
  sourceQuestionPath: "Tmua/2016-2023paper/tmua-paper-2-2017.pdf", sourceAnswerPath: "Tmua/2016-2023 answer key/tmua-2017.pdf",
  questions: [
    { prompt: [p(text("Given")), d(T`y=\frac{(1-3x)^2}{2x^{3/2}}`), p(text("find "), math(T`\frac{dy}{dx}`), text("."))], options: mo(T`\frac94x^{-1/2}+\frac32x^{-3/2}-\frac34x^{-5/2}`, T`\frac94x^{-1/2}-\frac32x^{-3/2}+\frac34x^{-5/2}`, T`\frac94x^{-1/2}-\frac32x^{-3/2}-\frac34x^{-5/2}`, T`-\frac94x^{-1/2}+\frac32x^{-3/2}+\frac34x^{-5/2}`, T`-\frac94x^{-1/2}+\frac32x^{-3/2}-\frac34x^{-5/2}`, T`-\frac94x^{-1/2}-\frac32x^{-3/2}-\frac34x^{-5/2}`), knowledge: "differentiation" },
    { prompt: [p(text("Rectangle "), math("PQRS"), text(" has "), math(T`P=(0,6),Q=(1,8)`), text(". The perpendicular to "), math("PQ"), text(" at "), math("Q"), text(" meets the "), math("x"), text("-axis at "), math("R"), text(". Find its area."))], options: mo(T`\frac52`, T`4\sqrt{10}`, "20", T`8\sqrt{10}`, "40"), knowledge: "coordinate-geometry" },
    { prompt: [p(text("A GP has first term "), math(T`2\sqrt3`), text(" and fourth term "), math(T`\frac94`), text(". Find its sum to infinity."))], options: mo(T`-2(2-\sqrt3)`, T`4(2\sqrt3-3)`, T`\frac{16(8\sqrt3+9)}{37}`, T`\frac{4(2\sqrt3-3)}7`, T`\frac{4(2\sqrt3+3)}7`, T`2(2+\sqrt3)`, T`4(2\sqrt3+3)`), knowledge: "sequences-and-series" },
    { prompt: [p(text("A student uses "), math(T`\tan x=\sqrt3`), text(" to take "), math(T`x=60^\circ`), text(" and concludes "), math(T`\sin2x=\frac{\sqrt3}{2}`), text(". Which comment is correct?"))], options: to("Only value; reasoning complete", "Only value; should consider other x with tan x = √3", "Only value; should consider other x with same sine", "Not the only value; should consider other x with tan x = √3", "Not the only value; should consider other x with same sine"), knowledge: "trigonometry", skills: ["error-detection", "condition-checking"] },
    { prompt: [p(text("Which claims does "), math(T`91=7\cdot13`), text(" counter?")), p(text("I — "), math(T`10p^2+1`), text(" and "), math(T`10p^2-1`), text(" are prime for every odd prime "), math("p"), text(".")), p(text("II — Every prime greater than 5 is "), math(T`6n+1`), text(".")), p(text("III — No multiple of 7 greater than 7 is prime."))], options: combos, knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("Define "), math(T`u_0=1`), text(" and")), d(T`u_n=\int_0^1 4x u_{n-1}\,dx\quad(n\ge1)`), p(text("find "), math(T`u_{1000}`), text("."))], options: mo(T`2^{1000}`, T`4^{1000}`, T`\frac4{1000!}`, T`\frac4{1001!}`, T`\frac{2^{1000}}{1000!}`, T`\frac{4^{1000}}{1000!}`, T`\frac{2^{1000}}{1001!}`, T`\frac{4^{1000}}{1001!}`), knowledge: "sequences-and-series" },
    { prompt: [p(text("A solid curve is "), math(T`y=a^x`), text(" with "), math("a>0"), text("; a dashed exponential has the same intercept and is steeper. Which could describe it?")), p(text("I — "), math(T`b^x,b>a`), text(". II — "), math(T`b^x,b<a`), text(". III — "), math(T`a^{kx},k>1`), text(". IV — "), math(T`a^{kx},k<1`), text("."))], options: to("I only", "II only", "III only", "IV only", "I and III", "I and IV", "II and III", "II and IV"), knowledge: "exponentials-and-logarithms", skills: ["diagram-interpretation", "representation-switching"] },
    { prompt: [p(text("Which number is smallest?"))], options: mo(T`\log_2 7`, T`(2^{-3}+2^{-2})^{-1}`, T`2^{\pi/3}`, T`\frac1{\sqrt[4]{2^{-1/3}}}`, T`4\sin^2\frac\pi4`) },
    { prompt: [p(text("An attempted proof of Fermat's "), math("n=3"), text(" case factors "), math(T`a^3=(c-b)(c^2+cb+b^2)`), text(" correctly, then in line III concludes "), math(T`a=c-b`), text(" and "), math(T`a^2=c^2+cb+b^2`), text(" from inequalities. Where is the first mistake?"))], options: to("Correct", "I", "II", "III", "IV", "V", "VI"), knowledge: "errors-in-proof", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("Which condition is sufficient for")), d(T`\int_1^3f(x)\,dx=0?`)], options: mo(T`f(2)=0`, T`f(1)=f(3)=0`, T`f(-x)=-f(x)\ \forall x`, T`f(x+2)=-f(2-x)\ \forall x`, T`f(x-2)=-f(2-x)\ \forall x`), knowledge: "integration", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("An increasing "), math("f"), text(" has "), math(T`f(0)=0`), text(". Area under "), math("f"), text(" from "), math("a"), text(" to "), math("b"), text(" is "), math("R"), text(". For "), math(T`g(x)=f(x)+2f(b)`), text(", find the corresponding area."))], options: mo(T`R+(b-a)f(b)`, T`R+2(b-a)f(b)`, T`R+2f(b)-f(a)`, T`R+2f(b)`, T`R+f(b)^2`, T`R+f(b)^2-f(a)^2`, T`R+2(f(b)-f(a))f(b)`), knowledge: "integration" },
    { prompt: [p(text("For "), math(T`-\pi/2<x<\pi/2`), text(", which ordering is impossible?"))], options: mo(T`\cos2x<\sin2x<\tan x`, T`\cos2x<\tan x<\sin2x`, T`\sin2x<\cos2x<\tan x`, T`\sin2x<\tan x<\cos2x`, T`\tan x<\sin2x<\cos2x`, T`\tan x<\cos2x<\sin2x`), knowledge: "trigonometry" },
    { prompt: [p(text("Positive "), math(T`a10^{-3},b10^{-2},c10^{-1}`), text(" are in standard form and")), d(T`a10^{-3}+b10^{-2}=c10^{-1}`), p(text("which must hold? "), math(T`\mathrm I\ a>9`), text(", "), math(T`\mathrm{II}\ b>9`), text(", "), math(T`\mathrm{III}\ a<c`), text(", "), math(T`\mathrm{IV}\ b<c`), text("."))], options: to("I only", "II only", "I and II", "I and III", "I and IV", "II and III", "II and IV", "all four") },
    { prompt: [p(text("The graph "), math(T`y=x^2-2bx+c`), text(" has vertex "), math("P"), text(". Which relative vertex position can "), math(T`y=x^2-2Bx+c`), text(" have when "), math("B>b"), text("?"))], options: to("left and higher", "left and same height", "left and lower", "right and higher", "right and same height", "right and lower"), knowledge: "graphs-of-functions", skills: ["diagram-interpretation", "representation-switching"] },
    { prompt: [p(text("Define on positive integers: "), math(T`f(1)=5`), text(", then "), math(T`f(n+1)=3f(n)+1`), text(" if odd and "), math(T`f(n)/2`), text(" if even; "), math(T`g(1)=3`), text(", then "), math(T`g(n+1)=g(n)+5`), text(" if odd and "), math(T`g(n)/2`), text(" if even. Find "), math(T`f(1000)-g(1000)`), text("."))], options: mo("-6", "-5", "1", "2", "4", "8"), knowledge: "sequences-and-series" },
    { prompt: [p(text("Which counters: if "), math("f(x)"), text(" is integer for every integer "), math("x"), text(", then "), math(T`f'(x)`), text(" is integer for every integer "), math("x"), text("?"))], options: mo(T`\frac{x^3+x+1}{4}`, T`\frac{x^4+x^2+x}{2}`, T`\frac{x^4+x^3+x^2+x}{2}`, T`\frac{x^4+2x^3+x^2}{4}`), knowledge: "mathematical-proof", skills: ["counterexample-construction", "condition-checking"] },
    { prompt: [p(text("A set is stapled iff every member "), math("a"), text(" has a prime factor dividing another member. Which is equivalent to not stapled?"))], options: to("For every a, no prime factor divides every other member.", "For every a, no prime factor divides another member.", "For every a, some prime factor divides no other member.", "For every a, some prime factor fails to divide at least one other.", "There exists a with no prime factor dividing every other.", "There exists a with no prime factor dividing another member.", "There exists a with some prime factor dividing no other.", "There exists a with some prime factor failing to divide at least one other."), knowledge: "mathematical-logic", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A student solves")), d(T`\left(\frac14\right)^n<\left(\frac1{32}\right)^{10}`), p(text("by applying "), math(T`\log_{1/2}`), text(" but keeps the inequality direction in step II, obtaining "), math(T`1\le n\le24`), text(". Which step is invalid?"))], options: to("none", "I", "II", "III", "IV", "V"), knowledge: "exponentials-and-logarithms", skills: ["error-detection", "proof-sequencing"] },
    { prompt: [p(text("Which is sufficient for "), math(T`x^3-3x^2+a=0`), text(" to have exactly one real root?"))], options: mo(T`a>0`, T`a\le0`, T`a\ge4`, T`a<4`, T`|a|>4`, T`|a|\le4`, T`a=\frac94`, T`|a|=\frac32`), knowledge: "graphs-of-functions", skills: ["necessary-sufficient-reasoning", "condition-checking"] },
    { prompt: [p(text("A five-letter password is a permutation of abcde. Guesses abcde, cdbea and eadbc each have zero letters in the correct position. With the best strategy, how many more attempts guarantee deduction?"))], options: to("none", "one", "two", "three", "more than three"), knowledge: "mathematical-logic" },
  ],
});
