import { T, combos, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

const sourceQuestionPath = "Tmua/2016-2023paper/tmua-paper-2-practice(2016).pdf";
const sourceAnswerPath = "Tmua/2016-2023 answer key/tmua-practice(2016).pdf";

export const TMUA_PRACTICE_2016_P2 = defineHistoricPaper({
  id: "tmua-practice-2016-p2", edition: "2016 Practice", paper: 2,
  answers: "ABDCCCCBDEDFEBDCHDFE", sourceQuestionPath, sourceAnswerPath,
  sourcePages: [3,3,4,4,5,6,7,8,9,10,11,12,13,14,14,15,16,17,18,19],
  questions: [
    { prompt: [p(text("Find the value of")), d(T`\int_1^2\left(x^2-\frac4{x^2}\right)^2\,dx`)], options: mo(T`\frac{43}{15}`,`3`,T`\frac{97}{15}`,T`\frac{103}{15}`,T`\frac{163}{15}`,`18`) },
    { prompt: [p(text("For "), math("x>0"), text(",")), d(T`f(x)=\frac{(x^2+5)(2x)}{\sqrt[4]{x^3}}`), p(text("which expression equals "), math("f'(x)"), text("?"))], options: mo(T`8x^{9/4}+\frac{40}{3}x^{1/4}`,T`\frac92x^{5/4}+\frac52x^{-3/4}`,T`8x^{9/4}+\frac{40}{3}x^{-1/4}`,T`\frac8{13}x^{13/4}+8x^{5/4}`) },
    { prompt: [p(text("Find the largest "), math("x"), text(" in "), math(T`0\le x\le2\pi`), text(" satisfying "), math(T`8\sin^2x+4\cos^2x=7`), text("."))], options: mo(T`\frac{2\pi}3`,T`\frac{5\pi}6`,T`\frac{4\pi}3`,T`\frac{5\pi}3`,T`\frac{7\pi}4`,T`\frac{11\pi}6`) },
    { prompt: [p(text("Five urns contain the same non-zero number of balls. Their labels say: P: one or four; Q: two or four; R: more than two and fewer than five; S: one or two; T: fewer than three. Exactly one statement is true. Which urn is it?"))], options: to("Urn P","Urn Q","Urn R","Urn S","Urn T") },
    { prompt: [p(text("Consider: ‘A whole number "), math("n"), text(" is prime if it is 1 less or 5 less than a multiple of 6.’ How many counterexamples are there for "), math("0<n<50"), text("?"))], options: mo("2","3","4","5","6") },
    { prompt: [p(text("The functions satisfy")), d(T`f_1(x)=x^{10},\qquad f_{n+1}(x)=xf'_n(x)\quad(n\ge1)`), p(text("Find "), math(T`\sum_{n=1}^{20}f_n(x)`), text("."))], options: mo(T`\frac{x^{10}(x^{20}-1)}{x-1}`,T`\frac{x^{10}(x^{21}-1)}{x-1}`,T`\frac{10^{20}-1}{9}x^{10}`,T`\frac{10^{21}-1}{9}x^{10}`,T`\frac{(10x)^{20}-1}{10x-1}x^{10}`,T`\frac{(10x)^{21}-1}{10x-1}x^{10}`,T`x^{10}+x^9+\cdots+x+1`,T`x^{10}+10x^9+(10\cdot9)x^8+\cdots+10!`) },
    { prompt: [p(text("Real numbers "), math("a,b,c,d>1"), text(" satisfy "), math(T`\log_c d=(\log_a b)^2`), text(". Put "), math(T`x=\log_a b,\ y=\log_a c`), text(" and prove "), math(T`\log_b d=(\log_a b)(\log_a c)`), text(" using the numbered transformations:")), d(T`(2)\ d=(c^x)^2\quad (3)\ d=c^{x^2}\quad (4)\ d=b^{xy}`), d(T`(5)\ d=(a^y)^{x^2}\quad (6)\ d=((a^y)^x)^2\quad (7)\ d=(a^x)^{xy}`), d(T`(8)\ d=a^{y^2x}\quad (9)\ d=a^{x^2y}`)], options: to("2, 6, 8, 7, 4","2, 7, 8, 6, 4","3, 5, 9, 7, 4","3, 7, 9, 5, 4","4, 5, 9, 7, 3","4, 6, 8, 7, 2","4, 7, 8, 6, 2","4, 7, 9, 5, 3") },
    { prompt: [p(text("A region is defined by "), math(T`x+y>6`), text(" and "), math(T`x-y>-4`), text(". Which statements hold for every point?")), d(T`\text{I }x>1\qquad\text{II }y>5\qquad\text{III }(x+y)(x-y)>-24`)], options: combos },
    { prompt: [p(text("Triangles "), math("ABC"), text(" and "), math("XYZ"), text(" have equal area. Which independent conditions imply congruence?")), d(T`\text{I }AB=XY,\ BC=YZ`), d(T`\text{II }AB=XY,\ \angle ABC=\angle XYZ`), d(T`\text{III }\angle ABC=\angle XYZ,\ \angle BCA=\angle YZX`)], options: to("none","III only","II only","II and III only","I only","I and III only","I and II only","I, II and III") },
    { prompt: [p(text("Here "), math("x,y"), text(" are non-zero real numbers. Which condition is sufficient to conclude "), math("x<y"), text("?"))], options: mo(T`x^4<y^4`,T`y^4<x^4`,T`x^{1/4}<y^{1/4}`,T`y^{1/4}<x^{1/4}`,T`x^{3/5}<y^{3/5}`,T`y^{3/5}<x^{3/5}`) },
    { prompt: [p(text("A real polynomial "), math("f"), text(" has exactly two real roots "), math("-p,p"), text(" with "), math("p>0"), text(". Which statements must be true?")), d(T`\text{I }f'(x)=0\text{ exactly once on }(-p,p)`), d(T`\text{II area}=2\int_0^p f(x)\,dx`), d(T`\text{III }y=-f(-x)\text{ meets the }x\text{-axis only at }\pm p`)], options: combos },
    { prompt: [p(text("An arithmetic sequence has first term "), math("a"), text(", common difference "), math("d"), text(" and partial sums "), math("S_n"), text(". If "), math(T`S_8>3S_6`), text(", what follows about the signs of "), math("a,d"), text("?"))], options: to("both negative","a positive, d negative","a negative, d positive","a negative; d cannot be deduced","d negative; a cannot be deduced","neither sign can be deduced") },
    { prompt: [p(text("An attempted proof claims: if positive integer "), math("a"), text(" divides "), math("bc"), text(", then it divides "), math("b"), text(" or "), math("c"), text(". It writes "), math(T`b=ax+r,\ c=ay+s`), text(" with "), math(T`0<r,s<a`), text(", then "), math(T`bc=a(axy+xs+yr)+rs`), text(" and says the remainder on division by "), math("a"), text(" is "), math("rs"), text(". Which line is the error?"))], options: to("Line 1","Line 2","Line 3","Line 4","Line 5","Line 6") },
    { prompt: [p(text("For a quartic "), math(T`f(x)=ax^4+bx^3+cx^2+dx+e`), text(", the equations "), math(T`f(x)=1,2,3,4`), text(" have respectively "), math("p,q,r,s"), text(" distinct real solutions. Which tuple is impossible?"))], options: mo("(1,2,4,3)","(1,3,2,4)","(1,4,3,2)","(2,4,3,1)","(4,3,2,1)") },
    { prompt: [p(text("For "), math(T`f(x)=x^2-2px+q`), text(", which condition is equivalent to having two real roots whose difference is greater than 2 and less than 4?"))], options: mo(T`q<p^2<q+4`,T`\sqrt{q+1}<p<\sqrt{q+4}`,T`q-3<p^2-4<q`,T`q<p^2-1<q+3`,T`q-2<p^2-3<q+2`) },
    { prompt: [p(text("In trapezium "), math("PQRS"), text(", "), math("PQ\parallel SR"), text(", "), math("PQ=12"), text(" cm and "), math("SR=3"), text(" cm. Diagonals meet at "), math("X"), text(" and the line through "), math("X"), text(" parallel to the bases meets the sides at "), math("U,T"), text(". Find "), math("UT"), text("."))], options: mo("4.2","4.5","4.8","5.25","6") },
    { prompt: [p(text("Consider "), math(T`y=3\sin x+2`), text(" and "), math("y=x+c"), text(". Which statements are possible for some "), math("c"), text("?")), d(T`\text{I exactly one solution on }(0,\pi)\text{ and at least one on }(-\pi,0)`), d(T`\text{II exactly one on }(0,\pi)\text{ and none on }(-\pi,0)`), d(T`\text{III exactly one on }(0,\pi)\text{ and none for }x>\pi`)], options: combos },
    { prompt: [p(text("Which function is a counterexample to: if "), math(T`(f(x))^2<1`), text(" for "), math(T`-1<x<1`), text(", then "), math(T`\int_{-1/2}^{1/2}f(x)\,dx<\int_{-1}^1f(x)\,dx`), text("?"))], options: mo(T`x+\frac13`,T`x-\frac12`,T`x+x^3`,T`x-x^3`,T`x^2+x^4`,T`x^2-x^4`) },
    { prompt: [p(text("An object made from unit cubes has the following orthographic views.")), fig("/questions/tmua-practice-2016-p2/q19.svg","Side elevation, front elevation and plan view of a unit-cube object"), p(text("How many cubes were used?"))], options: to("exactly 6","either 6 or 7","exactly 7","either 7 or 8","exactly 8","either 8 or 9","exactly 9") },
    { prompt: [p(text("Each interior angle of a regular "), math("n"), text("-gon is "), math(T`\frac34`), text(" of each interior angle of a regular "), math("m"), text("-gon. How many positive-integer pairs "), math("(n,m)"), text(" satisfy this?"))], options: to("none","1","2","3","4","5","6","infinitely many") },
  ],
});
