import { T, d, defineHistoricPaper, fig, math, mo, p, text, to } from "./historic-paper-helpers.js";

const sourceQuestionPath = "Tmua/2016-2023paper/tmua-paper-1-practice(2016).pdf";
const sourceAnswerPath = "Tmua/2016-2023 answer key/tmua-practice(2016).pdf";

export const TMUA_PRACTICE_2016_P1 = defineHistoricPaper({
  id: "tmua-practice-2016-p1", edition: "2016 Practice", paper: 1,
  answers: "HECBCCBFDEEECDCCDABD", sourceQuestionPath, sourceAnswerPath,
  sourcePages: [3,3,4,4,5,5,6,6,7,7,8,9,10,10,11,11,12,12,13,14],
  questions: [
    { prompt: [p(text("It is given that the expansion of "), math(T`(ax+b)^3`), text(" is")), d(T`8x^3-px^2+18x-3\sqrt3`), p(text("where "), math("a,b,p"), text(" are real constants. What is the value of "), math("p"), text("?"))], options: mo(T`-12\sqrt3`,T`-6\sqrt3`,T`-4\sqrt3`,T`-\sqrt3`,T`\sqrt3`,T`4\sqrt3`,T`6\sqrt3`,T`12\sqrt3`) },
    { prompt: [p(text("The expression "), math(T`3x^3+13x^2+8x+a`), text(", where "), math("a"), text(" is a constant, has "), math("x+2"), text(" as a factor. Which is a complete factorisation?"))], options: mo(T`(x+2)(x-1)(3x-2)`,T`(x+2)(x+1)(3x-2)`,T`(x+2)(x+1)(3x+2)`,T`(x+2)(x-3)(3x+2)`,T`(x+2)(x+3)(3x-2)`,T`(x+2)(x+3)(3x+2)`) },
    { prompt: [p(text("A line is drawn normal to the curve "), math(T`y=\frac2{x^2}`), text(" at the point where "), math("x=1"), text(". It cuts the axes at "), math("P"), text(" and "), math("Q"), text(". The length of "), math("PQ"), text(" is"))], options: mo(T`\frac{3\sqrt5}{2}`,T`\frac{3\sqrt{17}}4`,T`\frac{7\sqrt{17}}4`,T`\frac{35}4`,T`\frac{35\sqrt5}2`,T`\frac{3\sqrt{17}}2`) },
    { prompt: [p(text("The sequence "), math("a_n"), text(" is defined by")), d(T`a_n=(-1)^n-(-1)^{n-1}+(-1)^{n+2}\quad(n\ge1)`), p(text("Find "), math(T`\sum_{n=1}^{39}a_n`), text("."))], options: mo("-39","-3","-1","0","1","3","39") },
    { prompt: [p(text("What is the total area enclosed between "), math(T`y=x^2-1`), text(", the "), math("x"), text("-axis and the lines "), math("x=-2"), text(" and "), math("x=2"), text("?"))], options: mo(T`\frac43`,T`\frac83`,`4`,T`\frac{16}3`,`12`,`16`) },
    { prompt: [p(text("Mixtures "), math("P,Q,R"), text(" contain red and white paint. The red proportions in "), math("P,Q"), text(" are 30% and 20%. They are combined in the ratio "), math("12:5:3"), text(" and the result is 25% red. What percentage of "), math("R"), text(" is red?"))], options: to("25%","23%","13⅓%","19½%","9¾%","It is impossible to achieve this result.") },
    { prompt: [p(text("60% of a sports club are women. Every member plays exactly one of tennis or cricket. "), math(T`\frac25`), text(" of the men play cricket, and "), math(T`\frac23`), text(" of the cricket players are women. What is the probability that a random member is a woman who plays tennis?"))], options: mo(T`\frac15`,T`\frac7{25}`,T`\frac13`,T`\frac{11}{25}`,T`\frac35`) },
    { prompt: [p(text("Find the maximum angle "), math("x"), text(" in "), math(T`0^\circ\le x\le360^\circ`), text(" satisfying")), d(T`\cos^2(2x)+\sqrt3\sin(2x)-\frac74=0`)], options: mo(T`30^\circ`,T`60^\circ`,T`120^\circ`,T`150^\circ`,T`210^\circ`,T`240^\circ`,T`300^\circ`,T`330^\circ`) },
    { prompt: [p(text("The segment joining "), math("(3,3)"), text(" and "), math("(7,5)"), text(" is a diameter of a circle. Translate it 3 units left, reflect it in the "), math("x"), text("-axis, then enlarge it by scale factor 4 about its centre. The final circle is"))], options: mo(T`(x-2)^2+(y-4)^2=320`,T`(x-2)^2+(y+4)^2=320`,T`(x-2)^2+(y-4)^2=80`,T`(x-2)^2+(y+4)^2=80`,T`(x-2)^2+(y-4)^2=20`,T`(x-2)^2+(y+4)^2=20`) },
    { prompt: [p(text("How many solutions does "), math(T`x\tan x=1`), text(" have in "), math(T`-2\pi\le x\le2\pi`), text("?"))], options: mo("0","1","2","3","4","5","6") },
    { prompt: [p(text("The real roots of "), math(T`4^{2x}+12=2^{2x+3}`), text(" are "), math("p,q"), text(" with "), math("p>q"), text(". The value of "), math("p-q"), text(" is"))], options: mo(T`\frac34`,`1`,`4`,T`-\frac12+\frac32\log_{10}3`,T`\frac{\log_{10}3}{\log_{10}4}`,T`\frac{\log_{10}3}{\log_{10}2}`) },
    { prompt: [p(text("A right circular cylinder is inscribed in a sphere of radius 5 cm, with both end circumferences touching the sphere.")), fig("/questions/tmua-practice-2016-p1/q12.svg","Cross-section of a cylinder inscribed in a sphere"), p(text("Find the maximum possible volume of the cylinder."))], options: mo(T`250\pi`,T`500\pi`,T`1000\pi`,T`\frac{250\sqrt3}{3}\pi`,T`\frac{500\sqrt3}{9}\pi`,T`\frac{1000\sqrt3}{9}\pi`) },
    { prompt: [p(text("How many real roots does "), math(T`3x^5-10x^3-120x+30=0`), text(" have?"))], options: mo("1","2","3","4","5") },
    { prompt: [p(text("The terms of an infinite series "), math("S"), text(" are formed by adding corresponding terms of two geometric series "), math("T,U"), text(". Both first terms are 4, and the first three terms of "), math("S"), text(" are "), math(T`8,3,\frac54`), text(". Find the sum to infinity of "), math("S"), text("."))], options: mo(T`\frac{32}5`,T`\frac{20}3`,T`\frac{64}5`,T`\frac{40}3`,`16`,`32`) },
    { prompt: [p(text("As "), math("a"), text(" varies, find the least possible gradient at "), math("x=1"), text(" of")), d(T`y=(2x+a)(x-2a)^2`)], options: mo(T`-\frac{49}4`,`-8`,T`-\frac{25}4`,T`\frac74`,T`\frac{47}4`) },
    { prompt: [p(text("Given")), d(T`\log_{10}2+\log_{10}(y-1)=2\log_{10}x`), d(T`\log_{10}(y+3-3x)=0`), p(text("the values of "), math("y"), text(" are"))], options: mo(T`\frac52\pm\frac{3\sqrt5}2`,T`3\pm\sqrt3`,T`7\pm3\sqrt3`,`3,9`,`1,13`) },
    { prompt: [p(text("For "), math(T`0<x<\pi`), text(", let "), math(T`y=(1+2\cos x)\cos2x`), text(". The complete set of values for which "), math("y<0"), text(" is"))], options: mo(T`0<x<\frac\pi4,\ \frac{2\pi}3<x<\frac{3\pi}4`,T`0<x<\frac\pi4,\ \frac{3\pi}4<x<\pi`,T`0<x<\frac{2\pi}3,\ \frac{3\pi}4<x<\pi`,T`\frac\pi4<x<\frac{2\pi}3,\ \frac{3\pi}4<x<\pi`,T`\frac\pi4<x<\frac{2\pi}3`,T`\frac\pi4<x<\frac{3\pi}4`) },
    { prompt: [p(text("The function "), math(T`\frac{1-x}{\sqrt[3]{x^2}}`), text(" is defined for "), math("x\ne0"), text(". The complete set for which it is decreasing is"))], options: mo(T`x\le-2,\ x>0`,T`-2\le x<0`,T`x\le1,\ x\ne0`,T`x\ge1`,T`-2\le x\le1,\ x\ne0`,T`x\le-2,\ x\ge1`) },
    { prompt: [p(text("The coefficient of "), math("x^3"), text(" in "), math(T`(1+2x+3x^2)^6`), text(" is twice the coefficient of "), math("x^4"), text(" in "), math(T`(1-ax^2)^5`), text(". Find all possible values of "), math("a"), text("."))], options: mo(T`\pm2\sqrt2`,T`\pm\sqrt{17}`,T`\pm\sqrt{34}`,T`\pm2\sqrt{17}`,T`\text{no possible values}`) },
    { prompt: [p(text("A square-based pyramid has base "), math("PQRS"), text(" and vertex "), math("O"), text("; every edge has length 20 m.")), fig("/questions/tmua-practice-2016-p1/q20.svg","Square-based pyramid with all edges equal"), p(text("Find the shortest distance along its surface from "), math("P"), text(" to the midpoint of "), math("OR"), text("."))], options: mo(T`10\sqrt{5-2\sqrt3}`,T`10\sqrt3`,T`10\sqrt5`,T`10\sqrt7`,T`10\sqrt{5+2\sqrt3}`) },
  ],
});
