import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const sourcePath = "content/notes/tmua/specimen-p1-worked-explanations-v1.json";
const targetPath = "supabase/migrations/20260718213000_tmua_specimen_p1_deep_review.sql";
const resourceId = "tmua-specimen-p1-worked-explanations-v1";

const source = await readFile(sourcePath, "utf8");
const payload = JSON.parse(source) as { readonly id?: unknown };
if (payload.id !== resourceId) {
  throw new Error(`Canonical payload ID must be ${resourceId}`);
}
const canonical = source.endsWith("\n") ? source : `${source}\n`;
const digest = createHash("sha256").update(canonical).digest("hex");

const sql = `-- Generated by scripts/build-tmua-specimen-deep-review-migration.ts.
-- Edit ${sourcePath}, then rerun pnpm content:build-tmua-deep-review.

insert into public.access_packages (id, name, description, status)
values (
  'tmua-deep-review',
  'TMUA 深度解析',
  '已发布试卷的逐题思路、易错点和后续训练建议；题目、答案和基础结果不需要该权限。',
  'active'
)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    status = excluded.status;

insert into public.content_resources (
  id,
  exam,
  kind,
  title,
  access_tier,
  publication_status,
  revision,
  metadata,
  published_at
) values (
  '${resourceId}',
  'TMUA',
  'answer_explanation',
  'TMUA Early Specimen Paper 1 逐题深度解析',
  'entitled',
  'published',
  1,
  '{"delivery":"server-structured-native-page","contentSchema":"tmua-worked-explanations","paperId":"tmua-specimen-p1","questionCount":20,"edition":"2026.07-v1"}'::jsonb,
  '2026-07-18T21:30:00Z'::timestamptz
)
on conflict (id) do update
set title = excluded.title,
    access_tier = excluded.access_tier,
    publication_status = excluded.publication_status,
    revision = excluded.revision,
    metadata = excluded.metadata,
    published_at = excluded.published_at;

delete from public.access_package_resources
where package_id = 'tmua-deep-review'
  and resource_id = 'tmua-deep-review-v1';

insert into public.access_package_resources (package_id, resource_id)
values
  ('tmua-deep-review', '${resourceId}'),
  ('tmua-full-access', '${resourceId}')
on conflict do nothing;

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  '${resourceId}',
  1,
  '${digest}',
  $payload$
${canonical.trimEnd()}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();
`;

await writeFile(targetPath, sql, "utf8");
console.log(`${targetPath} <- ${sourcePath} (${digest})`);
