import { createHash } from "node:crypto";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { allPublishedPracticePapers } from "./lib/all-published-practice-papers.js";
import {
  buildPracticePublicationLedger,
  type PracticePublicationRecord,
} from "./lib/practice-paper-publication.js";

const manifestPath = resolve("content/practice/published-paper-revisions.json");
const writeMode = process.argv.includes("--write");
const migrationsDirectory = resolve("supabase/migrations");

interface PublicationManifest {
  readonly schemaVersion: 1;
  readonly generatedAt: string;
  readonly papers: readonly PracticePublicationRecord[];
}

async function readExisting(): Promise<PublicationManifest | null> {
  try {
    return JSON.parse(await readFile(manifestPath, "utf8")) as PublicationManifest;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

function migrationTimestamp(date: Date): string {
  return date.toISOString().replace(/[-:T]/gu, "").slice(0, 14);
}

function revisionTuple(record: PracticePublicationRecord): string {
  return `('${record.paperRevisionId}', '${record.paperId}', ${record.revision}, '${record.exam}', ${record.schemaVersion}, '${record.contentDigest}', ${record.questionCount}, ${record.durationMinutes}, '${record.publishedAt}')`;
}

async function revisionMigrationBodies(): Promise<string> {
  const names = (await readdir(migrationsDirectory))
    .filter((name) => /^\d{14}_published_practice_revision_(?:seed|release_[a-f0-9]{8})\.sql$/u.test(name))
    .sort();
  return (await Promise.all(names.map((name) => readFile(resolve(migrationsDirectory, name), "utf8")))).join("\n");
}

async function main(): Promise<void> {
  const existing = await readExisting();
  const existingRecords = [...(existing?.papers ?? [])];
  const now = new Date().toISOString();
  const papers = [...allPublishedPracticePapers()].sort((left, right) =>
    left.id.localeCompare(right.id),
  );
  const { records, currentRecords } = buildPracticePublicationLedger(papers, existingRecords, now);
  const existingByPaper = new Map(existingRecords.map((record) => [record.paperId, record]));
  const manifest: PublicationManifest = {
    schemaVersion: 1,
    generatedAt: writeMode ? now : existing?.generatedAt ?? now,
    papers: records,
  };
  const migrations = await revisionMigrationBodies();
  const missingMigrationRecords = records.filter((record) => !migrations.includes(revisionTuple(record)));

  if (writeMode) {
    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    if (missingMigrationRecords.length > 0) {
      const body = [
        "-- Append-only practice revision release generated by scripts/build-published-practice-revisions.ts.",
        "insert into public.practice_content_revisions (paper_revision_id, paper_id, revision, exam, schema_version, content_digest, question_count, duration_minutes, published_at) values",
        `${missingMigrationRecords.map(revisionTuple).map((row, index, rows) => `  ${row}${index === rows.length - 1 ? ";" : ","}`).join("\n")}`,
        "",
      ].join("\n");
      const releaseId = createHash("sha256").update(body).digest("hex").slice(0, 8);
      const releasePath = resolve(
        migrationsDirectory,
        `${migrationTimestamp(new Date())}_published_practice_revision_release_${releaseId}.sql`,
      );
      await writeFile(releasePath, body, { encoding: "utf8", flag: "wx" });
      console.log(`Created append-only revision migration for ${missingMigrationRecords.length} revisions`);
    }
    console.log(`Published ${currentRecords.length} current papers across ${records.length} immutable revisions`);
    return;
  }

  if (existing === null) {
    throw new Error("Published practice revision manifest is missing; run with --write");
  }
  const expected = JSON.stringify({ ...manifest, generatedAt: existing.generatedAt });
  const actual = JSON.stringify(existing);
  if (expected !== actual) {
    const changed = currentRecords
      .filter((record) => existingByPaper.get(record.paperId)?.contentDigest !== record.contentDigest)
      .map((record) => record.paperId);
    throw new Error(
      `Published practice revisions are stale${changed.length === 0 ? "" : `: ${changed.join(", ")}`}; run content:publish-practice-revisions after review`,
    );
  }
  if (missingMigrationRecords.length > 0) {
    throw new Error(
      `Published practice revisions are missing database migrations: ${missingMigrationRecords.map((record) => record.paperRevisionId).join(", ")}`,
    );
  }
  console.log(`Verified ${currentRecords.length} current papers across ${records.length} immutable revisions`);
}

await main();
