import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { parseAdvancedReviewNotes } from "../src/features/entitled-content/advanced-review-notes.js";

const targetPath = "supabase/migrations/20260726150000_esat_tara_advanced_notes.sql";
const sources = [
  {
    path: "content/notes/esat/advanced-review-notes-v1.json",
    resourceId: "esat-advanced-notes-v1",
    packageId: "esat-deep-review",
    packageName: "ESAT Advanced Review · ESAT 深度复习",
    packageDescription: "Private English-first module playbooks, worked cases and training prescriptions with concise Chinese learning support.",
    exam: "ESAT",
    title: "ESAT Advanced Review Notes · ESAT 深度复习笔记",
  },
  {
    path: "content/notes/tara/advanced-review-notes-v1.json",
    resourceId: "tara-advanced-notes-v1",
    packageId: "tara-deep-review",
    packageName: "TARA Advanced Review · TARA 深度复习",
    packageDescription: "Private English-first reasoning and writing playbooks, worked cases and training prescriptions with concise Chinese learning support.",
    exam: "TARA",
    title: "TARA Advanced Review Notes · TARA 深度复习笔记",
  },
] as const;

const rendered: string[] = [];
for (const source of sources) {
  const raw = await readFile(source.path, "utf8");
  const parsed = parseAdvancedReviewNotes(JSON.parse(raw));
  if (parsed.id !== source.resourceId || parsed.examId.toUpperCase() !== source.exam) {
    throw new Error(`${source.path} does not match its declared resource`);
  }
  const canonical = raw.endsWith("\n") ? raw : `${raw}\n`;
  if (canonical.includes("$payload$")) {
    throw new Error(`${source.path} contains the SQL payload delimiter`);
  }
  const digest = createHash("sha256").update(canonical).digest("hex");
  rendered.push(`insert into public.access_packages (id, name, description, status)
values (
  '${source.packageId}',
  '${source.packageName}',
  '${source.packageDescription}',
  'active'
)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    status = excluded.status;

insert into public.content_resources (
  id,
  exam,
  kind,
  title,
  access_tier,
  publication_status,
  revision,
  metadata,
  published_at
) values (
  '${source.resourceId}',
  '${source.exam}',
  'review_notes',
  '${source.title}',
  'entitled',
  'published',
  1,
  '${JSON.stringify({
    delivery: "server-structured-native-page",
    contentSchema: "advanced-review-notes",
    schemaVersion: 1,
    edition: parsed.edition,
    moduleCount: parsed.modules.length,
    languagePolicy: "english-first-zh-support",
  })}'::jsonb,
  '2026-07-26T15:00:00Z'::timestamptz
)
on conflict (id) do update
set exam = excluded.exam,
    kind = excluded.kind,
    title = excluded.title,
    access_tier = excluded.access_tier,
    publication_status = excluded.publication_status,
    revision = excluded.revision,
    metadata = excluded.metadata,
    published_at = excluded.published_at,
    updated_at = now();

insert into public.access_package_resources (package_id, resource_id)
values ('${source.packageId}', '${source.resourceId}')
on conflict do nothing;

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  '${source.resourceId}',
  1,
  '${digest}',
  $payload$
${canonical.trimEnd()}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();`);
}

const sql = `-- Generated by scripts/build-advanced-review-notes-migration.ts.
-- Edit the canonical ESAT or TARA advanced-note JSON, then rerun pnpm content:build-advanced-notes.

${rendered.join("\n\n")}
`;

await writeFile(targetPath, sql, "utf8");
console.log(`${targetPath} <- ${sources.map((source) => source.path).join(", ")}`);
