import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const sourcePath = "content/notes/tmua/specimen-p1-worked-explanations-v1.json";
const targetPath = "supabase/migrations/20260726143000_tmua_specimen_p1_deep_review_english_first.sql";
const resourceId = "tmua-specimen-p1-worked-explanations-v1";

const source = await readFile(sourcePath, "utf8");
const payload = JSON.parse(source) as {
  readonly id?: unknown;
  readonly schemaVersion?: unknown;
};
if (payload.id !== resourceId || payload.schemaVersion !== 2) {
  throw new Error(`Canonical payload must be ${resourceId} at schemaVersion 2`);
}
const canonical = source.endsWith("\n") ? source : `${source}\n`;
const digest = createHash("sha256").update(canonical).digest("hex");

const sql = `-- Generated by scripts/build-tmua-specimen-deep-review-migration.ts.
-- Edit ${sourcePath}, then rerun pnpm content:build-tmua-deep-review.

update public.access_packages
set name = 'TMUA Worked Review · TMUA 逐题深度解析',
    description = 'English-first reasoning, steps, traps and next drills, with concise Chinese learning support.'
where id = 'tmua-deep-review';

update public.content_resources
set title = 'TMUA Early Specimen Paper 1 Worked Review · 逐题深度解析',
    revision = 2,
    metadata = '{"delivery":"server-structured-native-page","contentSchema":"tmua-worked-explanations","schemaVersion":2,"paperId":"tmua-specimen-p1","questionCount":20,"edition":"2026.07-v1","languagePolicy":"english-first-zh-support"}'::jsonb,
    published_at = '2026-07-26T14:30:00Z'::timestamptz
where id = '${resourceId}';

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  '${resourceId}',
  2,
  '${digest}',
  $payload$
${canonical.trimEnd()}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();
`;

await writeFile(targetPath, sql, "utf8");
console.log(`${targetPath} <- ${sourcePath} (${digest})`);
