-- Generated by scripts/build-advanced-review-notes-migration.ts.
-- Edit the canonical ESAT or TARA advanced-note JSON, then rerun pnpm content:build-advanced-notes.

insert into public.access_packages (id, name, description, status)
values (
  'esat-deep-review',
  'ESAT Advanced Review · ESAT 深度复习',
  'Private English-first module playbooks, worked cases and training prescriptions with concise Chinese learning support.',
  'active'
)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    status = excluded.status;

insert into public.content_resources (
  id,
  exam,
  kind,
  title,
  access_tier,
  publication_status,
  revision,
  metadata,
  published_at
) values (
  'esat-advanced-notes-v1',
  'ESAT',
  'review_notes',
  'ESAT Advanced Review Notes · ESAT 深度复习笔记',
  'entitled',
  'published',
  1,
  '{"delivery":"server-structured-native-page","contentSchema":"advanced-review-notes","schemaVersion":1,"edition":"2026.07-v1","moduleCount":5,"languagePolicy":"english-first-zh-support"}'::jsonb,
  '2026-07-26T15:00:00Z'::timestamptz
)
on conflict (id) do update
set exam = excluded.exam,
    kind = excluded.kind,
    title = excluded.title,
    access_tier = excluded.access_tier,
    publication_status = excluded.publication_status,
    revision = excluded.revision,
    metadata = excluded.metadata,
    published_at = excluded.published_at,
    updated_at = now();

insert into public.access_package_resources (package_id, resource_id)
values ('esat-deep-review', 'esat-advanced-notes-v1')
on conflict do nothing;

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  'esat-advanced-notes-v1',
  1,
  '712c01035493a53129688445be09b66d9e96925e22f3c030e0ad8ac52f3eb448',
  $payload$
{
  "schemaVersion": 1,
  "id": "esat-advanced-notes-v1",
  "examId": "esat",
  "edition": "2026.07-v1",
  "publicationStatus": "published",
  "titleEn": "ESAT Advanced Strategy Notes",
  "titleZh": "ESAT 深度策略笔记",
  "subtitleEn": "Five module-specific playbooks for turning knowledge into fast, checkable decisions under non-calculator pressure.",
  "subtitleZh": "按五个模块拆解无计算器限时环境下的识别信号、决策动作、检查方式与训练处方。",
  "authorshipEn": "Original teaching material by Mantou",
  "authorshipZh": "满托教研原创",
  "audienceEn": "For students who have completed the foundation notes and begun timed ESAT practice in their selected modules.",
  "audienceZh": "适合已完成基础笔记，并已开始本人所选 ESAT 模块限时练习的学生。",
  "rightsNoticeEn": "Independently authored from verified scope and terminology. No official question, example or explanation is reproduced.",
  "rightsNoticeZh": "依据已核验范围与术语独立撰写，不复制官方题目、例题或讲解。",
  "modules": [
    {
      "id": "mathematics-1",
      "number": "01",
      "titleEn": "Mathematics 1 — Quantities, Structure and Decisions",
      "titleZh": "Mathematics 1：数量、结构与决策",
      "purposeEn": "Make units, ratios, algebra and data displays executable before arithmetic begins.",
      "purposeZh": "在开始计算前，把单位、比例、代数与数据图表转化为可执行关系。",
      "knowledgeFocusEn": ["Compound units and dimensional consistency", "Ratios, percentages and multiplicative change", "Algebraic structure, estimates and data displays"],
      "knowledgeFocusZh": ["复合单位与量纲一致性", "比例、百分比与乘法变化", "代数结构、估算与数据表示"],
      "playbooks": [
        {
          "titleEn": "Dimension before number",
          "titleZh": "先量纲，后数字",
          "triggerEn": "The stem mixes units, rates or quantities defined per unit time, mass or volume.",
          "triggerZh": "题干混合单位、速率，或出现每单位时间、质量、体积的量。",
          "actionEn": "Write the required unit, cancel dimensions symbolically, then substitute only the numbers that survive.",
          "actionZh": "先写目标单位，用符号消去量纲，再代入仍需使用的数字。",
          "checkEn": "The final dimension and order of magnitude must both match the physical description.",
          "checkZh": "最终量纲与数量级必须同时符合情境。"
        },
        {
          "titleEn": "Estimate before exact work",
          "titleZh": "精算前先估算",
          "triggerEn": "Options are widely separated or exact arithmetic is likely to create decimal noise.",
          "triggerZh": "选项差距明显，或精确运算容易产生小数噪音。",
          "actionEn": "Fix sign, scale and a plausible interval, then perform the shortest exact calculation that separates the remaining options.",
          "actionZh": "先确定正负、数量级和合理区间，再做能区分剩余选项的最短精确运算。",
          "checkEn": "If the exact value contradicts the estimate, audit the ratio direction and unit conversion first.",
          "checkZh": "若精确值与估算冲突，先检查比例方向和单位换算。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — density without decimal drift",
        "titleZh": "深度案例：避免小数漂移的密度计算",
        "promptEn": "A sample has mass 2.4 kg and volume 300 cm³. Determine its density in kg m⁻³.",
        "promptZh": "某样品质量为 2.4 kg、体积为 300 cm³，求以 kg m⁻³ 表示的密度。",
        "steps": [
          { "labelEn": "Convert the volume", "labelZh": "换算体积", "bodyEn": "Since 1 cm³=10⁻⁶ m³, 300 cm³=3×10⁻⁴ m³.", "bodyZh": "因为 1 cm³=10⁻⁶ m³，所以 300 cm³=3×10⁻⁴ m³。" },
          { "labelEn": "Preserve the structure", "labelZh": "保留结构", "bodyEn": "Write 2.4/(3×10⁻⁴) rather than converting immediately to a long decimal.", "bodyZh": "先写成 2.4/(3×10⁻⁴)，不要立刻展开成长小数。" },
          { "labelEn": "Calculate and test", "labelZh": "计算并核验", "bodyEn": "2.4÷3=0.8 and dividing by 10⁻⁴ multiplies by 10⁴, giving 8.0×10³ kg m⁻³.", "bodyZh": "2.4÷3=0.8，再除以 10⁻⁴ 等于乘 10⁴，得到 8.0×10³ kg m⁻³。" }
        ],
        "answerEn": "The density is 8000 kg m⁻³.",
        "answerZh": "密度为 8000 kg m⁻³。",
        "trapEn": "Treating 1 cm as 10⁻² m but forgetting to cube the conversion factor.",
        "trapZh": "只把厘米换成 10⁻² 米，却忘记体积换算因子需要立方。"
      },
      "trainingPrescriptionEn": ["Complete 12 mixed unit-and-ratio questions without a calculator.", "Record every first unit-conversion error, not only wrong final answers.", "Repeat the set after 48 hours and require at least 10/12 correct."],
      "trainingPrescriptionZh": ["完成 12 道无计算器单位与比例混合题。", "记录第一次单位换算错误，而不只记录最终错题。", "48 小时后回做，至少达到 10/12。"]
    },
    {
      "id": "mathematics-2",
      "number": "02",
      "titleEn": "Mathematics 2 — Functions, Graphs and Change",
      "titleZh": "Mathematics 2：函数、图像与变化",
      "purposeEn": "Recognise graph structure, parameter effects and rates of change before committing to algebra.",
      "purposeZh": "在进入代数运算前，先识别图像结构、参数影响与变化率。",
      "knowledgeFocusEn": ["Transformations, intersections and parameter families", "Sequences, trigonometry, exponentials and logarithms", "Differentiation, integration and graphical interpretation"],
      "knowledgeFocusZh": ["变换、交点与参数函数族", "数列、三角、指数与对数", "微分、积分与图像解释"],
      "playbooks": [
        {
          "titleEn": "Predict the graph before solving",
          "titleZh": "求解前先预测图像",
          "triggerEn": "The question asks for intersections, roots, signs or the effect of a parameter.",
          "triggerZh": "题目询问交点、根、正负区间或参数影响。",
          "actionEn": "State the expected number and location of features, then form the equation that tests that prediction.",
          "actionZh": "先写出特征数量与大致位置，再列方程验证预测。",
          "checkEn": "Every algebraic root must sit on the predicted branch and satisfy the original domain.",
          "checkZh": "每个代数根都必须落在预测分支上并满足原定义域。"
        },
        {
          "titleEn": "Translate derivative signs",
          "titleZh": "翻译导数符号",
          "triggerEn": "The stem connects gradient, turning points, optimisation or changing rate.",
          "triggerZh": "题干连接斜率、转折点、最优化或变化速率。",
          "actionEn": "Create a sign table for f′ before calculating exact coordinates; use f′′ only when it answers a remaining ambiguity.",
          "actionZh": "先为 f′ 建符号表，再计算精确坐标；只有存在歧义时才使用 f′′。",
          "checkEn": "Verify that the reported extremum agrees with the sign change, not merely f′=0.",
          "checkZh": "极值必须符合符号变化，不能只凭 f′=0。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — one tangent, one parameter",
        "titleZh": "深度案例：参数与唯一切线",
        "promptEn": "For y=x²-4x+k, determine the value of k for which the graph is tangent to the x-axis.",
        "promptZh": "对 y=x²-4x+k，求图像与 x 轴相切时的 k。",
        "steps": [
          { "labelEn": "Translate tangent", "labelZh": "翻译相切", "bodyEn": "Tangency to the x-axis means the quadratic has one repeated real root.", "bodyZh": "与 x 轴相切意味着二次方程有一个二重实根。" },
          { "labelEn": "Choose the shortest condition", "labelZh": "选择最短条件", "bodyEn": "Use discriminant zero: (-4)²-4(1)(k)=0.", "bodyZh": "使用判别式为零：(-4)²-4(1)(k)=0。" },
          { "labelEn": "Solve and verify", "labelZh": "求解并核验", "bodyEn": "k=4, so y=(x-2)², which touches the axis at x=2 without crossing it.", "bodyZh": "k=4，此时 y=(x-2)²，在 x=2 处接触 x 轴但不穿过。" }
        ],
        "answerEn": "k=4.",
        "answerZh": "k=4。",
        "trapEn": "Solving for the roots first and losing the structural meaning of tangency.",
        "trapZh": "先完整求根，反而丢失“相切”的结构含义。"
      },
      "trainingPrescriptionEn": ["Build a trigger sheet linking graph language to algebraic conditions.", "Complete two 20-minute mixed sets on functions and calculus.", "For each error, record whether prediction, route or execution failed first."],
      "trainingPrescriptionZh": ["建立图像语言到代数条件的触发表。", "完成两组 20 分钟函数与微积分混合题。", "每道错题记录最先失败的是预测、路径还是执行。"]
    },
    {
      "id": "physics",
      "number": "03",
      "titleEn": "Physics — Model Selection and Physical Checks",
      "titleZh": "Physics：模型选择与物理核验",
      "purposeEn": "Choose a valid model, preserve units and reject answers that violate direction, scale or conservation.",
      "purposeZh": "选择有效模型、保留单位，并用方向、数量级和守恒排除不合理答案。",
      "knowledgeFocusEn": ["Forces, motion, energy and momentum", "Electricity, waves, thermal physics and matter", "Graphs, experimental data and proportional reasoning"],
      "knowledgeFocusZh": ["力、运动、能量与动量", "电学、波、热学与物质", "图像、实验数据与比例推理"],
      "playbooks": [
        {
          "titleEn": "Name the system",
          "titleZh": "先定义系统",
          "triggerEn": "More than one object, force or energy store appears in the stem.",
          "triggerZh": "题干中出现多个物体、力或能量储存。",
          "actionEn": "State the system boundary, draw only external interactions, then choose force, momentum or energy according to what crosses the boundary.",
          "actionZh": "先写系统边界，只画外部相互作用，再依据穿过边界的量选择力、动量或能量。",
          "checkEn": "Internal forces must not be counted twice, and every sign must match the chosen positive direction.",
          "checkZh": "内部力不能重复计算，所有符号必须符合所选正方向。"
        },
        {
          "titleEn": "Test limiting cases",
          "titleZh": "检查极限情形",
          "triggerEn": "An expression depends on a parameter, resistance, angle, mass or frequency.",
          "triggerZh": "表达式依赖参数、电阻、角度、质量或频率。",
          "actionEn": "Ask what the result must do when the parameter tends to zero or becomes very large, before choosing an option.",
          "actionZh": "选项判断前，先问参数趋近零或极大时结果必须如何变化。",
          "checkEn": "Reject any formula with the wrong units or the wrong limiting behaviour.",
          "checkZh": "量纲错误或极限行为错误的公式直接排除。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — force from a velocity graph",
        "titleZh": "深度案例：从速度图像得到合力",
        "promptEn": "A 0.50 kg trolley increases speed uniformly from 2 m s⁻¹ to 8 m s⁻¹ in 3 s. Find the resultant force.",
        "promptZh": "质量 0.50 kg 的小车在 3 s 内由 2 m s⁻¹ 匀加速到 8 m s⁻¹，求合力。",
        "steps": [
          { "labelEn": "Read the gradient", "labelZh": "读取斜率", "bodyEn": "Acceleration is the gradient of velocity against time: (8-2)/3=2 m s⁻².", "bodyZh": "加速度是速度—时间图像斜率：(8-2)/3=2 m s⁻²。" },
          { "labelEn": "Select the model", "labelZh": "选择模型", "bodyEn": "For the trolley as the system, resultant force equals mass times acceleration.", "bodyZh": "以小车为系统，合力等于质量乘加速度。" },
          { "labelEn": "Calculate and check", "labelZh": "计算并核验", "bodyEn": "F=0.50×2=1.0 N, positive in the direction of increasing velocity.", "bodyZh": "F=0.50×2=1.0 N，方向与速度增加方向一致。" }
        ],
        "answerEn": "The resultant force is 1.0 N.",
        "answerZh": "合力为 1.0 N。",
        "trapEn": "Using final velocity divided by time instead of change in velocity divided by time.",
        "trapZh": "用末速度除以时间，而不是速度变化量除以时间。"
      },
      "trainingPrescriptionEn": ["For ten mixed questions, write the system and governing model before any equation.", "Audit every wrong option by units or a limiting case.", "Repeat graph questions until gradient and area meanings are automatic."],
      "trainingPrescriptionZh": ["完成 10 道混合题，每题先写系统与主模型。", "用量纲或极限情形审查每个错误选项。", "回做图像题，直到斜率和面积含义能自动调用。"]
    },
    {
      "id": "chemistry",
      "number": "04",
      "titleEn": "Chemistry — Ratios, Particles and Direction",
      "titleZh": "Chemistry：比例、粒子与方向",
      "purposeEn": "Translate chemical language into particle or mole relationships before using memorised equations.",
      "purposeZh": "在套用公式前，把化学语言转化为粒子或物质的量关系。",
      "knowledgeFocusEn": ["Atomic structure, bonding and periodic patterns", "Equations, moles, concentrations and redox", "Energetics, rates, equilibria and practical evidence"],
      "knowledgeFocusZh": ["原子结构、键合与周期规律", "方程、物质的量、浓度与氧化还原", "能量、速率、平衡与实验依据"],
      "playbooks": [
        {
          "titleEn": "Build the mole map",
          "titleZh": "建立摩尔关系图",
          "triggerEn": "Mass, volume, concentration, gas amount or an equation coefficient appears.",
          "triggerZh": "出现质量、体积、浓度、气体量或方程式系数。",
          "actionEn": "Convert the given quantity to moles, cross the balanced-equation ratio once, then convert to the requested quantity.",
          "actionZh": "先把已知量转成物质的量，只跨一次配平方程比例，再转为所求量。",
          "checkEn": "The limiting reagent, units and significant scale must agree with the physical amount available.",
          "checkZh": "限量试剂、单位和数量级必须符合实际可用物质量。"
        },
        {
          "titleEn": "Predict direction before magnitude",
          "titleZh": "先判断方向，再判断大小",
          "triggerEn": "The question changes temperature, concentration, pressure, catalyst or molecular structure.",
          "triggerZh": "题目改变温度、浓度、压力、催化剂或分子结构。",
          "actionEn": "Name the process affected, predict the direction from particle collisions or energy, then assess the size only if required.",
          "actionZh": "先指出受影响过程，用粒子碰撞或能量判断方向，再在需要时判断大小。",
          "checkEn": "Do not let a catalyst change equilibrium position or an unchanged stoichiometric ratio change yield by itself.",
          "checkZh": "催化剂不能改变平衡位置，未变的化学计量比也不能自行改变产率。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — concentration through stoichiometry",
        "titleZh": "深度案例：通过化学计量求浓度",
        "promptEn": "25.0 cm³ of HCl is neutralised by 20.0 cm³ of 0.150 mol dm⁻³ NaOH. Find the HCl concentration.",
        "promptZh": "25.0 cm³ HCl 恰好被 20.0 cm³、0.150 mol dm⁻³ NaOH 中和，求 HCl 浓度。",
        "steps": [
          { "labelEn": "Convert volume", "labelZh": "换算体积", "bodyEn": "20.0 cm³=0.0200 dm³, so NaOH moles are 0.150×0.0200=0.00300 mol.", "bodyZh": "20.0 cm³=0.0200 dm³，所以 NaOH 为 0.150×0.0200=0.00300 mol。" },
          { "labelEn": "Use the equation ratio", "labelZh": "使用方程比例", "bodyEn": "HCl+NaOH→NaCl+H₂O is 1:1, so HCl also contains 0.00300 mol.", "bodyZh": "HCl+NaOH→NaCl+H₂O 为 1:1，所以 HCl 也是 0.00300 mol。" },
          { "labelEn": "Recover concentration", "labelZh": "求回浓度", "bodyEn": "25.0 cm³=0.0250 dm³; concentration=0.00300/0.0250=0.120 mol dm⁻³.", "bodyZh": "25.0 cm³=0.0250 dm³；浓度=0.00300/0.0250=0.120 mol dm⁻³。" }
        ],
        "answerEn": "The HCl concentration is 0.120 mol dm⁻³.",
        "answerZh": "HCl 浓度为 0.120 mol dm⁻³。",
        "trapEn": "Dividing by 25.0 without converting cm³ to dm³.",
        "trapZh": "直接除以 25.0，却没有把 cm³ 换成 dm³。"
      },
      "trainingPrescriptionEn": ["Draw a three-node given→moles→wanted map for every quantitative item.", "Classify trend questions by particle, energy or equilibrium mechanism.", "Complete one timed mixed set and record the first missing conversion."],
      "trainingPrescriptionZh": ["每道定量题画出“已知量→摩尔→所求量”三节点图。", "把趋势题归为粒子、能量或平衡机制。", "完成一组限时混合题，记录第一次漏掉的换算。"]
    },
    {
      "id": "biology",
      "number": "05",
      "titleEn": "Biology — Mechanisms, Evidence and Experimental Control",
      "titleZh": "Biology：机制、证据与实验控制",
      "purposeEn": "Separate a plausible biological story from a conclusion actually supported by the experiment or data.",
      "purposeZh": "区分听起来合理的生物学叙述与实验或数据真正支持的结论。",
      "knowledgeFocusEn": ["Cells, membranes, enzymes and transport", "Inheritance, DNA, variation and biotechnology", "Organisms, ecosystems, data and experimental design"],
      "knowledgeFocusZh": ["细胞、膜、酶与运输", "遗传、DNA、变异与生物技术", "生物体、生态、数据与实验设计"],
      "playbooks": [
        {
          "titleEn": "Mechanism in three links",
          "titleZh": "三段式机制链",
          "triggerEn": "The stem asks why a variable changes a biological rate, distribution or phenotype.",
          "triggerZh": "题干询问某变量为何改变生物速率、分布或表型。",
          "actionEn": "Write variable→molecular or cellular effect→measured outcome. Add no link that is absent from the stated system.",
          "actionZh": "写成“变量→分子或细胞效应→测量结果”，不加入题设系统外的环节。",
          "checkEn": "Each arrow must have a direction and a mechanism, not merely two correlated observations.",
          "checkZh": "每个箭头都要有方向和机制，不能只是两个相关观察。"
        },
        {
          "titleEn": "Control the comparison",
          "titleZh": "控制比较关系",
          "triggerEn": "A table, graph or practical method compares treatments or populations.",
          "triggerZh": "表格、图像或实验方法比较处理组或群体。",
          "actionEn": "Identify the independent, dependent and controlled variables, then compare like with like using a rate or percentage where appropriate.",
          "actionZh": "识别自变量、因变量与控制变量，并在需要时用速率或百分比进行同类比较。",
          "checkEn": "A difference is not automatically causal if sample size, baseline or another variable differs.",
          "checkZh": "若样本量、基线或其他变量不同，差异不能自动证明因果。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — interpreting an enzyme experiment",
        "titleZh": "深度案例：解释酶实验",
        "promptEn": "An enzyme produces 18 units of product in 3 minutes at 20°C and 35 units in 5 minutes at 30°C. At which temperature is the measured rate higher?",
        "promptZh": "某酶在 20°C、3 分钟产生 18 单位产物，在 30°C、5 分钟产生 35 单位产物。哪个温度下测得速率更高？",
        "steps": [
          { "labelEn": "Choose a comparable measure", "labelZh": "选择可比指标", "bodyEn": "Total product is not comparable because the durations differ; use product per minute.", "bodyZh": "时间不同，总产物不可直接比较；应使用每分钟产物量。" },
          { "labelEn": "Calculate both rates", "labelZh": "计算两个速率", "bodyEn": "At 20°C the rate is 18/3=6 units min⁻¹; at 30°C it is 35/5=7 units min⁻¹.", "bodyZh": "20°C 时为 18/3=6 单位/分钟；30°C 时为 35/5=7 单位/分钟。" },
          { "labelEn": "State only the supported conclusion", "labelZh": "只写证据支持的结论", "bodyEn": "The measured rate is higher at 30°C, but two points do not establish the optimum temperature.", "bodyZh": "30°C 下测得速率更高，但两个数据点不足以确定最适温度。" }
        ],
        "answerEn": "30°C has the higher measured rate: 7 units min⁻¹.",
        "answerZh": "30°C 下测得速率更高，为 7 单位/分钟。",
        "trapEn": "Comparing 35 with 18 directly, or claiming 30°C is the enzyme's optimum from only two temperatures.",
        "trapZh": "直接比较 35 与 18，或仅凭两个温度就断言 30°C 是最适温度。"
      },
      "trainingPrescriptionEn": ["For every data question, write the comparison measure before calculating.", "Reduce each explanation to a three-link mechanism and test every arrow.", "Review errors as knowledge, data interpretation or unsupported inference."],
      "trainingPrescriptionZh": ["每道数据题先写比较指标，再开始计算。", "把每个解释压缩为三段机制链，并检查每个箭头。", "把错题区分为知识、数据解释或无证据推断。"]
    }
  ],
  "reviewProtocol": [
    { "stepEn": "Attempt", "stepZh": "独立作答", "actionEn": "Complete a timed set before opening these notes.", "actionZh": "打开笔记前先完成一组限时练习。" },
    { "stepEn": "Locate", "stepZh": "定位首错", "actionEn": "Mark the first point where the model, route or execution diverged.", "actionZh": "标出模型、路径或执行第一次偏离的位置。" },
    { "stepEn": "Prescribe", "stepZh": "形成处方", "actionEn": "Choose one playbook and one measurable repeat condition.", "actionZh": "选择一个策略动作和一个可测量的回做条件。" },
    { "stepEn": "Repeat", "stepZh": "间隔回做", "actionEn": "Repeat after 24–48 hours without topic labels or notes.", "actionZh": "24–48 小时后在无主题提示、无笔记条件下回做。" }
  ],
  "sourceAnchors": [
    { "title": "ESAT Content Specification — October 2026 and January 2027", "localPath": "content/official/raw/shared/ESAT_Content_Specification.pdf", "sha256": "da9e853ec99cc0befcae5c8871e48eedc5776d7b2db07b8d5d9e2492a01452b3", "usedForEn": "Used to verify module scope, terminology and the non-calculator test boundary.", "usedForZh": "用于核验模块范围、术语与无计算器考试边界。" },
    { "title": "Notes on Mathematics for TMUA and ESAT Mathematics 2", "localPath": "content/official/raw/shared/Notes_on_Mathematics_-for_TMUA_and_ESAT_M2.pdf", "sha256": "12ed684ee2dfb9b53355d54018ba216b5cd32161e5f6c5c9ee5e96b93cbf8844", "usedForEn": "Used to verify Mathematics 2 scope and vocabulary only.", "usedForZh": "仅用于核验 Mathematics 2 范围与术语。" },
    { "title": "ESAT Guide — Physics", "localPath": "content/official/raw/esat/ESAT_Guide_Physics.pdf", "sha256": "234651aa05f87112e3455bae420de782683938d8d28950293649a8352dc4729e", "usedForEn": "Used to verify Physics scope and terminology only.", "usedForZh": "仅用于核验 Physics 范围与术语。" },
    { "title": "ESAT Guide — Chemistry", "localPath": "content/official/raw/esat/ESAT_GUIDE_Chemistry_June2025.pdf", "sha256": "f1cfbc2ec1c44068526deeaac0b8ef7c87e245259cc89f9ed6b7c9124e359353", "usedForEn": "Used to verify Chemistry scope and terminology only.", "usedForZh": "仅用于核验 Chemistry 范围与术语。" },
    { "title": "ESAT Guide — Biology", "localPath": "content/official/raw/esat/ESAT_Guide_Biology_June_2025.pdf", "sha256": "cd5fd84f56ef0e55722841fcbdacb86eec15b0eddd16a05ea56c5d902d9e125b", "usedForEn": "Used to verify Biology scope and terminology only.", "usedForZh": "仅用于核验 Biology 范围与术语。" }
  ]
}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();

insert into public.access_packages (id, name, description, status)
values (
  'tara-deep-review',
  'TARA Advanced Review · TARA 深度复习',
  'Private English-first reasoning and writing playbooks, worked cases and training prescriptions with concise Chinese learning support.',
  'active'
)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    status = excluded.status;

insert into public.content_resources (
  id,
  exam,
  kind,
  title,
  access_tier,
  publication_status,
  revision,
  metadata,
  published_at
) values (
  'tara-advanced-notes-v1',
  'TARA',
  'review_notes',
  'TARA Advanced Review Notes · TARA 深度复习笔记',
  'entitled',
  'published',
  1,
  '{"delivery":"server-structured-native-page","contentSchema":"advanced-review-notes","schemaVersion":1,"edition":"2026.07-v1","moduleCount":4,"languagePolicy":"english-first-zh-support"}'::jsonb,
  '2026-07-26T15:00:00Z'::timestamptz
)
on conflict (id) do update
set exam = excluded.exam,
    kind = excluded.kind,
    title = excluded.title,
    access_tier = excluded.access_tier,
    publication_status = excluded.publication_status,
    revision = excluded.revision,
    metadata = excluded.metadata,
    published_at = excluded.published_at,
    updated_at = now();

insert into public.access_package_resources (package_id, resource_id)
values ('tara-deep-review', 'tara-advanced-notes-v1')
on conflict do nothing;

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  'tara-advanced-notes-v1',
  1,
  'e5e822e578a65c96977ccbacf9c21f41ff96810484d37b5b89d0f0a912e54a9e',
  $payload$
{
  "schemaVersion": 1,
  "id": "tara-advanced-notes-v1",
  "examId": "tara",
  "edition": "2026.07-v1",
  "publicationStatus": "published",
  "titleEn": "TARA Advanced Reasoning & Writing Notes",
  "titleZh": "TARA 深度推理与写作笔记",
  "subtitleEn": "A practical system for reconstructing arguments, controlling constraints and writing a defensible response under time pressure.",
  "subtitleZh": "在限时环境下重建论证、控制约束并写出可辩护回应的完整方法。",
  "authorshipEn": "Original teaching material by Mantou",
  "authorshipZh": "满托教研原创",
  "audienceEn": "For students who have completed the foundation notes and begun timed Critical Thinking, Problem Solving and Writing practice.",
  "audienceZh": "适合已完成基础笔记，并已开始 Critical Thinking、Problem Solving 与 Writing 限时练习的学生。",
  "rightsNoticeEn": "Independently authored from verified scope and terminology. No official question, example or explanation is reproduced.",
  "rightsNoticeZh": "依据已核验范围与术语独立撰写，不复制官方题目、例题或讲解。",
  "modules": [
    {
      "id": "tara-critical-thinking",
      "number": "01",
      "titleEn": "Critical Thinking — Reconstruct the Argument",
      "titleZh": "Critical Thinking：重建论证",
      "purposeEn": "Separate conclusion, evidence, assumption and qualifier before judging whether an argument succeeds.",
      "purposeZh": "在判断论证是否成立前，先分离结论、证据、假设与限定词。",
      "knowledgeFocusEn": ["Conclusions, reasons and intermediate conclusions", "Assumptions, flaws and alternative explanations", "Strengthening, weakening and drawing conclusions"],
      "knowledgeFocusZh": ["结论、理由与中间结论", "假设、漏洞与替代解释", "加强、削弱与推出结论"],
      "playbooks": [
        {
          "titleEn": "Build a one-line argument map",
          "titleZh": "建立一行论证图",
          "triggerEn": "The passage contains several facts but the author's main claim is not explicit.",
          "triggerZh": "材料包含多个事实，但作者主张并不直接。",
          "actionEn": "Write evidence→therefore→conclusion in one line. Treat every unused sentence as context until it earns a role.",
          "actionZh": "用一行写成“证据→因此→结论”；尚未发挥作用的句子先视为背景。",
          "checkEn": "The conclusion must be what the author wants accepted, not merely the final sentence.",
          "checkZh": "结论必须是作者希望读者接受的主张，而不一定是最后一句。"
        },
        {
          "titleEn": "Audit the missing bridge",
          "titleZh": "审查缺失桥梁",
          "triggerEn": "The evidence and conclusion discuss different groups, time periods, measures or causal directions.",
          "triggerZh": "证据与结论涉及不同群体、时间、指标或因果方向。",
          "actionEn": "State the smallest claim that must be true for the evidence to support the conclusion, then test options against that exact bridge.",
          "actionZh": "写出证据支持结论所必需的最小命题，再用它精确检验选项。",
          "checkEn": "A necessary assumption need not prove the conclusion; it only prevents the stated route from collapsing.",
          "checkZh": "必要假设不必证明结论，只需防止当前推理路径失效。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — correlation is not the missing bridge",
        "titleZh": "深度案例：相关性不是缺失桥梁",
        "promptEn": "A school introduced optional morning study. Participants later received higher grades than non-participants. The head claims the programme caused the improvement. What assumption is required?",
        "promptZh": "某校推出自愿晨间学习，参加者之后成绩高于未参加者。校长认为项目导致了提升。该论证需要什么假设？",
        "steps": [
          { "labelEn": "Map the claim", "labelZh": "画出主张", "bodyEn": "Evidence: participants had higher later grades. Conclusion: the programme caused the difference.", "bodyZh": "证据：参加者后续成绩更高；结论：项目导致了差异。" },
          { "labelEn": "Find the gap", "labelZh": "寻找缺口", "bodyEn": "Self-selection may explain the result: more motivated or initially stronger pupils may have chosen to participate.", "bodyZh": "自我选择可能解释结果：更有动力或起点更高的学生可能更愿参加。" },
          { "labelEn": "State the necessary bridge", "labelZh": "写出必要桥梁", "bodyEn": "The groups must not differ in a way that independently explains the grade difference, or that difference must be controlled.", "bodyZh": "两组不能存在足以独立解释成绩差异的系统差别，或这些差别已被控制。" }
        ],
        "answerEn": "The argument assumes that pre-existing differences between participants and non-participants do not account for the later grade gap.",
        "answerZh": "论证假设参加者与未参加者的既有差异不足以解释后续成绩差距。",
        "trapEn": "Choosing the stronger claim that every participant benefited; the conclusion needs causal comparability, not universal benefit.",
        "trapZh": "误选“每位参加者都受益”这种更强主张；结论需要的是因果可比性，而非普遍受益。"
      },
      "trainingPrescriptionEn": ["Map 15 passages as evidence→bridge→conclusion before answering options.", "Classify every error as conclusion, assumption, qualifier or option strength.", "Repeat five errors after 48 hours with the option order hidden."],
      "trainingPrescriptionZh": ["完成 15 篇材料的“证据→桥梁→结论”映射后再看选项。", "把每个错误归为结论、假设、限定词或选项强度。", "48 小时后隐藏选项顺序回做 5 道错题。"]
    },
    {
      "id": "tara-problem-solving",
      "number": "02",
      "titleEn": "Problem Solving — Control the Constraints",
      "titleZh": "Problem Solving：控制约束",
      "purposeEn": "Replace verbal complexity with a compact representation that preserves every relevant constraint.",
      "purposeZh": "把复杂文字转为紧凑表示，同时保留所有相关约束。",
      "knowledgeFocusEn": ["Relevant selection and representation", "Finding procedures, schedules and feasible orders", "Identifying similarity, invariants and decisive counterexamples"],
      "knowledgeFocusZh": ["相关信息选择与表示", "程序、排程与可行顺序", "相似性、不变量与决定性反例"],
      "playbooks": [
        {
          "titleEn": "Externalise the constraints",
          "titleZh": "把约束写到纸上",
          "triggerEn": "The question contains ordering, allocation, adjacency, capacity or if-then rules.",
          "triggerZh": "题目包含顺序、分配、相邻、容量或如果—那么规则。",
          "actionEn": "Create slots, a table or a graph; encode fixed placements first, then prohibitions, then conditional rules.",
          "actionZh": "建立槽位、表格或图；先写固定位置，再写禁止条件，最后写条件规则。",
          "checkEn": "Test a proposed arrangement against every original rule, not only the rule used to construct it.",
          "checkZh": "候选安排必须回到全部原始规则逐项核验，不能只检验用于构造的规则。"
        },
        {
          "titleEn": "Search for the bottleneck",
          "titleZh": "寻找瓶颈约束",
          "triggerEn": "Brute-force enumeration is possible but too slow for the remaining time.",
          "triggerZh": "穷举虽然可行，但在剩余时间内太慢。",
          "actionEn": "Start with the item that has the fewest legal positions or the constraint that removes the most possibilities.",
          "actionZh": "先处理合法位置最少的项目，或一次排除最多可能性的约束。",
          "checkEn": "If two branches remain, seek one decisive counterexample rather than completing both tables.",
          "checkZh": "若只剩两条分支，优先寻找决定性反例，而非填完两张表。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — schedule from a bottleneck",
        "titleZh": "深度案例：从瓶颈约束开始排程",
        "promptEn": "Four talks A, B, C and D occupy slots 1–4. A is before C; B is not adjacent to C; D is in slot 2. Which talk must be in slot 4?",
        "promptZh": "讲座 A、B、C、D 安排在 1–4 时段。A 在 C 前；B 不与 C 相邻；D 在时段 2。哪个讲座必须在时段 4？",
        "steps": [
          { "labelEn": "Place the fixed item", "labelZh": "放置固定项目", "bodyEn": "D occupies slot 2, leaving slots 1, 3 and 4 for A, B and C.", "bodyZh": "D 在时段 2，A、B、C 只能位于 1、3、4。" },
          { "labelEn": "Use the adjacency bottleneck", "labelZh": "使用相邻瓶颈", "bodyEn": "If C were in slot 3, B could be neither 2 nor 4 and would need slot 1; then A could not be before C because slot 1 is taken. So C is not 3.", "bodyZh": "若 C 在 3，B 不能在 2 或 4，只能在 1；此时 A 无法位于 C 前。因此 C 不在 3。" },
          { "labelEn": "Apply the order", "labelZh": "应用顺序", "bodyEn": "C cannot be slot 1 because A must be earlier, and cannot be slot 2 because D is fixed. Therefore C must be slot 4.", "bodyZh": "C 不能在 1（A 必须更早），也不能在 2（D 已固定），所以 C 必须在 4。" }
        ],
        "answerEn": "C must be in slot 4.",
        "answerZh": "C 必须位于时段 4。",
        "trapEn": "Trying arbitrary complete schedules before exploiting the fixed slot and the restricted adjacency.",
        "trapZh": "未利用固定时段和相邻限制，就开始随意穷举完整排程。"
      },
      "trainingPrescriptionEn": ["Represent ten constraint questions without solving them; score only representation accuracy.", "For the next ten, identify the bottleneck before branching.", "Track whether time was lost in reading, representation or verification."],
      "trainingPrescriptionZh": ["完成 10 道约束题，只建立表示而不求解，并只评分表示准确性。", "再做 10 道题，每题分支前先指出瓶颈。", "记录时间损失发生在阅读、表示还是核验。"]
    },
    {
      "id": "tara-writing-task",
      "number": "03",
      "titleEn": "Writing Task — Build a Defensible Position",
      "titleZh": "Writing Task：建立可辩护立场",
      "purposeEn": "Produce a clear, qualified argument that answers the prompt, uses reasons economically and survives a serious objection.",
      "purposeZh": "写出直接回应题目、理由经济、能承受严肃反驳的清晰限定论证。",
      "knowledgeFocusEn": ["Interpreting the exact task and defining terms", "Thesis, reasons, examples and paragraph function", "Counterargument, qualification and concise revision"],
      "knowledgeFocusZh": ["精确解释任务与定义术语", "论点、理由、例证与段落功能", "反方、限定与简洁修改"],
      "playbooks": [
        {
          "titleEn": "Write the thesis as a decision rule",
          "titleZh": "把论点写成决策规则",
          "triggerEn": "The prompt asks whether, when or to what extent a policy or principle is justified.",
          "triggerZh": "题目询问某政策或原则是否、何时或在多大程度上合理。",
          "actionEn": "State your position, the condition under which it holds and the criterion used to judge exceptions.",
          "actionZh": "写出立场、立场成立的条件以及判断例外的标准。",
          "checkEn": "A reader should be able to predict how your thesis handles a new case.",
          "checkZh": "读者应能用你的论点判断一个新案例。"
        },
        {
          "titleEn": "Use the strongest objection",
          "titleZh": "处理最强反驳",
          "triggerEn": "The draft contains two supporting paragraphs but no pressure test of the central principle.",
          "triggerZh": "草稿已有两个支持段落，却没有检验中心原则的压力。",
          "actionEn": "Present the most reasonable opposing concern, concede what is true, then refine the thesis rather than dismissing the objection.",
          "actionZh": "呈现最合理的反方顾虑，承认其中成立部分，再通过限定论点回应，而非直接否定。",
          "checkEn": "The response must change or sharpen the original thesis; otherwise the counterargument is decorative.",
          "checkZh": "回应必须改变或收紧原论点，否则反方段落只是装饰。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — qualifying a public-interest claim",
        "titleZh": "深度案例：限定公共利益主张",
        "promptEn": "Should universities be permitted to restrict controversial speakers? Draft a defensible thesis and paragraph plan.",
        "promptZh": "大学是否应被允许限制有争议的演讲者？写出可辩护论点与段落计划。",
        "steps": [
          { "labelEn": "Define the decision", "labelZh": "定义决策", "bodyEn": "Separate disagreement with a view from a credible, specific threat to safety or lawful participation.", "bodyZh": "区分对观点的反感与对安全或合法参与的具体可信威胁。" },
          { "labelEn": "State a qualified thesis", "labelZh": "写限定论点", "bodyEn": "Universities should protect expression by default, restricting a speaker only when proportionate measures cannot manage a specific risk to safety or equal participation.", "bodyZh": "大学原则上应保护表达；只有在比例适当的替代措施无法控制对安全或平等参与的具体风险时，才应限制演讲者。" },
          { "labelEn": "Assign paragraph jobs", "labelZh": "分配段落任务", "bodyEn": "Explain the value of open inquiry; define the narrow exception; test it against the objection that institutions also owe a duty of care; conclude with procedural safeguards.", "bodyZh": "说明开放探究价值；界定狭窄例外；回应大学负有照顾义务的反驳；以程序保障收束。" }
        ],
        "answerEn": "The plan answers the exact decision, supplies a usable threshold and gives the counterargument a real role in refining the position.",
        "answerZh": "该计划直接回答决策、给出可执行门槛，并让反方真正收紧原立场。",
        "trapEn": "Writing ‘free speech is important but safety matters’ without defining how a university decides between them.",
        "trapZh": "只写“言论自由重要，但安全也重要”，却没有定义大学如何在两者之间作出判断。"
      },
      "trainingPrescriptionEn": ["Draft five thesis-as-decision-rule statements in ten minutes each.", "Write paragraph jobs before prose for three full responses.", "Revise one response by removing 15% of words without losing a reasoning step."],
      "trainingPrescriptionZh": ["完成 5 个“决策规则式论点”，每个限时 10 分钟。", "三篇完整回应都先写段落任务，再写正文。", "修改一篇文章，在不丢失推理步骤的前提下删去 15% 字数。"]
    },
    {
      "id": "tara-language-bridge",
      "number": "04",
      "titleEn": "Language Bridge — Precise English for Reasoning",
      "titleZh": "语言桥接：推理所需的精确英文",
      "purposeEn": "Use English qualifiers and logical verbs precisely so that language does not change the strength or direction of reasoning.",
      "purposeZh": "准确使用英文限定词与逻辑动词，避免语言改变推理强度或方向。",
      "knowledgeFocusEn": ["Necessary, sufficient, only, unless and except", "Some, most, all, may, likely and must", "Concise analytical verbs and paragraph transitions"],
      "knowledgeFocusZh": ["necessary、sufficient、only、unless 与 except", "some、most、all、may、likely 与 must", "简洁分析动词与段落衔接"],
      "playbooks": [
        {
          "titleEn": "Preserve logical strength",
          "titleZh": "保留逻辑强度",
          "triggerEn": "An option changes may to must, some to all, or an observed association to a cause.",
          "triggerZh": "选项把 may 改成 must、some 改成 all，或把观察相关改成因果。",
          "actionEn": "Underline the quantifier or modal verb in the stem and require the option to stay at or below the supported strength.",
          "actionZh": "划出题干中的量词或情态动词，要求选项强度不得超过证据支持范围。",
          "checkEn": "Ask whether one counterexample would defeat the wording; if so, the claim may be too strong.",
          "checkZh": "问一个反例能否推翻该表述；若能，主张可能过强。"
        },
        {
          "titleEn": "Choose analytical verbs",
          "titleZh": "选择分析动词",
          "triggerEn": "A sentence relies on vague phrases such as ‘talks about’, ‘is good’ or ‘has an effect’.",
          "triggerZh": "句子依赖 talks about、is good、has an effect 等模糊表达。",
          "actionEn": "Replace them with identifies, assumes, distinguishes, predicts, limits, supports or contradicts, according to the actual reasoning job.",
          "actionZh": "按实际推理功能替换为 identifies、assumes、distinguishes、predicts、limits、supports 或 contradicts。",
          "checkEn": "The verb should reveal the relationship between sentences, not merely restate their topic.",
          "checkZh": "动词应揭示句子间关系，而非只重复主题。"
        }
      ],
      "workedCase": {
        "titleEn": "Worked case — reduce an absolute claim",
        "titleZh": "深度案例：降低绝对主张强度",
        "promptEn": "Rewrite ‘Online learning always makes students less engaged’ as a claim that evidence could realistically support.",
        "promptZh": "把“线上学习总会让学生参与度更低”改写为证据现实可支持的主张。",
        "steps": [
          { "labelEn": "Locate the overclaim", "labelZh": "定位过强之处", "bodyEn": "Always asserts a universal effect across students, subjects, designs and contexts.", "bodyZh": "Always 对所有学生、学科、设计与情境都作出普遍断言。" },
          { "labelEn": "Specify the measure", "labelZh": "明确测量指标", "bodyEn": "Replace the vague word engaged with a measurable outcome such as attendance, contribution frequency or task completion.", "bodyZh": "把模糊的 engaged 改为出勤、发言频率或任务完成率等可测量结果。" },
          { "labelEn": "Write the qualified claim", "labelZh": "写限定主张", "bodyEn": "In courses with little live interaction, online delivery may reduce the frequency of voluntary student contributions compared with otherwise similar in-person classes.", "bodyZh": "在实时互动较少的课程中，与其他条件相似的线下课堂相比，线上授课可能降低学生自愿发言频率。" }
        ],
        "answerEn": "The revised claim identifies a context, a comparison, a measurable outcome and an appropriately cautious strength.",
        "answerZh": "修改后的主张包含情境、比较对象、可测指标与恰当谨慎的强度。",
        "trapEn": "Replacing always with often but leaving engagement undefined and the comparison uncontrolled.",
        "trapZh": "只把 always 换成 often，却仍未定义参与度，也未控制比较条件。"
      },
      "trainingPrescriptionEn": ["Build a qualifier ladder from possible to certain and from some to all.", "Rewrite ten overstrong claims with a context, measure and comparison.", "Edit one essay solely for analytical verbs and logical transitions."],
      "trainingPrescriptionZh": ["建立从 possible 到 certain、从 some 到 all 的强度阶梯。", "把 10 个过强主张改写为包含情境、指标和比较的句子。", "只针对分析动词与逻辑衔接修改一篇文章。"]
    }
  ],
  "reviewProtocol": [
    { "stepEn": "Attempt", "stepZh": "独立作答", "actionEn": "Complete a timed set or draft before reading the relevant module.", "actionZh": "阅读对应模块前，先完成限时题组或写作草稿。" },
    { "stepEn": "Reconstruct", "stepZh": "重建过程", "actionEn": "Write the argument map, constraint representation or paragraph jobs from memory.", "actionZh": "凭记忆写出论证图、约束表示或段落任务。" },
    { "stepEn": "Diagnose", "stepZh": "诊断首错", "actionEn": "Identify the first failure in interpretation, representation, logic, language or timing.", "actionZh": "定位解释、表示、逻辑、语言或节奏中的第一次失败。" },
    { "stepEn": "Transfer", "stepZh": "迁移验证", "actionEn": "Apply one playbook to a different passage, problem or prompt after 24–48 hours.", "actionZh": "24–48 小时后，把一个策略应用到不同材料、问题或题目。" }
  ],
  "sourceAnchors": [
    { "title": "TARA Content Specification", "localPath": "content/official/raw/shared/TARA_Content_Specification.pdf", "sha256": "d326e78305aefd999c42953de3024d403f27357ecbc0f3dd562134e8105822cd", "usedForEn": "Used to verify module structure, timing, writing limit, tool restrictions and scoring boundaries.", "usedForZh": "用于核验模块结构、时间、写作字数、工具限制与计分边界。" },
    { "title": "TARA Question Guide", "localPath": "content/official/raw/shared/TARA_Question_Guide.pdf", "sha256": "afcee1ff9dd35025000cd7c5a4cef804fa31fb3e8870d5748ec8d3ac2c45a6cb", "usedForEn": "Used to verify the named reasoning skills, writing-task structure and mathematics appendix scope.", "usedForZh": "用于核验推理能力名称、写作任务结构与数学附录范围。" }
  ]
}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();
