-- Generated by scripts/build-tmua-six-week-plan-migration.ts.
-- Edit content/notes/tmua/six-week-review-plan-v1.json, then rerun pnpm content:build-tmua-six-week-plan.

update public.access_packages
set name = 'TMUA Six-Week Plan · TMUA 六周计划',
    description = 'A private English-first training plan with Chinese learning support, released only to entitled students.'
where id = 'tmua-full-access';

update public.content_resources
set title = 'TMUA Six-Week Precision Training Plan · TMUA 六周精确训练计划',
    revision = 2,
    metadata = '{"delivery":"server-structured-native-page","contentSchema":"tmua-six-week-review-plan","schemaVersion":2,"edition":"2026.07-v1","languagePolicy":"english-first-zh-support"}'::jsonb,
    published_at = '2026-07-26T14:00:00Z'::timestamptz
where id = 'tmua-six-week-review-plan-v1';

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  'tmua-six-week-review-plan-v1',
  2,
  '4f727b10e93a96e5fef3821476a9c1bd2c115738a6d055f6bcdf1c068c415088',
  $payload$
{
  "schemaVersion": 2,
  "id": "tmua-six-week-review-plan-v1",
  "edition": "2026.07-v1",
  "publicationStatus": "published",
  "titleZh": "TMUA 六周精确训练计划",
  "titleEn": "TMUA Six-Week Precision Training Plan",
  "subtitleZh": "从课程缺口、限时训练到整卷复盘，每次学习都留下可检查的结果",
  "subtitleEn": "Turn curriculum gaps, timed practice and paper review into evidence",
  "authorship": "满托教研原创",
  "audienceEn": "For A-Level, IB or AP students who have completed their curriculum profile and are ready to begin systematic preparation.",
  "audienceZh": "适用于已经完成课程信息填写，并准备开始系统训练的 A-Level、IB 或 AP 学生。",
  "rightsNoticeEn": "Independently written by Mantou. The schedule uses the verified TMUA structure on this site but reproduces no official questions or third-party explanations.",
  "rightsNotice": "本资料由满托教研原创编写。训练安排引用本站已核验的 TMUA 考试结构，但不复制官方题目或第三方解析。",
  "principles": [
    {
      "titleZh": "先补最小缺口",
      "titleEn": "Close the smallest gap first",
      "bodyEn": "When a knowledge unit is missing, learn only enough to begin purposeful practice; do not restart an entire course.",
      "bodyZh": "不会一个知识单元时，只补到能够开始做题；不要把整门课程重新学一遍。"
    },
    {
      "titleZh": "先记录第一处错误",
      "titleEn": "Record the first failure",
      "bodyEn": "During review, record the first point at which your answer diverged. Copying a complete solution creates notes without a next action.",
      "bodyZh": "复盘时只记录导致答案偏离的第一处错误，避免把完整答案抄成一页没有行动意义的笔记。"
    },
    {
      "titleZh": "真题用于校准，不用于消耗",
      "titleEn": "Use papers to calibrate",
      "bodyEn": "Start another full paper only after topic repair and error rework. A paper that has not been reviewed does not count as effective training.",
      "bodyZh": "只有在完成主题训练和错题回做后才进入下一套整卷；未复盘的整卷不计入有效训练。"
    },
    {
      "titleZh": "结论只来自你的证据",
      "titleEn": "Conclusions follow your evidence",
      "bodyEn": "Do not infer mastery from a course label, and do not turn a small sample into an admission probability or a false-precision percentile.",
      "bodyZh": "计划不根据课程名称推断你已经会做题，也不把少量样本包装成录取概率或伪精确百分位。"
    }
  ],
  "preflight": {
    "titleZh": "开始前的 45 分钟",
    "titleEn": "Your First 45 Minutes",
    "steps": [
      {
        "minutes": 5,
        "actionEn": "Confirm your curriculum profile",
        "actionZh": "确认课程信息",
        "detailEn": "Check the exam board, subjects and completed units on the knowledge-coverage page. A topic appearing in your course does not prove mastery.",
        "detailZh": "在知识覆盖页核对考试局、科目和已经学完的模块。课程里出现过，不等于你已经掌握。",
        "evidenceEn": "an up-to-date curriculum profile",
        "evidenceZh": "保存一份最新课程档案"
      },
      {
        "minutes": 30,
        "actionEn": "Complete the diagnostic",
        "actionZh": "完成能力诊断",
        "detailEn": "Work at your normal pace without notes. Flag hesitation so the system can preserve active time and answer changes for each question.",
        "detailZh": "按正常节奏作答，不查资料；对犹豫题做标记，让系统保留每题活跃时间和改答记录。",
        "evidenceEn": "one complete diagnostic session",
        "evidenceZh": "一次完整诊断会话"
      },
      {
        "minutes": 10,
        "actionEn": "Build your first training list",
        "actionZh": "建立第一份训练清单",
        "detailEn": "Classify errors as knowledge, route, execution, decoding or timing. Take only the two most frequent problems into Week 1.",
        "detailZh": "把错题分为知识、路径、执行、读题和节奏五类，只挑最高频的两个问题进入第一周。",
        "evidenceEn": "two priority problems, each with a next action",
        "evidenceZh": "两个优先问题与各自下一步"
      }
    ]
  },
  "weeklyPlan": [
    {
      "week": 1,
      "titleZh": "精确运算与代数底座",
      "titleEn": "Exact Arithmetic and Algebra",
      "purposeEn": "Eliminate recurring errors in surds, fractions, factorisation, equations and domains before they contaminate later topics.",
      "purposeZh": "先消除会反复污染后续主题的根式、分式、因式分解、方程与定义域错误。",
      "targetHoursEn": "4–5 hours",
      "targetHours": "4–5 小时",
      "sessions": [
        { "day": "01", "minutes": 45, "titleEn": "Repeat diagnostic errors", "titleZh": "诊断错题再做", "actionsEn": ["Redo this week's priority errors without looking at answers.", "Mark the first point where your original and second approaches differ.", "Assign one error code to every question."], "actionsZh": ["不看答案重做本周优先错题", "标出第一次与第二次解法不同的位置", "为每题写一个错误代码"], "evidenceEn": "at least five classified questions", "evidenceZh": "至少 5 道已分类题" },
        { "day": "02", "minutes": 60, "titleEn": "Surds, fractions and exact values", "titleZh": "根式、分式与精确值", "actionsEn": ["Preserve useful factors and conjugate structures.", "Write excluded values before every cancellation.", "Estimate only when it safely resolves a comparison."], "actionsZh": ["练习保留因式和共轭结构", "每次约分前写排除值", "只在比较大小时进行安全估算"], "evidenceEn": "a one-page domain and exact-value checklist", "evidenceZh": "一页定义域与精确值检查表" },
        { "day": "03", "minutes": 60, "titleEn": "Equations, inequalities and parameters", "titleZh": "方程、不等式与参数", "actionsEn": ["Distinguish equivalent transformations from one-way implications.", "Substitute back after squaring.", "Translate the number of roots into a discriminant condition."], "actionsZh": ["区分等价变形与单向推导", "平方后代回原式", "把根的数量翻译成判别式条件"], "evidenceEn": "ten topic questions with the first error recorded", "evidenceZh": "10 道主题题，记录首错" },
        { "day": "04", "minutes": 45, "titleEn": "Non-calculator speed sets", "titleZh": "无计算器速度组", "actionsEn": ["Complete two short sets consecutively.", "Write an executable first step for every question.", "Flag and leave a question when it exceeds its planned time."], "actionsZh": ["连续完成两组短题", "每题先写可执行的第一步", "超过计划时间先标记再继续"], "evidenceEn": "accuracy for both sets and the numbers of overrun questions", "evidenceZh": "两组正确率与超时题号" },
        { "day": "05", "minutes": 60, "titleEn": "Weekly check and spaced repeat", "titleZh": "周检与回做", "actionsEn": ["Repeat every error after an interval of at least 24 hours.", "Reclassify any question that is still wrong.", "Carry forward only problems that still need tracking."], "actionsZh": ["间隔至少 24 小时回做所有错题", "仍错的题重新归类", "只保留下一周仍需追踪的问题"], "evidenceEn": "a first-attempt versus repeat record", "evidenceZh": "首做与回做对照记录" }
      ],
      "exitCriteriaEn": ["Write domain and denominator restrictions before transforming an expression.", "Reach at least 80% accuracy when repeating questions of the same type.", "Ensure execution errors are no longer the week's most frequent error."],
      "exitCriteriaZh": ["能在变形前主动写出定义域和分母限制", "同类题回做正确率达到 80% 以上", "执行错误不再是本周最高频错误"]
    },
    {
      "week": 2,
      "titleZh": "函数、图像与坐标几何",
      "titleEn": "Functions, Graphs and Coordinate Geometry",
      "purposeEn": "Connect algebraic expressions, transformations, intersections and geometric conditions as one language, so structure guides the calculation.",
      "purposeZh": "把代数式、函数变换、交点和几何条件连成同一种语言，减少只会计算却看不出结构的问题。",
      "targetHoursEn": "4–5 hours",
      "targetHours": "4–5 小时",
      "sessions": [
        { "day": "01", "minutes": 45, "titleEn": "Function language audit", "titleZh": "函数语言检查", "actionsEn": ["Review domain, range, inverse and composite functions.", "Describe every transformation algebraically and graphically.", "Check the one-to-one condition."], "actionsZh": ["复习 domain、range、inverse 与 composite", "为每个变换同时写代数和图像解释", "检查一对一条件"], "evidenceEn": "bilingual function-language cards", "evidenceZh": "函数术语双语卡片" },
        { "day": "02", "minutes": 60, "titleEn": "Transformations and intersections", "titleZh": "图像变换与交点", "actionsEn": ["Predict the number of intersections before forming an equation.", "Distinguish f(x-a) from f(x)-a.", "Use endpoints, symmetry and monotonicity to eliminate options."], "actionsZh": ["先预测交点数量再列方程", "区分 f(x-a) 与 f(x)-a", "用端点、对称和单调性排除选项"], "evidenceEn": "eight graph questions with predictions", "evidenceZh": "8 道图像题与预测记录" },
        { "day": "03", "minutes": 60, "titleEn": "Lines, circles and distance", "titleZh": "直线、圆与距离", "actionsEn": ["Translate perpendicular, tangent and equidistant conditions into equations.", "Audit the circle-theorem supporting knowledge.", "Avoid expanding coordinate expressions prematurely."], "actionsZh": ["把垂直、相切和等距条件写成方程", "复核圆定理 supporting knowledge", "避免过早展开坐标式"], "evidenceEn": "a map from geometric conditions to algebraic statements", "evidenceZh": "一张几何条件到代数式的映射表" },
        { "day": "04", "minutes": 45, "titleEn": "Mixed timed set", "titleZh": "混合限时组", "actionsEn": ["Complete a mixed set on functions and coordinates.", "Flag questions for which no first step appears after reading.", "Add one trigger signal for every route gap."], "actionsZh": ["完成函数与坐标混合题", "标记读完后没有第一步的题", "对路径缺口补一条触发信号"], "evidenceEn": "a route-gap list", "evidenceZh": "路径缺口清单" },
        { "day": "05", "minutes": 60, "titleEn": "Weekly check and blind transfer", "titleZh": "周检与盲做", "actionsEn": ["Draw old questions at random from the previous two weeks.", "Work without topic labels.", "Compare within-topic accuracy with mixed-set accuracy."], "actionsZh": ["随机抽取上两周旧题", "不按主题提示作答", "比较主题内正确率与混合正确率"], "evidenceEn": "the mixed-transfer gap", "evidenceZh": "混合迁移差距" }
      ],
      "exitCriteriaEn": ["Write f(x)=g(x) first when a question asks about intersections.", "Explain the four basic graph transformations accurately.", "Choose methods in mixed sets without relying on topic headings."],
      "exitCriteriaZh": ["看到交点问题会先写 f(x)=g(x)", "能准确解释四类基本图像变换", "混合题中不再依赖主题标题寻找方法"]
    },
    {
      "week": 3,
      "titleZh": "数列、三角、指数对数与微积分",
      "titleEn": "Sequences, Trigonometry, Logs and Calculus",
      "purposeEn": "Audit the topics whose timing varies most across curricula, then learn from evidence of a gap rather than assumptions about a course label.",
      "purposeZh": "把课程体系之间最容易出现进度差异的内容逐项核实，按缺口补学而不是按课程名称猜测。",
      "targetHoursEn": "5–6 hours",
      "targetHours": "5–6 小时",
      "sessions": [
        { "day": "01", "minutes": 60, "titleEn": "Sequences and recurrence", "titleZh": "数列与递推", "actionsEn": ["Distinguish arithmetic, geometric and recursive definitions.", "Check the conditions for finite and infinite sums.", "Verify a general term against the first few terms."], "actionsZh": ["区分 arithmetic、geometric 与递推定义", "检查有限和与无穷和的适用条件", "用前几项验证通项"], "evidenceEn": "a sequence-conditions checklist", "evidenceZh": "数列条件检查表" },
        { "day": "02", "minutes": 60, "titleEn": "Trigonometry and exact values", "titleZh": "三角与精确值", "actionsEn": ["Recover common exact values without a calculator.", "Use period and quadrant to check solution sets.", "Check the valid scope of an identity before applying it."], "actionsZh": ["脱离计算器恢复常用精确值", "用周期和象限检查解集", "先判断恒等式适用范围"], "evidenceEn": "an exact-value blind-test result", "evidenceZh": "精确值盲测结果" },
        { "day": "03", "minutes": 60, "titleEn": "Exponentials and logarithms", "titleZh": "指数与对数", "actionsEn": ["State base and argument conditions first.", "Inspect monotonicity before substituting.", "Use order of magnitude to check options."], "actionsZh": ["先写底数与真数条件", "在代换前观察单调性", "用数量级检查选项"], "evidenceEn": "eight fully conditioned solutions", "evidenceZh": "8 道条件完整的解题记录" },
        { "day": "04", "minutes": 75, "titleEn": "Calculus and graph modelling", "titleZh": "微积分与图像建模", "actionsEn": ["Translate the sign of a derivative into increase, decrease and extrema.", "Distinguish instantaneous from average rate of change.", "Use signed area to test an integral conclusion."], "actionsZh": ["把导数符号翻译成增减和极值", "区分瞬时变化率与平均变化率", "用面积符号检查积分结论"], "evidenceEn": "one derivative–graph–equation relationship map", "evidenceZh": "一张导数—图像—方程关系图" },
        { "day": "05", "minutes": 75, "titleEn": "Curriculum gap review", "titleZh": "课程缺口复核", "actionsEn": ["Return to the coverage page and confirm each topic.", "Schedule the smallest lesson needed for unstudied content.", "Treat covered-but-wrong content as a practice problem."], "actionsZh": ["回到知识覆盖页逐项确认", "未学内容安排最小补课", "已学但做错内容改为练习问题"], "evidenceEn": "updated learn and revise lists", "evidenceZh": "更新后的补学与复习两张清单" }
      ],
      "exitCriteriaEn": ["Classify every topic this week as covered, not covered or needing confirmation.", "State domain, period and convergence conditions without prompting.", "Use performance evidence rather than a curriculum label to judge mastery."],
      "exitCriteriaZh": ["所有本周主题都能明确归为已学、未学或需要确认", "定义域、周期和收敛条件会主动出现", "没有用课程名称代替实际掌握证据"]
    },
    {
      "week": 4,
      "titleZh": "逻辑、证明与 Paper 2",
      "titleEn": "Logic, Proof and Paper 2",
      "purposeEn": "Stabilise the direction of necessary and sufficient conditions, quantifiers, counterexamples and proof flaws so that language errors are not mistaken for missing mathematics.",
      "purposeZh": "稳定 necessary、sufficient、quantifier、counterexample 与 proof flaw 的方向感，避免把语言错误误判为数学不会。",
      "targetHoursEn": "4–5 hours",
      "targetHours": "4–5 小时",
      "sessions": [
        { "day": "01", "minutes": 60, "titleEn": "Conditional direction", "titleZh": "条件方向", "actionsEn": ["Draw every sufficient and necessary statement as an arrow.", "Distinguish a converse from a contrapositive.", "Write a precise Chinese meaning for each English qualifier."], "actionsZh": ["把 sufficient 和 necessary 全部画成箭头", "区分 converse 与 contrapositive", "为英文限定词写中文精确含义"], "evidenceEn": "a 20-statement blind test on conditional direction", "evidenceZh": "20 条条件方向盲测" },
        { "day": "02", "minutes": 60, "titleEn": "Quantifiers and negation", "titleZh": "量词与否定", "actionsEn": ["Practise negating for all and there exists.", "Check whether the domain of objects has changed.", "Find a valid counterexample to a universal statement."], "actionsZh": ["练习否定 for all 与 there exists", "检查对象范围是否改变", "为全称命题寻找合法反例"], "evidenceEn": "ten rewritten quantified statements", "evidenceZh": "10 条量词改写" },
        { "day": "03", "minutes": 60, "titleEn": "Proof methods", "titleZh": "证明方法", "actionsEn": ["Choose direct proof, cases, contradiction or contrapositive for each prompt.", "Justify every step.", "Flag illegal division and circular reasoning."], "actionsZh": ["为题目选择 direct、cases、contradiction 或 contrapositive", "每步说明依据", "标记非法除法和循环论证"], "evidenceEn": "one problem for each of four proof methods", "evidenceZh": "四种方法各一题" },
        { "day": "04", "minutes": 45, "titleEn": "Timed flaw detection", "titleZh": "辨错限时组", "actionsEn": ["Find the first unjustified step before anything else.", "Distinguish a false conclusion from insufficient reasoning.", "Test a suspicion with a counterexample."], "actionsZh": ["先找第一处不成立的步骤", "区分结论错误与论证不足", "用反例验证怀疑"], "evidenceEn": "the first flaw and its reason for every item", "evidenceZh": "首错位置与原因" },
        { "day": "05", "minutes": 60, "titleEn": "Half Paper 2", "titleZh": "Paper 2 半卷", "actionsEn": ["Complete ten mixed questions in 37 minutes.", "Preserve flags and answer changes.", "Review with the error codebook."], "actionsZh": ["在 37 分钟内完成 10 道混合题", "保留标记与改答记录", "按错误代码复盘"], "evidenceEn": "half-paper timing and error distribution", "evidenceZh": "半卷节奏与错误分布" }
      ],
      "exitCriteriaEn": ["Reach 90% on a blind test of necessary and sufficient direction.", "Refute a universal conclusion with one valid counterexample.", "Make no more than one decoding error in the Paper 2 set."],
      "exitCriteriaZh": ["necessary / sufficient 方向盲测达到 90%", "能用一个合法反例推翻全称结论", "Paper 2 的读题错误不超过一次"]
    },
    {
      "week": 5,
      "titleZh": "整卷节奏与稳定性",
      "titleEn": "Full-Paper Timing and Stability",
      "purposeEn": "Place topic knowledge inside a 75-minute paper for the first time and establish a repeatable strategy for flags, review and answering every question.",
      "purposeZh": "第一次把主题能力放进 75 分钟整卷，建立属于自己的标记、回看与完成全部题目的节奏。",
      "targetHoursEn": "5–6 hours",
      "targetHours": "5–6 小时",
      "sessions": [
        { "day": "01", "minutes": 90, "titleEn": "Full Paper 1", "titleZh": "Paper 1 整卷", "actionsEn": ["Use a strict 75-minute timer.", "On the first pass, answer only questions with a clear route.", "Before time ends, ensure every question has an answer."], "actionsZh": ["严格计时 75 分钟", "第一轮只做路径清晰的题", "最后确认每题已有答案"], "evidenceEn": "a Paper 1 session with question-level timing", "evidenceZh": "Paper 1 会话与题目耗时" },
        { "day": "02", "minutes": 75, "titleEn": "Deep Paper 1 review", "titleZh": "Paper 1 深度复盘", "actionsEn": ["Redo every incorrect or flagged question before viewing explanations.", "Record the first error.", "Schedule every knowledge gap for the next repair session."], "actionsZh": ["不看解析重做所有错题和标记题", "记录第一处错误", "把知识缺口安排到下一次补学"], "evidenceEn": "a three-column first attempt, repeat and explanation record", "evidenceZh": "首做—回做—看解三列记录" },
        { "day": "03", "minutes": 90, "titleEn": "Full Paper 2", "titleZh": "Paper 2 整卷", "actionsEn": ["Use a strict 75-minute timer.", "Circle logical qualifiers.", "Record questions where language direction caused hesitation."], "actionsZh": ["严格计时 75 分钟", "圈出逻辑限定词", "记录因语言方向犹豫的题"], "evidenceEn": "a Paper 2 session with question-level timing", "evidenceZh": "Paper 2 会话与题目耗时" },
        { "day": "04", "minutes": 75, "titleEn": "Deep Paper 2 review", "titleZh": "Paper 2 深度复盘", "actionsEn": ["Separate mathematical knowledge from logical language.", "Write a trigger signal for each route gap.", "Isolate pure execution errors."], "actionsZh": ["区分数学知识与逻辑语言", "为路径缺口写触发信号", "隔离纯执行错误"], "evidenceEn": "the Paper 2 error structure", "evidenceZh": "Paper 2 错误结构" },
        { "day": "05", "minutes": 45, "titleEn": "Stability check", "titleZh": "稳定性检查", "actionsEn": ["Compare performance on the first and last ten questions of both papers.", "Check whether overruns cluster on a few questions.", "Choose only three actions to carry into Week 6."], "actionsZh": ["比较两卷前十题与后十题表现", "检查超时是否集中在少数题", "确定第六周只保留三个动作"], "evidenceEn": "three final improvement actions", "evidenceZh": "三个最终改进动作" }
      ],
      "exitCriteriaEn": ["Submit an answer to every question within time on both papers.", "Identify the three largest time losses and explain their causes.", "Produce specific review actions rather than recording only a score."],
      "exitCriteriaZh": ["两张卷都能在时间内完成全部作答", "能指出时间损失最大的三道题及原因", "复盘输出具体动作而不是只记录分数"]
    },
    {
      "week": 6,
      "titleZh": "模拟、修正与考前收束",
      "titleEn": "Simulation, Correction and Taper",
      "purposeEn": "Use two complete simulations to test stability, then repair only issues that can still affect the result without introducing broad new content.",
      "purposeZh": "用两次完整模拟检验稳定性；最后只修正仍会影响结果的问题，不在考前引入新的大范围内容。",
      "targetHoursEn": "5–7 hours",
      "targetHours": "5–7 小时",
      "sessions": [
        { "day": "01", "minutes": 165, "titleEn": "Complete two-paper simulation", "titleZh": "完整双卷模拟", "actionsEn": ["Complete two 75-minute papers in the official order.", "Take only the planned break between papers.", "Use no notes and never pause the timer."], "actionsZh": ["按正式顺序完成两张 75 分钟试卷", "中间只进行计划内休息", "不查资料、不暂停计时"], "evidenceEn": "one complete two-paper session", "evidenceZh": "双卷完整会话" },
        { "day": "02", "minutes": 90, "titleEn": "Simulation review", "titleZh": "模拟复盘", "actionsEn": ["Repeat independently before viewing the basic result.", "Count all five error types.", "Choose only two problems that can still be repaired."], "actionsZh": ["先独立回做，再查看基础结果", "统计五类错误", "只选择两个仍可修正的问题"], "evidenceEn": "an error distribution and two prescriptions", "evidenceZh": "错误分布与两项处方" },
        { "day": "03", "minutes": 60, "titleEn": "Targeted repair", "titleZh": "定向修正", "actionsEn": ["Complete one targeted set for each selected problem.", "Practise the planned checking action.", "Stop unfocused question volume."], "actionsZh": ["每个问题完成一组针对题", "练习计划中的检查动作", "停止无目的刷题"], "evidenceEn": "two targeted training sets", "evidenceZh": "两组定向训练" },
        { "day": "04", "minutes": 165, "titleEn": "Second complete simulation", "titleZh": "第二次完整模拟", "actionsEn": ["Recreate the formal environment.", "Use the same flagging strategy.", "Check whether each repaired action actually occurred."], "actionsZh": ["复刻正式环境", "执行同一套标记策略", "检查修正动作是否真的发生"], "evidenceEn": "a comparison of both simulations", "evidenceZh": "两次模拟对照" },
        { "day": "05", "minutes": 45, "titleEn": "Pre-test taper", "titleZh": "考前收束", "actionsEn": ["Read your personal error list instead of new material.", "Confirm the test process and required items.", "Stop using new full papers to create noise."], "actionsZh": ["阅读个人错误清单而非新资料", "确认考试流程与所需物品", "停止使用新整卷制造噪音"], "evidenceEn": "a one-page pre-test checklist", "evidenceZh": "一页考前检查单" }
      ],
      "exitCriteriaEn": ["Use the same timing strategy in both simulations.", "Reduce frequent errors or execute the relevant checking actions more consistently.", "Explain the next action without relying on one score for a conclusion."],
      "exitCriteriaZh": ["两次模拟的节奏策略一致", "高频错误数量下降或检查动作更稳定", "能够解释下一步，而不是依赖一次分数下结论"]
    }
  ],
  "errorCodebook": [
    { "code": "K", "nameZh": "知识缺口", "nameEn": "Knowledge gap", "signalEn": "The concept, formula or condition of use is not known.", "signalZh": "概念、公式或适用条件本身不知道。", "nextActionEn": "Learn one minimum knowledge unit, then immediately complete three to five questions of the same type.", "nextActionZh": "补一个最小知识单元，随后立即做 3–5 道同类题。" },
    { "code": "R", "nameZh": "路径缺口", "nameEn": "Route gap", "signalEn": "The knowledge has been covered, but no executable first step appears.", "signalZh": "知识学过，但看到题目没有可执行的第一步。", "nextActionEn": "Record a trigger, the first step and one adjacent variation; do not copy a full-page solution.", "nextActionZh": "记录触发信号、第一步和一个相邻变式；不要抄整页答案。" },
    { "code": "E", "nameZh": "执行错误", "nameEn": "Execution error", "signalEn": "The route is sound, but algebra, sign, range or transcription fails.", "signalZh": "思路正确，但代数、符号、范围或抄写出现错误。", "nextActionEn": "Place a checking action before the vulnerable step and force its use in the next set.", "nextActionZh": "把检查动作放在容易出错的那一步之前，并在下一组题强制执行。" },
    { "code": "D", "nameZh": "读题错误", "nameEn": "Decoding error", "signalEn": "A qualifier such as necessary, at least, integer or except—or the requested quantity—is misread.", "signalZh": "误读 necessary、at least、integer、except 或题目所求。", "nextActionEn": "Circle the qualifier, restate the task in your own words, then answer.", "nextActionZh": "圈定限定词，用自己的话改写题目，再作答。" },
    { "code": "T", "nameZh": "节奏错误", "nameEn": "Timing error", "signalEn": "Too long is spent on one question, leaving later answerable questions untouched.", "signalZh": "在一题停留过久，导致后续能做的题没有时间。", "nextActionEn": "Set a leave signal for questions without a first step; flag the question and move on.", "nextActionZh": "为没有第一步的题设置离开信号，标记后进入下一题。" }
  ],
  "curriculumAdjustments": [
    { "curriculum": "A-Level / IAL Mathematics", "guidanceEn": "If the Pure Mathematics core is complete, shorten repeated teaching in Weeks 1–3 to a knowledge audit. Move the saved time to Paper 2 logic, non-calculator exact arithmetic and mixed timed sets.", "guidanceZh": "若 Pure Mathematics 主干已完成，把第 1–3 周的重复课程学习缩短为知识检查；把释放的时间放在 Paper 2 逻辑、无计算器精确运算和混合限时组。" },
    { "curriculum": "IB Mathematics AA HL", "guidanceEn": "Functions and calculus will usually need an audit rather than full reteaching. Prioritise circle theorems, UK supporting knowledge, formal-logic vocabulary, exact values without a GDC and option discrimination.", "guidanceZh": "函数和微积分通常不需要重学；优先核对圆定理、英国 supporting knowledge、formal logic vocabulary，以及不用 GDC 的精确值和选项辨析。" },
    { "curriculum": "IB Mathematics AA SL / AI HL", "guidanceEn": "Do not skip Week 3. Check sequences, trigonometry, exponentials, logarithms, exact algebra and non-calculator graph reasoning against completed units; learn uncovered material before timing it.", "guidanceZh": "不要跳过第 3 周。根据已完成单元逐项确认数列、三角、指数对数、精确代数与非计算器图像推理，未覆盖内容先补学再计时。" },
    { "curriculum": "AP Precalculus + AP Calculus", "guidanceEn": "Audit Algebra II and Geometry as well. A Calculus score does not demonstrate coverage of surds, exact algebra, circle theorems, finite geometric series or Paper 2 logic.", "guidanceZh": "同时核对 Algebra II 与 Geometry 记录。Calculus 成绩不能证明根式、精确代数、圆定理、有限几何级数和 Paper 2 逻辑已经覆盖。" }
  ],
  "weeklyReview": {
    "titleZh": "每周只回答这六个问题",
    "titleEn": "Six Questions for Every Weekly Review",
    "questionsEn": [
      "How many minutes did you actually train, rather than plan to train?",
      "Which error type appeared most often? Give question-level evidence.",
      "Which question was still wrong on repeat, and where was the first error?",
      "Which topic was not yet taught, and which was merely under-practised?",
      "Which two training actions alone should continue next week?",
      "Do you need a teacher to judge one specific problem rather than asking generally how to improve?"
    ],
    "questionsZh": [
      "本周实际训练了多少分钟，而不是计划了多少？",
      "哪一种错误出现最多？请给出题号证据。",
      "哪一道题在回做时仍然错误？第一处错误在哪里？",
      "哪一个知识点属于未学，哪一个只是做题不熟？",
      "下周只保留哪两个最重要的训练动作？",
      "是否需要老师判断一个具体问题，而不是笼统地问“我该怎么提高”？"
    ]
  },
  "benchmarkBoundary": {
    "titleZh": "怎样理解你的阶段结果",
    "titleEn": "How to Read Your Evidence",
    "bodyEn": "One diagnostic or one paper describes only that question sample and that performance state. Time planning becomes defensible only after two to three weeks of training frequency, topic accuracy, repeat retention, active time per question and error-type movement. This site will not manufacture admission probabilities or false-precision percentiles from inadequate evidence.",
    "bodyZh": "单次诊断和单套试卷只描述当时的题目样本与作答状态。真正可以用来规划时间的，是连续两到三周的训练频率、主题正确率、回做保持率、每题活跃时间和错误类型变化。本站不会在样本不足时给出录取概率或伪精确百分位。"
  }
}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();
