-- Append-only practice revision release generated by scripts/build-published-practice-revisions.ts.
insert into public.practice_content_revisions (paper_revision_id, paper_id, revision, exam, schema_version, content_digest, question_count, duration_minutes, published_at) values
  ('esat-nsaa-2021-mathematics-1-r2', 'esat-nsaa-2021-mathematics-1', 2, 'ESAT', 1, 'b4b7adf208e9164b7d416c0e4018d20d5c9e0d3d3ec7c3738735ba47f4875f49', 20, 30, '2026-07-27T13:10:07.617Z'),
  ('esat-nsaa-2022-mathematics-1-r2', 'esat-nsaa-2022-mathematics-1', 2, 'ESAT', 1, '9618c3d64b4cb36b717a6dd28b9e56066cb284d6f4d1f1f7c3ebb31f99d7ca35', 20, 30, '2026-07-27T13:10:07.617Z'),
  ('esat-nsaa-2023-mathematics-1-r2', 'esat-nsaa-2023-mathematics-1', 2, 'ESAT', 1, '9e35fbd6a23af9e4322e155d00099180b900dd9b241be939e82721ca5dd66d48', 20, 30, '2026-07-27T13:10:07.617Z');
