-- Generated by scripts/build-tmua-specimen-deep-review-migration.ts.
-- Edit content/notes/tmua/specimen-p1-worked-explanations-v1.json, then rerun pnpm content:build-tmua-deep-review.

insert into public.access_packages (id, name, description, status)
values (
  'tmua-deep-review',
  'TMUA 深度解析',
  '已发布试卷的逐题思路、易错点和后续训练建议；题目、答案和基础结果不需要该权限。',
  'active'
)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    status = excluded.status;

insert into public.content_resources (
  id,
  exam,
  kind,
  title,
  access_tier,
  publication_status,
  revision,
  metadata,
  published_at
) values (
  'tmua-specimen-p1-worked-explanations-v1',
  'TMUA',
  'answer_explanation',
  'TMUA Early Specimen Paper 1 逐题深度解析',
  'entitled',
  'published',
  1,
  '{"delivery":"server-structured-native-page","contentSchema":"tmua-worked-explanations","paperId":"tmua-specimen-p1","questionCount":20,"edition":"2026.07-v1"}'::jsonb,
  '2026-07-18T21:30:00Z'::timestamptz
)
on conflict (id) do update
set title = excluded.title,
    access_tier = excluded.access_tier,
    publication_status = excluded.publication_status,
    revision = excluded.revision,
    metadata = excluded.metadata,
    published_at = excluded.published_at;

delete from public.access_package_resources
where package_id = 'tmua-deep-review'
  and resource_id = 'tmua-deep-review-v1';

insert into public.access_package_resources (package_id, resource_id)
values
  ('tmua-deep-review', 'tmua-specimen-p1-worked-explanations-v1'),
  ('tmua-full-access', 'tmua-specimen-p1-worked-explanations-v1')
on conflict do nothing;

insert into public.content_resource_payloads (
  resource_id,
  schema_version,
  source_sha256,
  payload
) values (
  'tmua-specimen-p1-worked-explanations-v1',
  1,
  '25b776e6951dcf79cc7657fc1865df4547fbef5a737fb81eb28ee7e0e4b4233e',
  $payload$
{
  "schemaVersion": 1,
  "id": "tmua-specimen-p1-worked-explanations-v1",
  "paperId": "tmua-specimen-p1",
  "edition": "2026.07-v1",
  "publicationStatus": "published",
  "titleZh": "TMUA Early Specimen Paper 1 逐题深度解析",
  "titleEn": "TMUA Early Specimen Paper 1 Worked Review",
  "subtitleZh": "20 道题的解题路径、关键步骤、易错点与下一步训练",
  "subtitleEn": "Method, reasoning, traps and next drill for all 20 questions",
  "authorship": "满托原创中文教学解读",
  "rightsNotice": "基于已归档官方题面、答案与 worked solutions 独立核验并重写；不得脱离本站批量转载。",
  "sourceEvidence": {
    "questionSha256": "d2e826c828b6102024bddd49b5edb85cedde4b50f116a4e2e3a0b41cf6f04241",
    "answerSha256": "e8b15c8e90f9b9db850d28a1b58a13a0c82fdf03becc58aff15e64c206fc3cca",
    "workedSolutionSha256": "d628203f6777a26dc0459410a598a9d6824f86dd0e62ef9a3ddd8350d0415585",
    "questionPages": [3, 3, 4, 4, 5, 5, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13],
    "auditedAt": "2026-07-18",
    "fidelityStatus": "visually-verified"
  },
  "explanations": [
    {
      "questionId": "tmua-specimen-p1-q01",
      "number": 1,
      "correctAnswer": "D",
      "topicZh": "联立方程与根的和",
      "topicEn": "Simultaneous equations and sum of roots",
      "methodZh": "消元后直接求两组解",
      "methodEn": "Eliminate, solve, then add",
      "keyIdeaZh": "先用一次方程把 x 写成 y 的式子，再代入第二式；题目问的是两个 x 值之和，不要把 y 的和当答案。",
      "steps": [
        { "titleZh": "消元", "bodyZh": "由 x-3y+1=0 得 x=3y-1，代入 3x²-7xy=5。", "math": "3(3y-1)^2-7(3y-1)y=5" },
        { "titleZh": "解二次方程", "bodyZh": "整理为 6y²-11y-2=0=(y-2)(6y+1)，所以 y=2 或 y=-1/6。", "math": "y=2\\quad\\text{or}\\quad y=-\\frac16" },
        { "titleZh": "回代并相加", "bodyZh": "对应 x=5 与 x=-3/2，二者之和为 7/2。", "math": "5-\\frac32=\\frac72=3.5" }
      ],
      "conclusionZh": "选择 D（3.5）。",
      "trapZh": "只用韦达定理算出 y 的根和 11/6 就停下；题目所求变量是 x。",
      "nextDrillZh": "练 3 道“联立方程后只问某个变量根的和/积”的题，每次先圈出目标变量。"
    },
    {
      "questionId": "tmua-specimen-p1-q02",
      "number": 2,
      "correctAnswer": "D",
      "topicZh": "三角方程解的个数",
      "topicEn": "Counting trigonometric solutions",
      "methodZh": "化成 cos θ 的二次方程",
      "methodEn": "Reduce to a quadratic in cosine",
      "keyIdeaZh": "用 sin²θ=1-cos²θ，把问题变成代数方程；代数根还要通过 cos 的值域筛选，再按闭区间数端点。",
      "steps": [
        { "titleZh": "代换", "bodyZh": "令 u=cosθ，原式变为 1-u²+3u=3。", "math": "u^2-3u+2=0" },
        { "titleZh": "筛选代数根", "bodyZh": "得到 u=1 或 u=2；cosθ 不可能等于 2，所以只保留 cosθ=1。", "math": "(u-1)(u-2)=0" },
        { "titleZh": "数闭区间内的解", "bodyZh": "在 0≤θ≤4π 中，θ=0、2π、4π，共 3 个。", "math": "\\theta\\in\\{0,2\\pi,4\\pi\\}" }
      ],
      "conclusionZh": "选择 D（3 个解）。",
      "trapZh": "忘记 0 和 4π 都属于闭区间，或把 cosθ=2 当成真实解。",
      "nextDrillZh": "练习在不同开闭区间内统计 sin/cos 方程解的个数，强制先写值域再画单位圆。"
    },
    {
      "questionId": "tmua-specimen-p1-q03",
      "number": 3,
      "correctAnswer": "B",
      "topicZh": "垂直平分线",
      "topicEn": "Perpendicular bisector",
      "methodZh": "中点 + 负倒数斜率",
      "methodEn": "Midpoint and negative reciprocal gradient",
      "keyIdeaZh": "垂直平分线必须同时通过原线段中点，且斜率是原斜率的负倒数。求 x 轴截距时直接令 y=0。",
      "steps": [
        { "titleZh": "求中点与斜率", "bodyZh": "中点为 (7/2,-1)，原线段斜率为 10/3。", "math": "M=\\left(\\frac72,-1\\right),\\quad m=\\frac{4-(-6)}{5-2}=\\frac{10}3" },
        { "titleZh": "写垂直平分线", "bodyZh": "垂直斜率为 -3/10，用点斜式即可。", "math": "y+1=-\\frac3{10}\\left(x-\\frac72\\right)" },
        { "titleZh": "求截距", "bodyZh": "令 y=0，解得 x=7/2-10/3=1/6。", "math": "x=\\frac16" }
      ],
      "conclusionZh": "选择 B（1/6）。",
      "trapZh": "把负倒数写成 -10/3，或看见负斜率就误判 x 轴截距也必须为负。",
      "nextDrillZh": "分别练一题水平线段和竖直线段的垂直平分线，补齐斜率不存在时的处理。"
    },
    {
      "questionId": "tmua-specimen-p1-q04",
      "number": 4,
      "correctAnswer": "E",
      "topicZh": "多项式不等式",
      "topicEn": "Polynomial inequalities",
      "methodZh": "零点分区间判号",
      "methodEn": "Critical points and sign chart",
      "keyIdeaZh": "把表达式完全因式分解，用零点 -1、1、2 切分数轴；严格大于零时不能包含零点。",
      "steps": [
        { "titleZh": "因式分解", "bodyZh": "原式为 (x+1)(x-1)(x-2)>0。", "math": "(x+1)(x-1)(x-2)>0" },
        { "titleZh": "区间判号", "bodyZh": "从右向左穿过三个单根时符号依次翻转：正、负、正、负。", "math": "(-\\infty,-1):-;\\ (-1,1):+;\\ (1,2):-;\\ (2,\\infty):+" }
      ],
      "conclusionZh": "解集为 -1<x<1 或 x>2，选择 E。",
      "trapZh": "只看二次因子 x²-1 的正负，忽略第三个因子 x-2；或把根包含进严格不等式。",
      "nextDrillZh": "用同一张符号表练 3 个带重根的不等式，观察偶重根处符号不翻转。"
    },
    {
      "questionId": "tmua-specimen-p1-q05",
      "number": 5,
      "correctAnswer": "D",
      "topicZh": "对数函数反解",
      "topicEn": "Rearranging logarithmic functions",
      "methodZh": "先去负号，再指数化",
      "methodEn": "Negate, exponentiate, isolate",
      "keyIdeaZh": "由 log₁₀A=B 得 A=10ᴮ。这里右侧先变成 -y，指数必须是 -y。",
      "steps": [
        { "titleZh": "指数化", "bodyZh": "由 y=-log₁₀(1-x) 得 log₁₀(1-x)=-y。", "math": "1-x=10^{-y}" },
        { "titleZh": "整理目标变量", "bodyZh": "把 x 单独留在一侧。", "math": "x=1-10^{-y}" }
      ],
      "conclusionZh": "选择 D。",
      "trapZh": "把 -log(1-x) 错写成 log(x-1)，或者指数化后把 10^{-y} 写成 10^y。",
      "nextDrillZh": "练习 4 道含 a-bx、负号和不同底数的对数反函数题，并逐步检查定义域。"
    },
    {
      "questionId": "tmua-specimen-p1-q06",
      "number": 6,
      "correctAnswer": "D",
      "topicZh": "因式定理与参数",
      "topicEn": "Factor theorem with a parameter",
      "methodZh": "把因子转成已知根",
      "methodEn": "Convert the factor into a known root",
      "keyIdeaZh": "x+2 是因子等价于把 x=-2 代入多项式后结果为 0；所得是关于 c 的二次方程。",
      "steps": [
        { "titleZh": "代入根", "bodyZh": "将 x=-2 代入。", "math": "(-2)^3+4c(-2)^2-2(c+1)^2-6=0" },
        { "titleZh": "整理参数方程", "bodyZh": "化简后除以 -2。", "math": "c^2-6c+8=0" },
        { "titleZh": "求根的和", "bodyZh": "可因式分解为 (c-2)(c-4)=0；两个可能值之和为 6。", "math": "2+4=6" }
      ],
      "conclusionZh": "选择 D（6）。",
      "trapZh": "把 x+2 的根写成 x=2；或者题目只问和，却做完两个根后忘记相加。",
      "nextDrillZh": "练习因式为 ax+b 的参数题，先写根 x=-b/a，再代入。"
    },
    {
      "questionId": "tmua-specimen-p1-q07",
      "number": 7,
      "correctAnswer": "C",
      "topicZh": "不放回抽样概率",
      "topicEn": "Probability without replacement",
      "methodZh": "利用第一球后的对称性",
      "methodEn": "Condition on the first draw",
      "keyIdeaZh": "第一球是什么颜色不重要。取走它后，剩余 3n-1 个球中，与它不同色的一共有 2n 个。",
      "steps": [
        { "titleZh": "固定第一球", "bodyZh": "无论第一球是哪种颜色，剩余同色 n-1 个、异色 2n 个。", "math": "(n-1)+2n=3n-1" },
        { "titleZh": "写条件概率", "bodyZh": "第二球从剩余球中随机选，因此异色概率为 2n/(3n-1)。", "math": "P(\\text{different})=\\frac{2n}{3n-1}" }
      ],
      "conclusionZh": "选择 C。",
      "trapZh": "把分母继续写成 3n，忘记第一次抽取后总数已减少 1。",
      "nextDrillZh": "分别用“直接算”和“1-同色概率”完成同一道题，确认两条路径给出相同结果。"
    },
    {
      "questionId": "tmua-specimen-p1-q08",
      "number": 8,
      "correctAnswer": "F",
      "topicZh": "指数方程与对数法则",
      "topicEn": "Exponential equations and logarithm laws",
      "methodZh": "合并同一指数后取对数",
      "methodEn": "Collect the common exponent and take logs",
      "keyIdeaZh": "aˣb²ˣc³ˣ=(ab²c³)ˣ。取对数后，x 是乘在 log(ab²c³) 前的系数。",
      "steps": [
        { "titleZh": "合并底数", "bodyZh": "利用指数法则把左侧写成一个整体的 x 次方。", "math": "(ab^2c^3)^x=2" },
        { "titleZh": "取对数并解 x", "bodyZh": "两边取常用对数。", "math": "x\\log_{10}(ab^2c^3)=\\log_{10}2" },
        { "titleZh": "整理", "bodyZh": "所以 x=log₁₀2 / log₁₀(ab²c³)。", "math": "x=\\frac{\\log_{10}2}{\\log_{10}(ab^2c^3)}" }
      ],
      "conclusionZh": "选择 F。",
      "trapZh": "把 log(ab²c³) 错拆成 log(a+2b+3c)，或把分子分母倒置。",
      "nextDrillZh": "练习把乘积、幂与对数互相转换，特别检查 log(uᵏ)=k log u。"
    },
    {
      "questionId": "tmua-specimen-p1-q09",
      "number": 9,
      "correctAnswer": "A",
      "topicZh": "二次方程根的距离",
      "topicEn": "Distance between quadratic roots",
      "methodZh": "用判别式表示两根之差",
      "methodEn": "Express the root gap using the discriminant",
      "keyIdeaZh": "对 ax²+bx+c=0，两根之差的绝对值为 √Δ/|a|。这里也可直接从求根公式读出。",
      "steps": [
        { "titleZh": "写两根", "bodyZh": "由求根公式，根为 (11±√(121-8c))/4。", "math": "x=\\frac{11\\pm\\sqrt{121-8c}}4" },
        { "titleZh": "建立根差", "bodyZh": "两根相减等于 √(121-8c)/2，题设说它为 2。", "math": "\\frac{\\sqrt{121-8c}}2=2" },
        { "titleZh": "解参数", "bodyZh": "平方得到 121-8c=16，因此 c=105/8。", "math": "c=\\frac{105}8" }
      ],
      "conclusionZh": "选择 A。",
      "trapZh": "相减时漏掉 ± 两项产生的系数 2，或平方后仍保留错误的正负号。",
      "nextDrillZh": "练习不完全解根、只用判别式求根距或根距范围的题。"
    },
    {
      "questionId": "tmua-specimen-p1-q10",
      "number": 10,
      "correctAnswer": "D",
      "topicZh": "函数图像变换",
      "topicEn": "Graph transformations",
      "methodZh": "先做纵向反射，再做横向平移",
      "methodEn": "Reflect vertically, then translate horizontally",
      "keyIdeaZh": "关于 y=1 反射把 y=f(x) 变成 y=2-f(x)；向右平移 π/4 要把 x 替换为 x-π/4。",
      "steps": [
        { "titleZh": "反射", "bodyZh": "y=cosx 关于 y=1 反射后为 y=2-cosx。", "math": "y=2-\\cos x" },
        { "titleZh": "右移", "bodyZh": "向右 π/4，把式中的 x 换成 x-π/4。", "math": "y=2-\\cos\\left(x-\\frac\\pi4\\right)" }
      ],
      "conclusionZh": "选择 D。",
      "trapZh": "把向右平移写成 x+π/4；函数内部的平移符号与移动方向相反。",
      "nextDrillZh": "用关键点 x=0 的新位置检查 4 道左右平移题，不靠背口诀。"
    },
    {
      "questionId": "tmua-specimen-p1-q11",
      "number": 11,
      "correctAnswer": "E",
      "topicZh": "指数代换与对数换底",
      "topicEn": "Exponential substitution and change of base",
      "methodZh": "令 u=2ˣ 转成二次方程",
      "methodEn": "Substitute u=2^x",
      "keyIdeaZh": "先解 2ˣ 的值，再把两个 x 相加；logₐm+logₐn=logₐ(mn)。",
      "steps": [
        { "titleZh": "代换", "bodyZh": "令 u=2ˣ，则 u²-8u+15=0。", "math": "(u-3)(u-5)=0" },
        { "titleZh": "还原 x", "bodyZh": "所以 x=log₂3 或 log₂5。", "math": "x_1=\\frac{\\log_{10}3}{\\log_{10}2},\\quad x_2=\\frac{\\log_{10}5}{\\log_{10}2}" },
        { "titleZh": "求和", "bodyZh": "同分母相加，分子合并为 log₁₀15。", "math": "x_1+x_2=\\frac{\\log_{10}15}{\\log_{10}2}" }
      ],
      "conclusionZh": "选择 E。",
      "trapZh": "把 2²ˣ 看成 2x，或把 log3+log5 写成 log8。",
      "nextDrillZh": "练习令 aˣ=u 的指数二次方程，并在最后检查 u>0 的限制。"
    },
    {
      "questionId": "tmua-specimen-p1-q12",
      "number": 12,
      "correctAnswer": "D",
      "topicZh": "棱柱体积与表面积",
      "topicEn": "Prism volume and surface area",
      "methodZh": "分别建模后令数值相等",
      "methodEn": "Model volume and surface area separately",
      "keyIdeaZh": "边长 2x 的等边三角形面积为 √3x²；总表面积还要包含两个三角形端面和三个矩形侧面。",
      "steps": [
        { "titleZh": "体积", "bodyZh": "横截面积为 √3x²，所以体积为 √3x²d。", "math": "V=\\sqrt3x^2d" },
        { "titleZh": "总表面积", "bodyZh": "两端面积为 2√3x²，三块侧面总面积为 3·2x·d=6xd。", "math": "S=2\\sqrt3x^2+6xd" },
        { "titleZh": "解 d", "bodyZh": "令 V=S，移项并化简。", "math": "d=\\frac{2x}{x-2\\sqrt3}" }
      ],
      "conclusionZh": "选择 D。",
      "trapZh": "只算侧面积，漏掉两个三角形端面；或者把等边三角形高写成 √3x/2。",
      "nextDrillZh": "为三棱柱、圆柱各写一次“体积/表面积/单位”三列表。"
    },
    {
      "questionId": "tmua-specimen-p1-q13",
      "number": 13,
      "correctAnswer": "C",
      "topicZh": "四次函数实根个数",
      "topicEn": "Number of real roots of a quartic",
      "methodZh": "改写成非负结构判断交点",
      "methodEn": "Rewrite into a non-negative structure",
      "keyIdeaZh": "x⁴-4x³+4x²=x²(x-2)²，所以方程等价于 [x(x-2)]²=10。只需分析两个二次方程。",
      "steps": [
        { "titleZh": "识别完全平方", "bodyZh": "左侧前三项为 x²(x-2)²。", "math": "[x(x-2)]^2=10" },
        { "titleZh": "分两种情况", "bodyZh": "x(x-2)=√10 的判别式为 4+4√10>0，有两根；x(x-2)=-√10 的判别式为 4-4√10<0，无实根。", "math": "x^2-2x=\\pm\\sqrt{10}" }
      ],
      "conclusionZh": "共有 2 个实根，选择 C。",
      "trapZh": "看到四次就猜 4 个根；多项式次数只是复根总数上限，不代表实根数量。",
      "nextDrillZh": "练习把偶次多项式改写成平方或令 u=x(x-a)，再判断实根数量。"
    },
    {
      "questionId": "tmua-specimen-p1-q14",
      "number": 14,
      "correctAnswer": "D",
      "topicZh": "双对数直线化",
      "topicEn": "Log-log linearisation",
      "methodZh": "对候选关系取对数",
      "methodEn": "Take logs of the candidate model",
      "keyIdeaZh": "log y 对 log x 是直线，必须能写成 log y=m log x+c；这正对应幂律 y=axᵇ。",
      "steps": [
        { "titleZh": "写直线形式", "bodyZh": "令横轴 X=logx、纵轴 Y=logy，直线满足 Y=mX+c。", "math": "\\log y=m\\log x+c" },
        { "titleZh": "还原原变量", "bodyZh": "把 c 写成 loga，则 logy=log(xᵐ)+loga=log(axᵐ)。", "math": "y=ax^m" }
      ],
      "conclusionZh": "与选项 D 的 y=axᵇ 同型，选择 D。",
      "trapZh": "把半对数模型 y=abˣ 与双对数模型混淆；前者是 logy 对 x 成直线。",
      "nextDrillZh": "比较 linear、semi-log、log-log 三种图各自对应的函数模型。"
    },
    {
      "questionId": "tmua-specimen-p1-q15",
      "number": 15,
      "correctAnswer": "A",
      "topicZh": "含参数积分的最小值",
      "topicEn": "Minimising a parameterised integral",
      "methodZh": "先积分，再对参数配方",
      "methodEn": "Integrate, then complete the square",
      "keyIdeaZh": "积分变量是 x，a 在积分时视为常数。得到关于 a 的二次式后再求最小值。",
      "steps": [
        { "titleZh": "展开并积分", "bodyZh": "积分 x²-2ax+a²。", "math": "\\int_0^1(x-a)^2dx=\\frac13-a+a^2" },
        { "titleZh": "配方", "bodyZh": "把关于 a 的二次式写成平方加常数。", "math": "a^2-a+\\frac13=\\left(a-\\frac12\\right)^2+\\frac1{12}" }
      ],
      "conclusionZh": "平方项最小为 0，所以最小值是 1/12，选择 A。",
      "trapZh": "把 a 当积分变量，或积分完只代上下限却没有继续对 a 最优化。",
      "nextDrillZh": "练习“最佳常数逼近”类型积分题，观察最优 a 与区间平均值的关系。"
    },
    {
      "questionId": "tmua-specimen-p1-q16",
      "number": 16,
      "correctAnswer": "E",
      "topicZh": "质因数指数与整数条件",
      "topicEn": "Prime exponents and integrality",
      "methodZh": "全部拆成 2 与 5 的幂",
      "methodEn": "Resolve into prime powers",
      "keyIdeaZh": "一个正有理数是整数时，最简质因数分解中的每个指数都必须非负。这里不需要展开大数。",
      "steps": [
        { "titleZh": "质因数分解", "bodyZh": "使用 10=2·5、20=2²·5、8=2³、125=5³，合并指数。", "math": "\\frac{10^{c-2d}20^{2c+d}}{8^c125^{c+d}}=2^{2c}5^{-4d}" },
        { "titleZh": "施加整数条件", "bodyZh": "需 2c≥0 且 -4d≥0。c、d 均为非零整数，所以 c>0 且 d<0。", "math": "c>0,\\quad d<0" }
      ],
      "conclusionZh": "选择 E。",
      "trapZh": "只检查总指数的和，或认为“d<0”单独就足够；2 和 5 的指数必须分别检查。",
      "nextDrillZh": "练习含 2、3、5 三种质因子的整数条件题，给每种质数单独列一行指数。"
    },
    {
      "questionId": "tmua-specimen-p1-q17",
      "number": 17,
      "correctAnswer": "D",
      "topicZh": "参数二次方程的不同实根",
      "topicEn": "Distinct real roots with a parameter",
      "methodZh": "判别式严格大于零",
      "methodEn": "Require a strictly positive discriminant",
      "keyIdeaZh": "题目已规定 a≠0，方程确为二次方程；有两个不同实根等价于判别式 Δ>0。",
      "steps": [
        { "titleZh": "标准化", "bodyZh": "移项得 ax²+(a-2)x-2=0。", "math": "ax^2+(a-2)x-2=0" },
        { "titleZh": "计算判别式", "bodyZh": "Δ=(a-2)²-4a(-2)=(a+2)²。", "math": "\\Delta=(a+2)^2" },
        { "titleZh": "严格不等式", "bodyZh": "平方只在 a=-2 时为 0，其余非零 a 均使 Δ>0。", "math": "a\\ne-2" }
      ],
      "conclusionZh": "选择 D。",
      "trapZh": "把“有实根”用 Δ≥0，而忽略 distinct 要求严格大于 0。",
      "nextDrillZh": "练习同时检查二次项系数不为 0 与 Δ 条件的参数题。"
    },
    {
      "questionId": "tmua-specimen-p1-q18",
      "number": 18,
      "correctAnswer": "B",
      "topicZh": "三角不等式区间交集",
      "topicEn": "Intersection of trigonometric intervals",
      "methodZh": "分别解区间，再取交集",
      "methodEn": "Solve separately, then intersect",
      "keyIdeaZh": "不要把两个不等式混在一起代数操作。先在 0≤x≤π 上分别标出 tan 条件和 sin2x 条件，再只保留重叠区间。",
      "steps": [
        { "titleZh": "解 tan 条件", "bodyZh": "在给定区间内，-1<tanx≤1 给出 [0,π/4] 与 (3π/4,π]，端点开闭不影响最终长度。", "math": "x\\in[0,\\frac\\pi4]\\cup(\\frac{3\\pi}4,\\pi]" },
        { "titleZh": "解 sin 条件", "bodyZh": "sin2x≥1/2 且 0≤2x≤2π，得到 π/12≤x≤5π/12。", "math": "x\\in[\\frac\\pi{12},\\frac{5\\pi}{12}]" },
        { "titleZh": "取交集并求长度", "bodyZh": "交集为 [π/12,π/4]，长度 π/4-π/12=π/6。", "math": "\\frac\\pi4-\\frac\\pi{12}=\\frac\\pi6" }
      ],
      "conclusionZh": "选择 B。",
      "trapZh": "解 sin2x 时忘记自变量是 2x，导致区间端点没有除以 2。",
      "nextDrillZh": "在同一条数轴上练习两个周期函数不等式的交集，并明确写出变量变换后的区间。"
    },
    {
      "questionId": "tmua-specimen-p1-q19",
      "number": 19,
      "correctAnswer": "D",
      "topicZh": "等比数列与等差条件",
      "topicEn": "Geometric series with an arithmetic condition",
      "methodZh": "用等差中项条件建立 r 方程",
      "methodEn": "Use the arithmetic-middle-term condition",
      "keyIdeaZh": "等比数列第 1、2、4 项是 4、4r、4r³；连续等差三项满足中间项的两倍等于首尾和。",
      "steps": [
        { "titleZh": "建立条件", "bodyZh": "由 2·4r=4+4r³，除以 4。", "math": "2r=1+r^3" },
        { "titleZh": "筛选公比", "bodyZh": "整理为 (r-1)(r²+r-1)=0。0<r<1 排除 r=1，保留 r=(√5-1)/2。", "math": "r=\\frac{\\sqrt5-1}{2}" },
        { "titleZh": "求无穷和", "bodyZh": "S∞=4/(1-r)，有理化后为 2(3+√5)。", "math": "S_\\infty=2(3+\\sqrt5)" }
      ],
      "conclusionZh": "选择 D。",
      "trapZh": "把等比数列的第四项写成 4r⁴；第 n 项是 ar^{n-1}。",
      "nextDrillZh": "练习从非相邻等比项构造等差条件，并在解出 r 后用范围筛根。"
    },
    {
      "questionId": "tmua-specimen-p1-q20",
      "number": 20,
      "correctAnswer": "G",
      "topicZh": "指定项系数",
      "topicEn": "Coefficient extraction",
      "methodZh": "只保留到 x² 的截断展开",
      "methodEn": "Truncate the expansion at the required degree",
      "keyIdeaZh": "题目只问 x² 系数，不必完整展开。第二个括号 (1+4x³)⁵ 在 x² 及以下只有常数 1。",
      "steps": [
        { "titleZh": "展开第一项到 x²", "bodyZh": "令 u=2x+3x²，(1+u)⁶=1+6u+15u²+…，得到 1+12x+78x²+…。", "math": "(1+2x+3x^2)^6=1+12x+78x^2+O(x^3)" },
        { "titleZh": "处理相减", "bodyZh": "(1+4x³)⁵=1+O(x³)，所以方括号为 12x+78x²+O(x³)。", "math": "[\\cdots]=12x+78x^2+O(x^3)" },
        { "titleZh": "乘外层", "bodyZh": "乘 (4-x²) 时，-x² 与方括号最低次 12x 相乘至少是 x³，不贡献 x²；所求为 4·78。", "math": "[x^2]=4\\times78=312" }
      ],
      "conclusionZh": "选择 G（312）。",
      "trapZh": "为整式做完全展开，增加计算量；或忘记相减后两个常数 1 抵消。",
      "nextDrillZh": "练习用 O(x³) 或“只保留所需次数”处理 3 道系数题，减少无效展开。"
    }
  ]
}
$payload$::jsonb
)
on conflict (resource_id) do update
set schema_version = excluded.schema_version,
    source_sha256 = excluded.source_sha256,
    payload = excluded.payload,
    updated_at = now();
